### ISSUE TITLE
Exception when using function VMM_PidList.

### ISSUE THREAD

**Issue by leolongvu** [ufrisk/MemProcFS#10]
Dear Ufrisk

I keep getting the following exception when trying to use VMMDLL_PidList(pPIDs, pcPIDs). I guess that is due to my initialization of the array:

Exception thrown at 0x00007FFB2CE6A054 (ucrtbased.dll) in vmm_example.exe: 0xC0000005: Access violation reading location 0x000000000000011A.

The initialization I have tried:

DWORD pIDs[1000]; // not working
DWORD *arrayPointer;
arrayPointer = pIDs; // not working
PDWORD pIDs; // not working
PDWORD pIDs[1000]; // not working

Can you please suggest a simple way to pass the arguments through the function.

Leo

**Comment by ufrisk** [comment]
Can you please try
```C

PDWORD pdwPIDs;
ULONG64 cPIDs = 0;
VMMDLL_PidList(NULL, &cPIDs);
pdwPIDs = LocalAlloc(LMEM_ZEROINIT, cPIDs * sizeof(DWORD));
VMMDLL_PidList(pdwPIDs , &cPIDs);

// or if lazy and guessing no more than 1024 pids

DWORD dwPIDs[1024] = { 0 };
ULONG64 cPIDs = 1024;
VMMDLL_PidList(dwPIDs, &cPIDs);

```

**Comment by leolongvu** [comment]
I have actually just found the error. The problem lies in the cPIDs. I can check that both of your initialization is Success, however when I use `printf(cPIDs)` it starts throwing the exception. I am looking into it since this is just an IO issue. Many thanks for your help.

**Comment by ufrisk** [comment]
C# makes a lot of sense :) it's lots of easier for most users, it would be really nice to be able to use this in C# :)

**Comment by ufrisk** [comment]
Closing issue since it seems to be resolved.

Looking forward to the result of this. C# would be hugely helpful for a lot of people.
