### ISSUE TITLE
VMMDLL_Map_GetPool always return false.

### ISSUE THREAD

**Issue by lolirape69** [ufrisk/MemProcFS#100]
i've been trying to use the exact same code as example but somehow it always returns false. Someone knows anything?. Thank you

VMMDLL_Map_GetPool

**Comment by ufrisk** [comment]
do you have the required supporting files next to vmm.dll?

The files are: `symsrv.dll` and `dbghelp.dll`. They can be found in the binary download package.

additional optional on Windows (and required on Linux) is `info.db`

**Comment by lolirape69** [comment]
thank you Ulf! its working fine now.

**Comment by ufrisk** [comment]
Awesome, and thanks for letting me know about this issue. You're not the first one that asks it. I'll update the API documentation in the header file comments in the next version.

Please let me know if you should run into something else. And I wish you the best with your memory analysis project 👍
