### ISSUE TITLE
Multiple DMA device

### ISSUE THREAD

**Issue by lolirape69** [ufrisk/MemProcFS#101]
Hello ulf, thanks for your great project !, its been really helpful on memory studying. 

My question is, is it possible to control multiple dma devices using only 1 pc?.

For example i have 1 laptop, then i have 2 PCs with dma on each one.

Is there any parameter to initialize or identify each USB for them?. Thank you!.

**Comment by ufrisk** [comment]
Check out the devindex option

https://github.com/ufrisk/LeechCore/wiki/Device_FPGA

`-device fpga://devindex=0`  or `-device fpga://devindex=1` etc.

**Comment by lolirape69** [comment]
Thank you for fast response ulf!.
