### ISSUE TITLE
Support for .lime format

### ISSUE THREAD

**Issue by guyhacker** [ufrisk/MemProcFS#110]
Add .lime support. Actualy the tool only supports .raw format.

**Comment by ufrisk** [comment]
Thank you for this enhancement suggestion. I'll add lime support soonish.

**Comment by ufrisk** [comment]
just checking, I just want to make sure you're trying to mount a Windows memory dump in lime format with MemProcFS?

Analyzing Linux images aren't supported by this tool.

**Comment by guyhacker** [comment]
Yes, It is a windows dump in lime format.
Regards.

**Comment by ufrisk** [comment]
Great and huge thanks for confirming, I'll see to it that the lime format is added. I'm going away for a few weeks so it will probably happen some time after that.

**Comment by ufrisk** [comment]
stupid question, but where do I find lime for windows, or any windows dumps created with lime?

**Comment by guyhacker** [comment]
Hi. let me see if I can get one for you online.
Regards.

**Comment by ufrisk** [comment]
I'm closing this issue.

I don't think the tools you mentioned earlier on (in separate conversation) actually dumps to the .lime format, they rather dump to a raw dump file with file ending of .lime.

If you get hold of a Windows memory dump in the lime format please let me know and I'll gladly look into it. Until then I'm closing this enhancement suggestions though.

**Comment by ufrisk** [comment]
I've now added support for the LiME format. I managed to source an example memory dump elsewhere so now it's added. It should be possible to mount the LiME memory dump as any other memory dump. It should be auto-detected.

**Comment by guyhacker** [comment]
Thanks very much. I will download the new tool right away.
Regards.
