### ISSUE TITLE
DEVICE: ERROR: Unable to load driver into kernel.

### ISSUE THREAD

**Issue by johnjohnsp1** [ufrisk/MemProcFS#112]
Hi Ulk,
i'm trying to run memprocfs and mount live system with the following examples but keep getting error

prompt is run as administrator

C:\temp\MemProcFS_files_and_binaries_v5>MemProcFS.exe -device pmem://c:\temp\MemProcFS_files_and_binaries_v5\winpmem_64.sys
DEVICE: ERROR: Unable to load driver into kernel.
Is project executable running from the C:\ drive ?
DEVICE: ERROR: Unable to load driver into kernel.
Is project executable running from the C:\ drive ?
MemProcFS: Failed to connect to memory acquisition device.

C:\temp\MemProcFS_files_and_binaries_v5>MemProcFS.exe -device pmem://c:\\temp\\MemProcFS_files_and_binaries_v5\\winpmem_64.sys
DEVICE: ERROR: Unable to load driver into kernel.
Is project executable running from the C:\ drive ?
DEVICE: ERROR: Unable to load driver into kernel.
Is project executable running from the C:\ drive ?
MemProcFS: Failed to connect to memory acquisition device.

C:\temp\MemProcFS_files_and_binaries_v5>MemProcFS.exe -device pmem://c://temp//MemProcFS_files_and_binaries_v5//winpmem_64.sys
DEVICE: ERROR: Unable to load driver into kernel.
Is project executable running from the C:\ drive ?
DEVICE: ERROR: Unable to load driver into kernel.
Is project executable running from the C:\ drive ?
MemProcFS: Failed to connect to memory acquisition device.

C:\temp\MemProcFS_files_and_binaries_v5>copy winpmem_64.sys c:\
        1 file(s) copied.

C:\temp\MemProcFS_files_and_binaries_v5>MemProcFS.exe -device pmem://c:\\winpmem_64.sys
DEVICE: ERROR: Unable to load driver into kernel.
Is project executable running from the C:\ drive ?
DEVICE: ERROR: Unable to load driver into kernel.
Is project executable running from the C:\ drive ?
MemProcFS: Failed to connect to memory acquisition device.

i dont understand where actually i need to put the winpmem_64.sys driver in order to make it loaded correctly
i do anything wrong ?

thanks

**Comment by ufrisk** [comment]
Are you running MemProcFS from an elevated administrator command prompt? This is required to load the driver.

If you are you may also find some additional info in the Event Viewer.

Please let me know if you got it to work.

**Comment by johnjohnsp1** [comment]
I did run the prompt as administrator, this is the source where i get driver:
https://github.com/Velocidex/WinPmem/blob/master/kernel/binaries/winpmem_x64.sys

still fail:

C:\temp\MemProcFS_files_and_binaries_v5>dir *mem*
 Volume in drive C has no label.
 Volume Serial Number is 565E-C16D

 Directory of C:\temp\MemProcFS_files_and_binaries_v5

08/03/2022  10:10 PM            45,512 MemProcFS.exe
06/29/2022  11:42 PM            13,735 memprocfs.py
06/29/2022  11:42 PM            14,749 memprocfs_example.py
08/03/2022  10:09 PM            11,776 pluginsm_vmemd.dll
06/09/2021  02:35 PM            36,176 winpmem_64.sys
               5 File(s)        121,948 bytes
               0 Dir(s)  21,321,084,928 bytes free

C:\temp\MemProcFS_files_and_binaries_v5>MemProcFS.exe -device pmem
DEVICE: ERROR: unable to locate the winpmem driver file ''.
DEVICE: ERROR: unable to locate the winpmem driver file ''.
MemProcFS: Failed to connect to memory acquisition device.

run on windows 10 version 21H2 (OSBuild 19044.1826)

on the event viewer im getting a eventid 7000 complaining about the pmem driver:
The pmem service failed to start due to the following error: 
Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

looks like the problem is the driver ... i will attach a screenshot
i have installed on this client sophos A/V.

let me know if you find anything 
thanks
![memprocfs](https://user-images.githubusercontent.com/1888855/182816974-08fb59a2-e614-4bb2-8df5-bbff54cdf9f3.PNG)

**Comment by ufrisk** [comment]
I don't know if this is your error, but it seems like the file downloaded from:
https://github.com/Velocidex/WinPmem/blob/master/kernel/binaries/winpmem_x64.sys
does not have a valid signature.

The file downloaded from:
https://github.com/Velocidex/WinPmem/raw/master/kernel/binaries/winpmem_x64.sys
seems to have a valid signature.

I don't understand this, but try download from the 2nd link and re-try. It may be something else as well...

Please let me know how it goes, it it works I'll update my documentation, right now it seems like I'm pointing to both the blob and raw locations on github.

**Comment by johnjohnsp1** [comment]
it worked with the 2nd driver, awesome, thanks really much !!

**Comment by johnjohnsp1** [comment]
![memprocfs_working](https://user-images.githubusercontent.com/1888855/182821710-27349b50-cd5b-4a5f-9df4-a60a062accba.PNG)

**Comment by ufrisk** [comment]
awesome! and best wishes with everything!

I'll update the links in the documentation.

**Comment by ufrisk** [comment]
The guide entry should now be updated as well. Thank You for reporting this.
