### ISSUE TITLE
Map_GetPfn of vmmsharp returns wrong MAP_PFNENTRY.tp value

### ISSUE THREAD

**Issue by geun-yeong** [ufrisk/MemProcFS#114]
In case of my WinPmem dump file, PFN 1 is Active. MemProcFS of python returns Active too.

But vmmsharp returns it as Free. Below picture shows that _u3 of VMMDLL_MAP_PFNENTRY has 0x00560001.

![image](https://user-images.githubusercontent.com/31948038/183368720-7614cfc1-f89b-49ee-93d8-30cc314bf83c.png)

Currently, Map_GetPfn of vmmsharp gets tp value using AND operation with _u3 and 0x7. In my opinion, code of the Map_GetPfn needs to be fixed.

[before]
e.tp = (MAP_PFN_TYPE)(n._u3 & 0x07);

[after]
e.tp = (MAP_PFN_TYPE)((n._u3 & 0x00070000) >> 16);

I have used MemProcFS version 4.9.3, 64-bits vmm.dll and leechcore.dll and have developed on Windows 11 21H2 64-bits.

Thanks.

**Comment by ufrisk** [comment]
Many thanks for this excellent bug report.

I've now fixed it in the v5.0.3 version I just pushed to Github. In the v5 version the C# API have changed a little bit.

I will not be fixing the old 4.9.3 version, but if you wish to continue using it I believe it should easy to change yourself.

But the latest version is now fixed. Once again thank you for reporting this.
