### ISSUE TITLE
VMMDLL_Map_GetPool sometimes return false.

### ISSUE THREAD

**Issue by 0xGabriella** [ufrisk/MemProcFS#115]
Hello Ulf! wishing you good luck everytime.

Having a little problem with VMMDLL_Map_GetPool, even with required dependencies like (symsrv.dll, dbghelp.dll and info.db) its still failing. Only works after tons of pc restart, then it will break again after a while. Thank you!.

**Comment by ufrisk** [comment]
Many thanks, and also thank you for the sponsorship :)

Which version are you experiencing this issue on. Are you using the older version 4.9 or the new version 5 I released just last week?

If you are experiencing this on the v5 is it the same behavior in the v4.9 version? Or did things get worse with the upgrade.

Unfortunately I'm away from home and won't be back until next week. But hoprfully we can solve this together when I know which version you're using.

**Comment by 0xGabriella** [comment]
Hello Ulf!, looks like the problem was my windows. I did a fresh install and its resolved. Also tried the latest version which is amazing! Thank you for your hard work
