### ISSUE TITLE
I am a new developer of DMA. I use C #

### ISSUE THREAD

**Issue by bbhxwl** [ufrisk/MemProcFS#116]
I am a new developer of DMA. I use C #. I have DMA hardware. Now I want to understand how I use C # to read the memory of another computer. What should be the steps? thank you

**Comment by ufrisk** [comment]
Please have a look at the C# example file. Get it running and work from there. https://github.com/ufrisk/MemProcFS/blob/master/vmmsharp/vmm_example.cs

Best wishes with your DMA attacks and please let me know how it goes.

**Comment by bbhxwl** [comment]
> Please have a look at the C# example file. Get it running and work from there. https://github.com/ufrisk/MemProcFS/blob/master/vmmsharp/vmm_example.cs
> 
> Best wishes with your DMA attacks and please let me know how it goes.

I failed to initialize in the first step. I don't know why.

But I'm sure my DMA is good, because I can use other people's DMA games to cheat

**Comment by bbhxwl** [comment]
> Please have a look at the C# example file. Get it running and work from there. https://github.com/ufrisk/MemProcFS/blob/master/vmmsharp/vmm_example.cs
> 
> Best wishes with your DMA attacks and please let me know how it goes.

···
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using vmmsharp;

namespace WindowsFormsApp8
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        Vmm vmm = null;
        private void Form1_Load(object sender, EventArgs e)
        {
            try
            {
                vmm = new Vmm("-printf", "-v", "-device", "fpga");
            }
            catch (Exception ex)
            {

                MessageBox.Show(ex.Message);
            }
          
        }

        private void button1_Click(object sender, EventArgs e)
        {
            uint[] dwPidAll = vmm.PidList();
            if (dwPidAll!=null&& dwPidAll.Length>0)
            {
                MessageBox.Show("获取到了"+ dwPidAll.Length);
                for (int i = 0; i < dwPidAll.Length; i++)
                {
                    string strKernel32KernelPath = vmm.ProcessGetInformationString(dwPidAll[i], Vmm.VMMDLL_PROCESS_INFORMATION_OPT_STRING_PATH_KERNEL);
                    MessageBox.Show(strKernel32KernelPath);
                }
            }
            else
            {
                MessageBox.Show("没获取到");
            }
        }
    }
}

···

**Comment by ufrisk** [comment]
I'm currently away until next week.

In the meanwhile can you please verify it works with the example project I have? Also if DMA works at all with standard memprocfs exe downloaded from releases.

Please let me know how it goes. If unwell Ill try to look closer into it next week

**Comment by bbhxwl** [comment]
> I'm currently away until next week.
> 
> In the meanwhile can you please verify it works with the example project I have? Also if DMA works at all with standard memprocfs exe downloaded from releases.
> 
> Please let me know how it goes. If unwell Ill try to look closer into it next week

![image](https://user-images.githubusercontent.com/26525599/184195065-69a34f0a-7481-429e-859e-a3ed2ecbcf78.png)
I really don't understand why my DMA can't read. Cannot initialize

**Comment by bbhxwl** [comment]
> I'm currently away until next week.
> 
> In the meanwhile can you please verify it works with the example project I have? Also if DMA works at all with standard memprocfs exe downloaded from releases.
> 
> Please let me know how it goes. If unwell Ill try to look closer into it next week

![image](https://user-images.githubusercontent.com/26525599/184195555-9bd1e09e-35f2-46be-a1fc-c175d27ad4df.png)

**Comment by ufrisk** [comment]
DMA should work with standard MemProcFS, you may have to generate a manual memory map first though, especially if running over Thunderbolt or on AMD CPUs. Please see [here](https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt).

Also to see more detailed information about the error do `memprocfs.exe -device fpga -memmap <your_memmap_file.txt> -v`

**Comment by bbhxwl** [comment]
> DMA should work with standard MemProcFS, you may have to generate a manual memory map first though, especially if running over Thunderbolt or on AMD CPUs. Please see [here](https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt).
> 
> Also to see more detailed information about the error do `memprocfs.exe -device fpga -memmap <your_memmap_file.txt> -v`

Can I pay to learn from you? There should be no need to set any system configuration now. It can be read by software. My name is surface Pro3. I can read memory data by using software developed by others

So I suspect that something is missing from the code.

**Comment by ufrisk** [comment]
I'm sorry, I'm kinda busy so I don't have much time to do private trainings and such. It's possible that someone else might be able to help you here if you ask around.

**Comment by bbhxwl** [comment]
> Please have a look at the C# example file. Get it running and work from there. https://github.com/ufrisk/MemProcFS/blob/master/vmmsharp/vmm_example.cs
> 
> Best wishes with your DMA attacks and please let me know how it goes.

FTD3XX.dll
If you put this file together with memprocfs, you can use memprocfs, but my C # code is still unreadable. Why? Do you need to set any parameters?

**Comment by imerzan** [comment]
> > Please have a look at the C# example file. Get it running and work from there. https://github.com/ufrisk/MemProcFS/blob/master/vmmsharp/vmm_example.cs
> > Best wishes with your DMA attacks and please let me know how it goes.
> 
> FTD3XX.dll If you put this file together with memprocfs, you can use memprocfs, but my C # code is still unreadable. Why? Do you need to set any parameters?

Sounds like you are using this for game cheats, I would check the UnknownCheats forums for more help, would be better suited than here.
