### ISSUE TITLE
vmm init failed?

### ISSUE THREAD

**Issue by bbhxwl** [ufrisk/MemProcFS#117]
```
vmm = new Vmm("-printf", "-v", "-device", "fpga");
```

I am sure that I have DMA and can use other people's DMA assistance normally. Why does my initialization fail?

![B75D35A6F4BD2F070E9CDB9FD5060331](https://user-images.githubusercontent.com/26525599/184191134-58a137ef-37f8-4322-b890-051db9a3c718.png)
![B4B7910A28F964F9E10BE3A1A86EB243](https://user-images.githubusercontent.com/26525599/184191150-aa6f8b9a-0d8f-4f8d-9a0b-fc2074a9a618.png)

**Comment by ufrisk** [comment]
Apologies, but I don't support the RaptorDMA board or its custom software. Please contact the makers of RaptorDMA for support about their software or any custom software created around it.

**Comment by bbhxwl** [comment]
> Apologies, but I don't support the RaptorDMA board or its custom software. Please contact the makers of RaptorDMA for support about their software or any custom software created around it.


I refer to your C # demo for this code. Wrong, I don't know why?


```
 private void Form1_Load(object sender, EventArgs e)
        {
            try
            {
                vmm = new Vmm("-device", "fpga");
            }
            catch (Exception ex)
            {

                MessageBox.Show(ex.Message);
            }
          
        }
```

**Comment by bbhxwl** [comment]
> Apologies, but I don't support the RaptorDMA board or its custom software. Please contact the makers of RaptorDMA for support about their software or any custom software created around it.

Why does initialization fail? My DMA must be good.

**Comment by ufrisk** [comment]
1. have you tried to use binary distrubution of MemProcFS, i.e. try to get the DMA working first without using the API?
3. your C# application would need to be compiled as 64-bit to be able to load the 64-bit DLLs required.
4. for more extensive error messages do: vmm = new Vmm("-printf", "-v", "-vv", "-device", "fpga");

**Comment by bbhxwl** [comment]
> 1. have you tried to use binary distrubution of MemProcFS, i.e. try to get the DMA working first without using the API?
> 2. your C# application would need to be compiled as 64-bit to be able to load the 64-bit DLLs required.
> 3. for more extensive error messages do: vmm = new Vmm("-printf", "-v", "-vv", "-device", "fpga");

 vmm = new Vmm("", "-device", "fpga");
I can use the following code, but I don't know why. Just add an empty string in front of the parameter? And another reason is that I lack FTD3xx.dll

**Comment by bbhxwl** [comment]
```
process.memory.read(int: address_virtual, int: bytes_to_read, opt int: flags) # -> bytes

```
It seems that the python document is simpler and much simpler than C #.

**Comment by bbhxwl** [comment]
But C # does not see the corresponding method.

**Comment by ufrisk** [comment]
Please check the example file, it's not 1:1 with the Python API but here it is:

```C#
        // read first 128 bytes of kernel32.dll
        byte[] dataKernel32MZ = vmm.MemRead(dwExplorerPID, mModuleKernel32.vaBase, 128, 0);
```

you specify the pid as well as the address, size and flags.
