### ISSUE TITLE
C# Map_GetEAT

### ISSUE THREAD

**Issue by alechy** [ufrisk/MemProcFS#121]
use fpga.

return value is wrong.

![Uploading getEAT.png…]()

**Comment by alechy** [comment]
![getEAT](https://user-images.githubusercontent.com/19263422/184531432-6d916b32-14c8-4d1f-8bf1-5b8da18754ae.png)

**Comment by ufrisk** [comment]
Hi, this seems to be a bug in the new v5 version. Ill fix it next week once home from defcon.

I just want to make sure you're experiencing this issue on the latest v5 release?

**Comment by alechy** [comment]
yes , v5 have this bug, and v4 is work fine.

**Comment by ufrisk** [comment]
Please try the new update I just released in releases section. Please let me know how it goes.

**Comment by alechy** [comment]
yes, work fine,now.thx!
