### ISSUE TITLE
Writing through ScatterApi crashes with AccessViolationException while direct MemWrite works

### ISSUE THREAD

**Issue by uberhalit** [ufrisk/MemProcFS#122]
Reading/writing directly through `MemRead()` and `MemWrite()` works fine, reading using ScatterApi works as well but trying to write anything via ScatterApi `PrepareWrite -> Execute` crashes with a System.AccessViolationException. I added a minimal C# example below. Is there something wrong with my scatter init?
```cs
Vmm vmm = new Vmm("-printf", "-v", "-device", "fpga");
vmm.PidGetFromName("explorer.exe", out uint dwExplorerPID);
ulong vaExplorerBase = vmm.ProcessGetModuleBase(dwExplorerPID, "explorer.exe");

await Task.Delay(1000);
byte[] data = vmm.MemRead(dwExplorerPID, vaExplorerBase, 8, Vmm.FLAG_NOCACHE | Vmm.FLAG_NOPAGING);

// works...
vmm.MemWrite(dwExplorerPID, vaExplorerBase, data);

// crashes...
VmmScatter scatterApi = vmm.Scatter_Initialize(dwExplorerPID, Vmm.FLAG_NOCACHE);
scatterApi.PrepareWrite(vaExplorerBase, data);
scatterApi.Execute(); // System.AccessViolationException: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."
scatterApi.Clear(dwExplorerPID, Vmm.FLAG_NOCACHE);
scatterApi.Close();

vmm.Close();
```

**Comment by ufrisk** [comment]
Thanks. I'll take a look at this. Issue is most probably that I never actually tested this code path. It's quite new and not too often used I think. Huge thanks for reporting :)

**Comment by ufrisk** [comment]
I updated this now. Please try it again. Please let me know how it goes and once again thanks for reporting this issue.

**Comment by uberhalit** [comment]
Thank you for your quick fix. It is working fine now. Just one question, how exactly does the ScatterWrite behave internally if I for example write 2 Ints like so:
```
ScatterWrite(base + 0x0, int1);
ScatterWrite(base + 0x8, int2);
```
There is a 4 bytes space between them, does ScatterWrite write them both at once and fills out the void inbetween from cache?

**Comment by ufrisk** [comment]
it's written in two separate pcie packets at the very same time. nothing will be written to the in-between void.

Since this issue is now resolved I'm closing this issue. Please let me know if you should run into anything else that isn't how it's supposed to be.
