### ISSUE TITLE
Why do some people fail to initialize?

### ISSUE THREAD

**Issue by bbhxwl** [ufrisk/MemProcFS#127]
Why do some people fail to initialize?
Some people can, some people can't. But I can use other people's programs and DMA, which means that my initialization code compatibility is not enough. Do not know why?

  vmm = new Vmm("", "-device", "fpga");

**Comment by ufrisk** [comment]
I don't know why. Maybe try using `vmm = new Vmm("-device", "fpga");` or `vmm = new Vmm("-printf", "-v", "-vv", "-device", "fpga");` for extra debug output. Please let me know how it goes.

**Comment by bbhxwl** [comment]
> I don't know why. Maybe try using `vmm = new Vmm("-device", "fpga");` or `vmm = new Vmm("-printf", "-v", "-vv", "-device", "fpga");` for extra debug output. Please let me know how it goes.

Is there any way to obtain these outputs? I send the test to others and output it to the console. They can't see it.

**Comment by gaygaygay** [comment]
> I don't know why. Maybe try using `vmm = new Vmm("-device", "fpga");` or `vmm = new Vmm("-printf", "-v", "-vv", "-device", "fpga");` for extra debug output. Please let me know how it goes.

hi~everything was fine yesterday. But today I met a problem in initialization. error log says: [INFODB] INIT:FAIL:va=0xfffff8065ca00000

**Comment by ufrisk** [comment]
Closing issue due to old age. In the case of bad memory I'd most frequently require a memory dump to find the issue. I hope this issue is quite rare nowdays. But if you still have issues please let me know.
