### ISSUE TITLE
Issue Printing Data via PrintHexAscii Function C++

### ISSUE THREAD

**Issue by MrCoInSanity** [ufrisk/MemProcFS#128]
Hello, So I've been trying to follow the c/c++ example and I successfully read the memory, but i'm having trouble displaying the data in my console, it doesn't print out anything. The Example is on line 249 to 283 in the vmmdll_example.c;

I had to change up the PrintHexAscii function to work with C++ and I think this is my problem. Below you will find the output to the console and then the function I have changed. 
**Console Output-----**
CALL:    VMMDLL_MemRead - BEFORE WRITE
SUCCESS: VMMDLL_MemRead - BEFORE WRITE
CALL:    VMMDLL_MemWrite
CALL:    VMMDLL_MemRead - AFTER WRITE
SUCCESS: VMMDLL_MemRead - AFTER WRITE
**------**

**//Function Updated**
**VOID PrintHexAscii(_In_ PBYTE pb, _In_ DWORD cb)
{
LPSTR sz = nullptr;
DWORD szMax = 0;
VMMDLL_UtilFillHexAscii(pb, cb, 0, NULL, &szMax);
    if (!(sz == LocalAlloc(0, szMax))) { return; }
    VMMDLL_UtilFillHexAscii(pb, cb, 0, sz, &szMax);
    printf("%s", sz);
    LocalFree(sz);
}**

Any help is appreciated, thanks in advance!

**Comment by ufrisk** [comment]
You can't do `if (!(sz == LocalAlloc(0, szMax))) { return; }`

this would mean IF NOT nullptr == soemallocatedmemory then return. This would pretty much always return

You really have to use the original syntax.

`if (!(sz = LocalAlloc(0, szMax))) { return; }`

or do it in two steps:
```
sz = LocalAlloc(0, szMax);
if(!sz) return;
```

Please let me know if you managed to resolve this.

**Comment by MrCoInSanity** [comment]
Hello, thank you for such a quick reply. I have resolved the issue, Thank you!

**Comment by ufrisk** [comment]
awesome, thanks for letting me know. and best wishes with everything!
