### ISSUE TITLE
Couple of typos in PrintHelp

### ISSUE THREAD

**Issue by aapo** [ufrisk/MemProcFS#132]
--- a/vmm/vmmdll_core.c
    +++ b/vmm/vmmdll_core.c
    @@ -258,13 +258,13 @@ VOID VmmDllCore_PrintHelp(_In_ VMM_HANDLE H)
             "   -cr3 : base address of kernel/process page table (PML4) / CR3 CPU register. \n" \
             "   -max : memory max address, valid range: 0x0 .. 0xffffffffffffffff           \n" \
             "          default: auto-detect (max supported by device / target system).      \n" \
    -        "   -memmap-str : specify a physical memory map in parameter agrument text.     \n" \
    +        "   -memmap-str : specify a physical memory map in parameter argument text.     \n" \
             "   -memmap : specify a physical memory map given in a file or specify 'auto'.  \n" \
             "          example: -memmap c:\\temp\\my_custom_memory_map.txt                  \n" \
             "          example: -memmap auto                                                \n" \
    -        "   -pagefile0..9 : specify specify page file / swap file. By default pagefile  \n" \
    -        "          have index 0 - example: -pagefile0 pagefile.sys while swapfile have  \n" \
    -        "          have index 1 - example: -pagefile1 swapfile.sys                      \n" \
    +        "   -pagefile0..9 : specify page file / swap file. By default pagefile have     \n" \
    +        "          index 0 - example: -pagefile0 pagefile.sys while swapfile have       \n" \
    +        "          index 1 - example: -pagefile1 swapfile.sys                           \n" \
             "   -pythonpath : specify the path to a python 3 installation for Windows.      \n" \
             "          The path given should be to the directory that contain: python.dll   \n" \
             "          Example: -pythonpath \"C:\\Program Files\\Python37\"                 \n" \
    @@ -303,7 +303,7 @@ VOID VmmDllCore_PrintHelp(_In_ VMM_HANDLE H)

**Comment by ufrisk** [comment]
Once again thank you. This will be fixed in next release!

**Comment by ufrisk** [comment]
This should now be fixed in the public release. I'm closing this issue, but if you find anything goofy around this please let me know in this issue.
