### ISSUE TITLE
Linux: why mountpoint must start with "/"?

### ISSUE THREAD

**Issue by aapo** [ufrisk/MemProcFS#133]
Why mountpoint needs to be absolute path starting with "/" ?

    diff --git a/memprocfs/memprocfs_fuse.c b/memprocfs/memprocfs_fuse.c
    index 794ff6d..3306f22 100644
    --- a/memprocfs/memprocfs_fuse.c
    +++ b/memprocfs/memprocfs_fuse.c
    @@ -233,7 +233,7 @@ int main(_In_ int argc, _In_ char* argv[])
         int i;
         LPSTR szMountPoint = NULL, *szArgs = NULL;
         GetMountPoint(argc, argv, &szMountPoint);
    -    if(!szMountPoint || (szMountPoint[0] != '/')) {
    +    if(!szMountPoint) {
             printf("MemProcFS: no mount point specified - specify with: ./memprocfs -mount /dir/to/mount\n");
             return 1;
         }

And then this is possible:

    mkdir mountpoint
    files/memprocfs -device ram.vmem -mount mountpoint

**Comment by ufrisk** [comment]
Many thanks for this suggestion. I don't know why I added it like that. It works great if removing it. I'll include it in next release as well 👍

**Comment by ufrisk** [comment]
This should now be fixed in the public release. I'm closing this issue, but if you find anything goofy around this please let me know in this issue.
