### ISSUE TITLE
Linux: suggestion to clarify compile

### ISSUE THREAD

**Issue by aapo** [ufrisk/MemProcFS#134]
I found it hard to read from wiki how to compile on Linux (order and placement of folders).

Ubuntu 20.04 / 22.04
    
    sudo apt install git build-essential
    sudo apt install libusb-1.0-0-dev libfuse-dev libssl-dev liblz4-dev
    
    mkdir memprocfs
    cd memprocfs
    git clone https://github.com/ufrisk/MemProcFS 
    git clone https://github.com/ufrisk/LeechCore 
    cd LeechCore/leechcore
    make
    cd ../..
    
    cd MemProcFS/vmm
    make
    cd ..
    
    cd memprocfs
    make
    cd ..
    
And binary is then files/memprocfiles

**Comment by ufrisk** [comment]
Thanks for this excellent suggestion. I've added it already to https://github.com/ufrisk/MemProcFS/wiki/_Linux 

I agree that previous instructions left a few things to wish for. I hope it should be a little bit clearer now. I also added a section about copying an additional sqlite database from the binary release (which will improve analysis quality).

Please let me know if you wish for any additional improvements to the build guide?

**Comment by ufrisk** [comment]
I'm closing this issue since it's now resolved.
