### ISSUE TITLE
Linux: feature request: default mount point

### ISSUE THREAD

**Issue by aapo** [ufrisk/MemProcFS#135]
Windows has default mountpoint = M:

Linux should also have some sane default. It is harder to decide what is correct place. 
/tmp/ ?
Or creating new directory on current working directory?

Missing default mountpoint also causes side-effect that help is not printed when running memprocfs without any arguments:

    files/memprocfs
    MemProcFS: no mount point specified - specify with: ./memprocfs -mount /dir/to/mount

I tested simple

    diff --git a/memprocfs/memprocfs_fuse.c b/memprocfs/memprocfs_fuse.c
    index 794ff6d..e4c8c5f 100644
    --- a/memprocfs/memprocfs_fuse.c
    +++ b/memprocfs/memprocfs_fuse.c
    @@ -165,7 +165,8 @@ VOID GetMountPoint(_In_ DWORD argc, _In_ char *argv[], _Out_ LPSTR *pszMountPoin
     {
         char *argv2[3];
         DWORD i = 0;
    -    *pszMountPoint = NULL;
    +    char *default_path="/tmp/memprocfs_mountpoint";
    +    *pszMountPoint = default_path;
         while(i < argc) {
             if(0 == _stricmp(argv[i], "-mount")) {
                 *pszMountPoint = argv[i + 1];
    
And now running memprocfs without arguments shows usage as expected.

Running "./memprocfs ram.vmem" without specifying -mount shows very clearly why it fails:

     - Version:          5.1.0 (Linux)
     - Mount Point:      /tmp/memprocfs_mountpoint           
     - Tag:              2600_9f36ec6d        
     - Operating System: Windows 5.1.2600 (X86PAE)
    fuse: bad mount point `/tmp/memprocfs_mountpoint': No such file or directory

So maybe memprocfs must mkdir that?

**Comment by ufrisk** [comment]
Change is super minimal - this will be included in the next bug fix release (if I have to do one) or in v5.2 which is probably like a month off.

**Comment by ufrisk** [comment]
This should now be fixed in the public release. I'm closing this issue, but if you find anything goofy around this please let me know in this issue.
