### ISSUE TITLE
How to obtain the second process with the same name? In addition to getting the pid list.

### ISSUE THREAD

**Issue by bbhxwl** [ufrisk/MemProcFS#137]
Besides getting the list, and then getting the software name to judge, is there any way to get the next pid? If there are duplicate processes in the following method, only one can be obtained.

        
vmm.PidGetFromName("explorer.exe", out dwExplorerPID);

**Comment by ufrisk** [comment]
The PID list is the way to go for you in this case if there may be multiple processes with the same name. The GetPidFromName is a convenience function that may not be sufficient in your use case.
