### ISSUE TITLE
VMMDLL_MemReadScatter limits

### ISSUE THREAD

**Issue by haode333** [ufrisk/MemProcFS#138]
Hi Ufrisk,

I'm wondering if ```VMMDLL_MemReadScatter``` has a limitation on how many "scatter memory location" it can read in one go?
Asking in the context of FPGA device.

**Comment by ufrisk** [comment]
There shouldn't be any limits really. But if the read becomes very large it will taker longer times to read since the read may be need to chunked into several FPGA reads, but that should be done in the background automatically.

**Comment by haode333** [comment]
Thanks!
