### ISSUE TITLE
VMMDLL_PdbLoad crashes after symbols downloaded.

### ISSUE THREAD

**Issue by 0xGabriella** [ufrisk/MemProcFS#140]
Hello Ulf, once again wishing u good luck <3. The title explains it all. Do you have any example for this function usage? because i tried most examples all crashed the program. Thank you

**Comment by 0xGabriella** [comment]
im sorry, it was the vpn im using blocking connections randomly.

**Comment by ufrisk** [comment]
hm, it shouldn't crash in the memprocfs library if you're not able to download symbols, or did you mean it crashed in your user application or just that it didn't work?
