### ISSUE TITLE
VMMDLL_Initialize Failing with -memmap

### ISSUE THREAD

**Issue by haode333** [ufrisk/MemProcFS#141]
Hi Ufrisk,

I was experimenting with '-memmap' option and find I couldn't initialize at all.
I also tried VMMDLL_InitializeEx and hoping to get some error info but the pLcErrorInfo points to 0x0.

I'm initialization like this
```cpp
LPSTR arg[7] = { (LPSTR)"",(LPSTR)"-max", (LPSTR)"<max phys address from my memmap file>",
		(LPSTR)"-memmap", (LPSTR)"C:\\Users\\9\\Desktop\\memmap.txt",
		(LPSTR)"-device", (LPSTR)"fpga"};

	PLC_CONFIG_ERRORINFO pErrorInfo;
	_hVMM = VMMDLL_InitializeEx(7, arg, &pErrorInfo);
    if ( _hVMM ) {
        printf("SUCCESS: VMMDLL_Initialize\n");
		if (pErrorInfo) LcMemFree(pErrorInfo);
    }
    else {
        printf("FAIL:    VMMDLL_Initialize\n");

		if (pErrorInfo) {
			std::wcout << pErrorInfo->wszUserText<< std::endl;
			LcMemFree(pErrorInfo);
		}
		
        getchar();
        return 1;
    }
```

**Comment by ufrisk** [comment]
The ErrorInfo struct is only very rarely used to provide input back to the user. When connecting to a Hyper-V host and it will return the list of available Hyper-V VMs. This is not applicable for the FPGA use case. Just use the normal Initialize function and not the Ex variant.

to get additional error info you may add options:` -printf` and  `-v` and  `-vv`. Please let me know how it goes.

**Comment by haode333** [comment]
Thanks! I'm able to get the error now but it says failed to locate ntoskrnl.exe

```
LcMemMap_AddRange: 0000000000000000-000000000009ffff -> 0000000000000000
LcMemMap_AddRange: 0000000000100000-000000086dffffff -> 0000000000100000
LeechCore v2.12.1: Open Device: fpga
LcMemMap_AddRange: 0000000000001000-000000000008ffff -> 0000000000001000
LcMemMap_AddRange: 0000000000091000-000000000009dfff -> 0000000000091000
LcMemMap_AddRange: 000000000009f000-000000000009ffff -> 000000000009f000
LcMemMap_AddRange: 0000000000100000-0000000003ffffff -> 0000000000100000
LcMemMap_AddRange: 0000000040400000-000000007dcaafff -> 0000000040400000
LcMemMap_AddRange: 000000007dcac000-000000007dccefff -> 000000007dcac000
LcMemMap_AddRange: 000000007dcd0000-000000008ab7ffff -> 000000007dcd0000
LcMemMap_AddRange: 000000008effe000-000000008effefff -> 000000008effe000
LcMemMap_AddRange: 0000000100000000-000000086dffffff -> 0000000100000000
[CORE]     DTB  located at: 00000000001ae000. MemoryModel: X64
[CORE]     Initialization Failed. Unable to locate ntoskrnl.exe. #3
VmmProc: Unable to auto-identify operating system for PROC file system mount.
         Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.
MOUNT: INFO: PROC file system not mounted.
FAIL:    VMMDLL_Initialize
```

**Comment by ufrisk** [comment]
For some reason it's not able to locate the kernel.

Please verify that the memory map is correct in every detail as given by sysinternals rammap.

If it is, can you please do a memory dump with my PCILeech tool, ie, `pcileech.exe dump -device fpga -max <max phys address from my memmap file> -memmap <memmap.txt>`

Then verify that my MemProcFS tool does is not able to read the dump file created, `memprocfs.exe -device <your_dump_file>`

If the error persists, zip it, upload it somewhere and and share it with me at pcileech@frizk.net (if possible).

**Comment by haode333** [comment]
The dump works fine but when analyzing the dumped file with memprocfs it has the same result (can't locate ntoskrnl.exe)

logs of dumping
```
Memory Dump: Initializing ... Done.
 Current Action: Dumping Memory
 Access Mode:    Normal
 Progress:       34528 / 34528 (100%)
 Speed:          210 MB/s
 Address:        0x0000000100000000
 Pages read:     8111900 / 8839168 (91%)
 Pages failed:   727268 (8%)
Memory Dump: Successful.
```

logs of memprocfs
```
[CORE]     Initialization Failed. Unable to locate ntoskrnl.exe. #3
VmmProc: Unable to auto-identify operating system for PROC file system mount.
         Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.
MOUNT: INFO: PROC file system not mounted.
```

I also sent the dump to your email. Please let me know if there's anything else I can do.

**Comment by ufrisk** [comment]
The memory dump is corrupt. Required memory at address 0x05a09000 is missing.

This memory address is not in your memory map. I suspect you have put in the wrong range at this line:
`LcMemMap_AddRange: 0000000000100000-0000000003ffffff -> 0000000000100000`
I'm guessing it should be:
`LcMemMap_AddRange: 0000000000100000-000000003fffffff -> 0000000000100000` 

Please check this and also if you possibly have more errors in it and retry. Please let me know how it goes.

**Comment by haode333** [comment]
it is the problem. sorry I miscount that :(

**Comment by ufrisk** [comment]
I'm happy to see the issue is now resolved. I wish you the best with your DMA work. Also please let me know if you should run into any more things in the future or wish for new features.

If you find my project useful please consider sponsoring it for as little as $2/month at my [Github Sponsors](https://github.com/sponsors/ufrisk). Thank You 💖

**Comment by haode333** [comment]
Thanks for the great work! I'm sponsoring now ❤️
