### ISSUE TITLE
5.1Read the data bug 

### ISSUE THREAD

**Issue by DIXIN20** [ufrisk/MemProcFS#147]
5.0 Everything is normal. After replacing h, lib and dll of 5.1, it is normal to read a small amount of data. The data can't be read more than once, and then it can be read again a few minutes later. When it can't be read, the device can't be connected after closing the program

**Comment by ufrisk** [comment]
I made an optimization of the reads in leechcore.dll around that time. It may be what is causing your issues. I heard others had minor issues with it (nothing major like this though).

I could add a initialization/start-up option to it to make it perform the old way and maybe it will help. i.e. you'll have to add some extra info to the device fpga startup parameter (`-device fpga://algo=4`) would this be ok?

Note that the above is just a suggestion, it's not implemented yet.

**Comment by DIXIN20** [comment]
Can

**Comment by DIXIN20** [comment]
Sure, No problem

**Comment by ufrisk** [comment]
Can you please try this again to see if this is fixed in the update I published earlier on today.

1) Test it with default settings. Are you still experiencing this issue?
2) Test it with startup option `-device fpga://algo=4` (this will revert it back to how it was done prior to v5.1).

**Comment by DIXIN20** [comment]
> 您能否再试一次，看看我今天早些时候发布的更新是否解决了这个问题。
> 
> 1. 使用默认设置对其进行测试。您是否仍然遇到这个问题？
> 2. 使用启动选项对其进行测试`-device fpga://algo=4`（这会将其恢复到 v5.1 之前的状态）。

The problem still exists, using -device fpga://algo=4 can read normally

**Comment by DIXIN20** [comment]
> 感谢您确认这一点。不过，在恢复此更改之前，我需要更多用户的额外输入。性能提升相当可观。
> 
> 现在我相信您的尖锐问题已经解决，因为您可以使用新选项。
> 
> 我会暂时搁置这个问题，看看是否还有其他人有问题。

It may involve VMMDLL_Scatter. When using a VMMDLL_Scatter_Initialize series command, the data can be read. After adding a VMMDLL_Scatter_Initialize, only the first group can read the data, and the data in the second group is messed up.

**Comment by ufrisk** [comment]
I think I found the bug and hopefully it's now fixed. Can you please test that it is now working in the new version I just released?

**Comment by ufrisk** [comment]
are you using the `leechcore.dll` file from this release?

https://github.com/ufrisk/LeechCore/releases/download/v2.14/LeechCore_files_and_binaries_v2.14.1-win_x64-20221127.zip

**Comment by DIXIN20** [comment]
> 您正在使用`leechcore.dll`此版本中的文件吗？
> 
> https://github.com/ufrisk/LeechCore/releases/download/v2.14/LeechCore_files_and_binaries_v2.14.1-win_x64-20221127.zip

this is the file

**Comment by DIXIN20** [comment]
> 您正在使用`leechcore.dll`此版本中的文件吗？
> 
> https://github.com/ufrisk/LeechCore/releases/download/v2.14/LeechCore_files_and_binaries_v2.14.1-win_x64-20221127.zip

I am this version of the file

**Comment by ufrisk** [comment]
I'm closing this issue since it's a bit old. Also the issue seems to be "resolved" if you specify an algorithm (algo) so PCILeech/MemProcFS should be working for you.

I quite don't understand why some target systems have this behavior whilst others do not. I can't really backtrack on my changes and change the defaults though since they come with large performance gains for the absolute majority of the users.

Sometimes also this may be related to custom firmwares of the device. Anyway I wish you the best with your DMA attacks (even if you may have to resolve to use the algo=4).
