### ISSUE TITLE
How to efficiently read and write memory frequently? Are there any examples? The current reading and writing speed is very slow

### ISSUE THREAD

**Issue by jmp19940829** [ufrisk/MemProcFS#151]
How to read memory at high speed

**Comment by ufrisk** [comment]
what speed are you considering slow? are you using the api or the file system? which device are you using?

**Comment by jmp19940829** [comment]
如果有更快的方法，那么使用VMMDLL_MemRead读取另一台计算机上的程序内存并不理想

**Comment by jmp19940829** [comment]
> what speed are you considering slow? are you using the api or the file system? which device are you using?
如果有更快的方法，那么使用VMMDLL_MemRead读取另一台计算机上的程序内存并不理想

**Comment by ufrisk** [comment]
VMMDLL_Read is not ideal if you have a lot of known memory addresses to read. There is a memory read API that will allow you to read multiple memories at the same time. This will greatly save on the total time. Please have a look in the Example for a short example how to use the Memory Scatter API. https://github.com/ufrisk/MemProcFS/blob/454fa98f4080f97106d833362189d20abdebe0ed/vmm_example/vmmdll_example.c#L1266

For some workloads there is a 100x increase in speed.

Please let me know how it goes.

**Comment by jmp19940829** [comment]
This method is not very useful when there are multilevel Pointers

> 如果您有大量已知内存地址要读取，则 VMMDLL_Read 并不理想。有一个内存读取 API，可让您同时读取多个内存。这将大大节省总时间。请查看示例中的简短示例，了解如何使用 Memory Scatter API。
> 
> https://github.com/ufrisk/MemProcFS/blob/454fa98f4080f97106d833362189d20abdebe0ed/vmm_example/vmmdll_example.c#L1264
> 
> 对于某些工作负载，速度提高了 100 倍。
> 
> 请告诉我进展如何。

**Comment by jmp19940829** [comment]
This method is not very useful when there are multilevel Pointers

**Comment by jmp19940829** [comment]
I need to read a process memory address! But this address has multiple levels of pointers that need to be read out! So is there any way to increase the reading speed! This problem has troubled me for a long time and I hope it can be solved. The method you provide is only useful when I know the memory address in advance.

**Comment by jmp19940829** [comment]
> 当有多级指针时，这种方法不是很有用
> 
> > 如果您有大量已知道内存地址要读取，则VMMDLL_Read并不想。有一个内存读取API，可让您同时读取多个内存。这将大节省时间的时候，请看例子。了解了如何使用 Memory Scatter API。
> > https://github.com/ufrisk/MemProcFS/blob/454fa98f4080f97106d833362189d20abdebe0ed/vmm_example/vmmdll_example.c#L1264
> > 
> > 对于某些工作负载，速度提高了100倍。
> > 请告诉我进展如何。

I need to read a process memory address! But this address has multiple levels of pointers that need to be read out! So is there any way to increase the reading speed! This problem has troubled me for a long time and I hope it can be solved. The method you provide is only useful when I know the memory address in advance.

**Comment by ufrisk** [comment]
one pointer chain is not possible to do fast.

for multiple pointer chains you can use the scatter with one call for each level in the chain (reading the multiple chains at the same time). not ideal but faster.

for re-reads of pointer chains you can guess all the previous (known) memory locations and do a scatter read and only fallback to doing more reads if any chain address have changed.

**Comment by imerzan** [comment]
Yup, I can attest that chaining scatter reads is the way to go for chains of pointers. Pretty easy to implement.

VMMDLL_Read isn't really that slow either. Maybe you have a bad fpga card or usb cable?

**Comment by jmp19940829** [comment]
> 一个指针链是不可能做到快速的。
> 
> 对于多个指针链，您可以对链中的每个级别使用一次调用分散（同时读取多个链）。不理想但更快。
> 
> 对于指针链的重新读取，您可以猜测所有以前的（已知的）内存位置并进行分散读取，并且只有在任何链地址发生变化时才回退以进行更多读取。

[thank you](javascript:;)

**Comment by ufrisk** [comment]
I'm closing this issue. I believe the issue was resolved (or at least it's known why it's slow). Also some good examples about what to do has been given. Thanks :)
