### ISSUE TITLE
Issue when loading mmap

### ISSUE THREAD

**Issue by vmmenjoyer** [ufrisk/MemProcFS#154]
Hello,
I seem to have an issue when trying to load a mmap, for some reason the DMA fails to read it and connect.
This is the mmap:
0000000000001000 - 0000000000057FFF
0000000000059000 - 000000000009EFFF
0000000000100000 - 000000008452DFFF
0000000084530000 - 000000008D177FFF
000000008FAA2000 - 000000008FAFFFFF
0000000100000000 - 0000000A1B026FFF
0000000A1B028000 - 0000000A1B226FFF
0000000A1B228000 - 000000106EFFFFFF

Created by this:
![image](https://user-images.githubusercontent.com/120314428/206903891-85cd999a-2461-4348-a210-9cd25a28aa8a.png)

If I run my program without the mmap it works fine, only fails to connect with mmap.
My friend can run my program with mmap with no issues.
I have 4 sticks of ram and 64 GB of memory.
Really not sure what the issue can be, I double-checked the file encoding and everything seems fine.

**Comment by vmmenjoyer** [comment]
1. gave me this at the end:
LcMemMap_AddRange: 0000000000000000-000000000009ffff -> 0000000000000000
LcMemMap_AddRange: 0000000000100000-000000ffffffefff -> 0000000000100000
LeechCore v2.14.1: Open Device: fpga
PCILEECH: Invalid memory map: '.txt'.
PCILEECH: Failed to connect to the device.

2. Tried and still the same

3. Got this(also the same):
0000000000001000 - 0000000000057fff
0000000000059000 - 000000000009efff
0000000000100000 - 000000008452dfff
0000000084530000 - 000000008d177fff
000000008faa2000 - 000000008fafffff
0000000100000000 - 0000000a1b026fff
0000000a1b028000 - 0000000a1b226fff
0000000a1b228000 - 000000106effffff

Not sure why it's not working

**Comment by ufrisk** [comment]
It seems like it's unable to read your memory map file for some reason. It's almost as you specified it as an incorrect file name. Also make sure it's saved in ASCII.
