### ISSUE TITLE
Cannot set a fast refresh rate

### ISSUE THREAD

**Issue by gaygaygay** [ufrisk/MemProcFS#155]
Hi~your work is great and i met this problem while learning. I am using a fpga card to leech memory from my other computer and coding with python. After setting up a Vmm object and set OPT_CONFIG_TICK_PERIOD OPT_CONFIG_READCACHE_TICKS       
 OPT_CONFIG_TLBCACHE_TICKS         OPT_CONFIG_PROCCACHE_TICKS_PARTIAL  OPT_CONFIG_PROCCACHE_TICKS_TOTAL all to 1, my readings still refresh about once per second. What should I do to make it refresh as fast as possible? Thank you.

**Comment by gaygaygay** [comment]
oh, and when I tried to write memory in a 50ms interval, it worked properly for several attempts but then stopped for half a second, and looped like this.

**Comment by ufrisk** [comment]
Hi, I'm unsure if it works with super aggressive settings like that.

If you're trying to read uncached memory with Python it's better to supply the option: memprocfs.FLAG_NOCACHE to the memory read functions.

**Comment by gaygaygay** [comment]
thx! I will have a try. btw how to use OPT_REFRESH_ALL to do a forced refreshment?

**Comment by ufrisk** [comment]
Awesome, `vmm.set_config(memprocfs.OPT_REFRESH_ALL, 1)` should do it, but for reads use the nocache flag.

**Comment by gaygaygay** [comment]
everything works perfect now, thx!
