### ISSUE TITLE
error on getpool (windows 10 22H2)

### ISSUE THREAD

**Issue by pineda89** [ufrisk/MemProcFS#156]
hello
I am quite stuck, because I am testing on a windows 10 22H2 and I get everything to work or so it seems, except for VMMDLL_Map_GetPool . Of course I have tried with both possible flags.

I have tried with both old versions (from a few months ago) and the last 3 releases.

The only thing that seems strange looking at the log is
[INFODB]     INIT: FAIL: va=0xfffff80665800000

same code, same card, with another operating system version (21H2) is working fine.

I'm sorry I can't provide more information

Any ideas?

**Comment by gaygaygay** [comment]
met the same problem today.

**Comment by gaygaygay** [comment]
> met the same problem today.

I guess this has something to do with the windows update today.

**Comment by gaygaygay** [comment]
KB5021255 and KB5020880

**Comment by ufrisk** [comment]
can you please download the most recent version of memprocfs from the releases section and try with it?

most importantly use the new updated info.db file.

**Comment by ufrisk** [comment]
Some symbols was missing from the info.db. download the new release (named MemProcFS_files_and_binaries_v5.2.11-win_x64-20221218) and try again. Please let me know if it works better.

**Comment by gaygaygay** [comment]
> Some symbols was missing from the info.db. download the new release (named MemProcFS_files_and_binaries_v5.2.11-win_x64-20221218) and try again. Please let me know if it works better.

how can I use pip to upgrade to 5.2.11? I am quite newbie and dont know how to add it to python environment manually.

**Comment by pineda89** [comment]
hey @ufrisk all seems working again as usual with latest version
thanks

the problem was the win symbols?

**Comment by ufrisk** [comment]
Awesome and thanks for confirming it works.

I just now updated the Python PIP package to memprocfs-5.2.12 which should contain the new cached symbols. (5.2.11 does not contain them).

If the PC running MemProcFS is running Windows and is connected to the Internet it should be able to download missing symbols automatically as well. But the updated cached symbols should work now as well.
