### ISSUE TITLE
GetProcess and GetThreads

### ISSUE THREAD

**Issue by kkh961216** [ufrisk/MemProcFS#157]
Hey, thank you for your work on this project!

I've been having troubles with two functions in particular, and was wondering if you would not mind letting me know if I'm doing something wrong. The two functions are VMMDLL_ProcessGetInformation and VMMDLL_Map_GetThread. Other functions work wonderfully. My usage of them on the newest binaries are as follows:

```
SIZE_T ProcInfoSize;
	if (!VMMDLL_ProcessGetInformation(DMA_HANDLE, PID, 0, &ProcInfoSize)) {
		printf("ProcessGetInformation failed\n");
	}
	printf("Required size: %llx\n", ProcInfoSize);
	PVOID buffer = VirtualAlloc(0, ProcInfoSize, MEM_COMMIT, PAGE_EXECUTE_READWRITE);
	if (!VMMDLL_ProcessGetInformation(DMA_HANDLE, PID, (PVMMDLL_PROCESS_INFORMATION)buffer, &ProcInfoSize)) {
		printf("ProcessGetInformation failed\n");
	}
	printf("PID 2 %i\n", ((PVMMDLL_PROCESS_INFORMATION)buffer)->dwPID);

PVMMDLL_MAP_THREAD AddressOfMap;
	if (!VMMDLL_Map_GetThread(DMA_HANDLE, PID, &AddressOfMap)) {
		printf("VMMDLL_Map_GetThread Failed \n");
	}
```

However, the output I'm getting is:

```
Required size: 1c0
ProcessGetInformation failed
PID 2 0
VMMDLL_Map_GetThread Failed
ThreadMap Location: 0
```

Thank you in advance!

**Comment by ufrisk** [comment]
Issue 1: Please see the [example](https://github.com/ufrisk/MemProcFS/blob/a07e137a2aeb9bd49b8e7da929e4c5a2e2ee7244/vmm_example/vmmdll_example.c#L308) about how to use the VMMDLL_ProcessGetInformation function. Also I recently added a VMMDLL_ProcessGetInformationAll function (also documented in the example).

Issue 2: MemProcFS thread parsing is quite reliant on symbols. Ensure you either have the most recent version of the cached symbols in info.db (download from the releases section and unzip it). Or if you have Internet access (and are running on Windows) it should be possible to download from the Microsoft symbol server as well.

Please let me know how it goes.

**Comment by kkh961216** [comment]
Hey,
Thank you for your reply. 
Issue 1 resolved very nicely, thank you very much.

Regarding issue 2 - I do have info.db in my compiled folder (downloaded from the latest binaries today), and there is also a symbol folder which gets populated on first run of the program with a folder called ntkrnlmp.pdb, which contains another folder, which leads to the actual ntkrnlmp.pdb. However, I am still returning a failure for the GetThread. Would you have any other potential troubleshooting steps?

**Comment by ufrisk** [comment]
As for the thread issue, there may be a race condition at startup, where the symbols aren't yet loaded fully when the "thread map" is generated. I could look into this, meanwhile you could add the startup-option [`-waitinitialize`](https://github.com/ufrisk/MemProcFS/wiki/_CommandLine#-waitinitialize) to see if it will resolve your issue.

Please let me know how it goes.

**Comment by ufrisk** [comment]
Closing issue due to old age. It seem to be resolved. Let me know if it's not.
