### ISSUE TITLE
Region Size Incorrect ? 

### ISSUE THREAD

**Issue by bin5k** [ufrisk/MemProcFS#16]
![mstsc_2019-12-16_13-12-05](https://user-images.githubusercontent.com/44826092/70910560-de05bf80-2007-11ea-863b-4ba059718a79.png)

I have been testing the new VAD functions and i noticed that the region size is not same as the one you get from VirtualQueryEx or Process Hacker.

To calculate the region size is just use:
`pVadMapEntry->vaEnd + 1 - pVadMapEntry->vaStart`

**Comment by ufrisk** [comment]
hmm, the length checks out for me, or am I missing something?
0x8000 == 32kB
0x80000 == 512kB

also (not related in any way) I noticed that stacks aren't showing up in your sample, if you put the microsoft binaries dbghelp.dll and symsrv.dll alongside vmm.dll and also initialize it with additional option -waitinitialize MemProcFS will download required symbol files from Microsoft server and parse threads as well.

**Comment by bin5k** [comment]
i am enumerating the memory regions like this:

`#include <iostream>
#include <Windows.h>
#include "TlHelp32.h"
#include <string.h>
#include <tchar.h>

DWORD GetProcessPidByName(const TCHAR* processname)
{
	DWORD result = 0;
	PROCESSENTRY32 pe32;
	pe32.dwSize = sizeof(PROCESSENTRY32);

	HANDLE hProcessSnap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
	if (INVALID_HANDLE_VALUE == hProcessSnap) return result;

	if (!Process32First(hProcessSnap, &pe32)) {
		CloseHandle(hProcessSnap);
		return result;
	}

	do
	{
		if (0 == _tcsicmp(processname, pe32.szExeFile))
		{
			result = pe32.th32ProcessID;
		}
	} while (Process32Next(hProcessSnap, &pe32));

	CloseHandle(hProcessSnap);
	return result;
}

void ListMemoryRegions(DWORD pid)
{
	HANDLE hProc = OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, FALSE, pid);
	if (NULL == hProc) return;

	SYSTEM_INFO sysInfo = { 0 };
	GetSystemInfo(&sysInfo);

	UINT64 startAddress = 0;
	UINT64 endAddress = (UINT64)sysInfo.lpMaximumApplicationAddress;

	int i = 0;
	while (startAddress < endAddress) {
		MEMORY_BASIC_INFORMATION mbi = { 0 };

		if (VirtualQueryEx(hProc, (LPCVOID)startAddress, &mbi, sizeof(mbi)) == 0)
			break;

		printf("BaseAddress: %llX\nAllocationBase: %llX\nRegion Size: %llX\n", mbi.BaseAddress, mbi.AllocationBase, mbi.RegionSize);
		printf("%016llx-%016llx\n", mbi.BaseAddress, (INT64)mbi.BaseAddress + mbi.RegionSize );
		printf("-----------------------------------\n");

		startAddress = (UINT64)mbi.BaseAddress + mbi.RegionSize;
		if (i > 5)
			break;
		i++;
	}

	CloseHandle(hProc);
}

int main()
{
	DWORD pid = GetProcessPidByName(L"explorer.exe");
	if (pid != 0) {
		printf("Listing Memory Regions of PID: %i\n\n", pid);
		ListMemoryRegions(pid);
	}

	return 1;
}`

**Comment by ufrisk** [comment]
yes, but region sizes checks out in the image you posted.

process hacker shows 32kB for address 0x470000 and MemProcFS 0x8000. 0x8000 = 32kB

**Comment by bin5k** [comment]
you're right, but when i use VirtualQueryEx i see more pages and different region sizes.

![vmm_example_2019-12-16_14-59-04](https://user-images.githubusercontent.com/44826092/70917616-8ff7b880-2015-11ea-880f-329586ec486f.png)

**Comment by bin5k** [comment]
i tought VMMDLL_ProcessMap_GetVad was supposed to give me the same information as VirtualQueryEx, or am I missing something ?

> 
> 
> you're right, but when i use VirtualQueryEx i see more pages and different region sizes.
> 
> ![vmm_example_2019-12-16_14-59-04](https://user-images.githubusercontent.com/44826092/70917616-8ff7b880-2015-11ea-880f-329586ec486f.png)

**Comment by ufrisk** [comment]
I haven't tested it against VirtualQueryEx, but MemProcFS should be returning the size of the whole VAD, while I suspect VirtualQueryEx may return only committed (i.e. not reserved) pages? could that be the issue?

In the VMMDLL_MAP_VADENTRY struct there is a field CommitCharge and MemCommit. Does the CommitCharge corresponds to VirtualQueryEx?

Also, I currently have no notion about which parts of the VAD is commited, it's a thing that would be nice to add for the future I guess?

**Comment by ufrisk** [comment]
Hmm, when looking at your example you have two regions in the same VAD. I'll have to add support for querying sub-regions within a VAD for this to work as you wish. It would be a good thing to do and I'll put it on the todo list.

**Comment by bin5k** [comment]
> 
> 
> Hmm, when looking at your example you have two regions in the same VAD. I'll have to add support for querying sub-regions within a VAD for this to work as you wish. It would be a good thing to do and I'll put it on the todo list. So it's not a bug, it's more of a feature request.

I see, it would be great to have something that works like VirtualQueryEx or gives the same information.

**Comment by ufrisk** [comment]
Anyway, thanks for reporting this. I'll try to add support for sub-regions in the future. Hopefully I'll get to it sooner than later. I'll put it down as enhancement.

I'll probably add a flag in the VMMDLL_MAP_VADENTRY struct that there exists sub-regions and you'll have to query via separate API call.

**Comment by ufrisk** [comment]
I have decided not to add this since there is already functionality that will do the job. sort of.

If you have a VAD region which is marked as "private" and you wish to know which pages are readable in there please retrieve the PTE map (which is gathered by walking the page tables) and check the memory addresses for the VAD region. 

This will mostly give the correct answer already; the result may be a bit shaky if some of the memory pages are paged out right now; this will be fixed in the next version that will be released this or next month (i.e. PTE map will contain paged-out memory regions as well).
