### ISSUE TITLE
Execute the command memprocfs.exe -device c:\temp\win10x64-dump.raw -forensic 2 during initialization. An error occurred

### ISSUE THREAD

**Issue by kay6666** [ufrisk/MemProcFS#161]
I have encountered a problem, the consequence of this problem is that the forensic mode cannot be used, and the information cannot be obtained
Unable to fuzz EPROCESS offsets - trying debug symbols

[PROCESS]  OK: FALSE
[PROCESS]      PID:  2e0 PPID: 3d0 STAT: 004 DTB:  028 DTBU: 000 NAME: 438 PEB: 3e8
[PROCESS]      FLnk: 2e8 BLnk: 2f0 oMax: 000 SeAu: 450 VadR: 000 ObjT: 408 WoW: 418
[PROCESS]  Unable to fuzz EPROCESS offsets - trying debug symbols
[INFODB]   INIT: FAIL: va=0xfffff8019fa1f000
[SYMBOL]   Initialization of debug symbol .pdb functionality completed
[SYMBOL]   [ srv*C:\Users\Administrator\Desktop\MemProcFS2\Symbols*https://msdl.microsoft.com/download/symbols ]
[PROCESS]  OK: TRUE
[PROCESS]      PID:  2e0 PPID: 3d0 STAT: 004 DTB:  028 DTBU: 270 NAME: 438 PEB: 3e8
[PROCESS]      FLnk: 2e8 BLnk: 004 oMax: 708 SeAu: 450 VadR: 5d8 ObjT: 408 WoW: 418
[PROCESS]  SYSTEM DTB: 00000000001aa000 EPROCESS: ffffe0013dc1c8c0
![image](https://user-images.githubusercontent.com/50900788/211765591-6cc6dc8a-9b90-49dc-9c4e-74f29f9ba686.png)

**Comment by ufrisk** [comment]
The error message mean that MemProcFS was unable to determine required offsets by the default method - but that it was successfully able to with the fallback method (debug symbols). Everything should work just fine.

Forensic mode takes a short while to process. You can check the progress in the progress_percent.txt file. I'm very hopeful you'll see results if you wait a short while and that this is a false alarm.

Can you please confirm forensic mode is working?

**Comment by kay6666** [comment]
Thx, I am indeed too anxious, thinking that there will be problems with the forensics mode of the win10 system. At first I used server2008, and the data in the forensics mode was displayed very quickly. Thank you very much for solving my problem

**Comment by ufrisk** [comment]
Thanks for the update. I'm glad the issue was resolved.

Best wishes with your memory analysis and please let me know if you should run into any issues again.
