### ISSUE TITLE
difference between VMMDLL_MemReadScatter and VMMDLL_Scatter_Read

### ISSUE THREAD

**Issue by haode333** [ufrisk/MemProcFS#162]
Hi Ufrisk,

This is not an issue but a question. I've been using VMMDLL_MemReadScatter but recently discovered these newly added VMMDLL_Scatter_* APIs. 
They look a lot more cleaner but I'm wondering if there's any difference internally?
Would one perform better than another?

Asking in the context of small reads(0x8) and big reads (maybe whole page)

**Comment by haode333** [comment]
Also wondering if VMMDLL_Scatter_Read has limitation of 1 page (0x1000)?

**Comment by ufrisk** [comment]
`VMMDLL_MemReadScatter` is an older more complicated API that I was always getting a lot of questions about how to use.

The `VMMDLL_Scatter_*` API should be much easier to use.

No limitation on number of pages, and the new API is pretty much a wrapper API around the older more complicated `VMMDLL_MemReadScatter` API which is still used in the background.

**Comment by haode333** [comment]
Thanks for the info! The new API is indeed much easier to work with!
