### ISSUE TITLE
Version 5.3 does not work on X86

### ISSUE THREAD

**Issue by zijingsh** [ufrisk/MemProcFS#164]
Hello, the latest version of 5.3 does not work on X86 but 5.2 does work, I don't know what the problem is, please help me, everything is using the default fpga mode

**Comment by ufrisk** [comment]
Hi, thanks for reporting this. I usually don't test against the 32-bit version and there was a wrongly sized field in a struct in this version affecting only the 32-bit version.

I've made a minor change in the v5.3.2 version to the source. If you rebuild against the latest sources and retry it should work.

Please let me know if it works better for you after the fix.

**Comment by zijingsh** [comment]
yes it working now, thx!

**Comment by ufrisk** [comment]
Thanks for confirming it works. Best wishes with your DMA work.
