### ISSUE TITLE
Process with kernel memory in Rust

### ISSUE THREAD

**Issue by spikerushed** [ufrisk/MemProcFS#168]
I am having a hard time getting to the gafAsyncKeystate symbol using the Rust crate.

This wont work:

```rust
let winlogon = mem_ctx.vmm.process_from_name("winlogon.exe").unwrap();
winlogon.get_proc_address("win32kbase.sys", "gafAsyncKeyState");
```

In the C library, since functions take a pid argument, we can mask with `0x80000000` to get kernel memory. Is there any equivalent in the rust crate?

Thanks!

**Comment by ufrisk** [comment]
oh, I never thought about that use case. By default csrss.exe is already open for "kernel memory" since there exists one per session. You could use that one or use winlogon.exe with the code below:

```Rust
if let Ok(mut winlogon) = mem_ctx.vmm.process_from_name("winlogon.exe") {
    winlogon.pid = winlogon.pid | 0x80000000;
    if let Ok(va) = winlogon.get_proc_address("win32kbase.sys", "gafAsyncKeyState") {
        println!("win32kbase.sys!gafAsyncKeyState -> {:x}", va);
    }
}
```

It's a bit "ugly" but it should work. It's basically the same thing that is done in the C/C++ library. The masked PID should be inherited to any other handles that would require it (such as the scatter read).

I don't have a nice rust-ish solution for it right now without changing quite a lot of internals in the crate. But please let me know if this works well for you and I'll include this use-case in the example documentation in the next crate release.

**Comment by ufrisk** [comment]
And please let me know how it goes.

Also if you run into anything else around the crate. It's still fairly new so I'm very open to feedback around it if there is anything you feel should be changed or added (in addition to the above issue).

**Comment by spikerushed** [comment]
Ah, that is actually perfect for my use case. Thank you!

I get the address but the only issue is that it doesn't seem to read correctly:

This works (in my fork, for testing):
```rust
let key_state = vmm.mem_read_pid(winlogon.pid, va, 256 * 2 / 8)?;
```
This does not work:
```rust
let key_state = winlogon.mem_read(gaf_async_keystate, 256 * 2 / 8)?;
```

**Comment by ufrisk** [comment]
Did you mask the pid on your winlogon process? The example below works for me. Please let me know if it's working better now.

```Rust
let mut winlogon = vmm.process_from_name("winlogon.exe")?;
winlogon.pid = winlogon.pid | 0x80000000;
let va = winlogon.get_proc_address("win32kbase.sys", "gafAsyncKeyState")?;
let mem = winlogon.mem_read(va, 64)?;
println!("win32kbase.sys!gafAsyncKeyState -> {:x} : {:x?}", va, mem.hex_dump());
```
->
```
vmmprocess.get_proc_address():
kernel32.dll!GetProcAddress -> 7ff982678f10
win32kbase.sys!gafAsyncKeyState -> ffffdf470bd2da20 : Length: 64 (0x40) bytes
0000:   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00   ................
0010:   00 80 00 02  00 00 00 00  00 00 00 00  00 00 00 00   ................
0020:   00 00 00 00  02 00 00 00  0a 00 00 00  00 00 00 08   ................
0030:   00 00 00 00  00 00 00 00  00 00 00 00  82 20 80 00   ............. ..
```

**Comment by spikerushed** [comment]
I did try reading exactly like that, and I do actually get data back identical to yours, the problem is that it doesn't actually change when pressing a button, I am constantly getting the same bytes back.

**Comment by ufrisk** [comment]
MemProcFS caches data by default to speed up accesses significantly.

In this case you obviously don't want that so specify the FLAG_NOCACHE as in either of the two examples below and it should work. Please let me know if it works better.

```Rust
# example #1:
let data = winlogon.mem_read_ex(va, 64, FLAG_NOCACHE | FLAG_ZEROPAD_ON_FAIL)?;
# example #2:
let data : [u8; 64] = winlogon.mem_read_as(va, FLAG_NOCACHE | FLAG_ZEROPAD_ON_FAIL)?;
```

**Comment by spikerushed** [comment]
Yes of course, I was obviously tired when I wrote my last reply, in my fork I had the `FLAG_NOCACHE` set...
Thank you so much for your help Ulf!

**Comment by ufrisk** [comment]
Awesome, thanks for confirming, and the best wishes with your rust project :)
