### ISSUE TITLE
VMMDLL_Map_GetPool Fail

### ISSUE THREAD

**Issue by pipiw33** [ufrisk/MemProcFS#169]
Hi ufrisk,
VMMDLL_Map_GetPool works fine in x64 but doesn't work in x86 always return fail
include x86 symsrv.dll dbghelp.dll info.db vmm.dll

**Comment by ufrisk** [comment]
I did a quick test on a 32-bit x86 build and it seems to be working for me.

I analyzed a 64-bit memory image though.

Are you using the most up-to-date info.db file (it's found in any release at https://github.com/ufrisk/MemProcFS/releases/latest/

the info.db file is an sql database and is the same for both 32-bit and 64-bit.

Is this working better for you?

**Comment by pipiw33** [comment]
Thanks for the quick response
tried updating to the latest version (5.2 -> 5.4) and everything worked fine

**Comment by ufrisk** [comment]
Awesome, and thanks for letting me know. Best wishes with your DMA attacking 👍
