### ISSUE TITLE
Expose FullDllName

### ISSUE THREAD

**Issue by bin5k** [ufrisk/MemProcFS#17]
In the previous version of MemProcFS i made a few changes to be able to get the full dll name, like this:

> typedef struct tdPCILEECH_VMM_MODULEMAP_ENTRY {
>     ULONG64 BaseAddress;
>     ULONG64 EntryPoint;
>     DWORD SizeOfImage;
>     BOOL  fWoW64;
>     CHAR  szName[32];
> 	CHAR szExePath[MAX_PATH];
> } PCILEECH_VMM_MODULEMAP_ENTRY, *PPCILEECH_VMM_MODULEMAP_ENTRY;

>         if(!VmmReadString_Unicode2Ansi(ctxVmm, pProcess, (QWORD)pLdrModule->BaseDllName.Buffer, pModule->szName, min(31, pLdrModule->BaseDllName.Length))) { break; }
> 		if (pLdrModule->FullDllName.Length != 0) {
> 			VmmReadString_Unicode2Ansi(ctxVmm, pProcess, (QWORD)pLdrModule->FullDllName.Buffer, pModule->szExePath, min(MAX_PATH, pLdrModule->FullDllName.Length));
> 		}

But in the latest version much has changed, and it would be nice to have official support, something like this:

> 
> typedef struct tdVMMDLL_MAP_MODULEENTRY {
>     QWORD vaBase;
>     QWORD vaEntry;
>     DWORD cbImageSize;
>     BOOL  fWoW64;
>     LPWSTR wszText;
>     DWORD cwszText;                 // wchar count not including terminating null
> 	LPWSTR wszFullDllName;
> 	DWORD cwszFullDllName;
>     DWORD _Reserved1[7];
> } VMMDLL_MAP_MODULEENTRY, *PVMMDLL_MAP_MODULEENTRY;

**Comment by ufrisk** [comment]
The name of the .DLL (i.e. the complete non truncated DLL name) is already exposed in the `LPWSTR wszText;`.

Just want to double check that I understand this request - If I understand correctly you wish to have the DLL name including its path in a separate entry?

**Comment by bin5k** [comment]
> 
> 
> The name of the .DLL (i.e. the complete non truncated DLL name) is already exposed in the `LPWSTR wszText;`.
> 
> Just want to double check that I understand this request - If I understand correctly you wish to have the DLL name including its path in a separate entry?

I know that wszText has the dll name but i also need the Dll name with its path.

Yea it could be done in a separate entry like this: https://docs.microsoft.com/en-us/windows/win32/api/tlhelp32/ns-tlhelp32-moduleentry32
or wszText could be changed to have the full dll name, including its path.

**Comment by ufrisk** [comment]
Thanks for clarifying. I'll try to add this in the next version.

**Comment by ufrisk** [comment]
would you prefer that this value is to be fetched from the in-process memory structures that you suggest, or that I fetch it from the VAD in the kernel?

I would think the VAD would be better since it would be harder for a malware to modify.

As it stands right now you can already retrieve this value from the VAD even though it's rather cumbersome.

**Comment by bin5k** [comment]
> 
> 
> would you prefer that this value is to be fetched from the in-process memory structures that you suggest, or that I fetch it from the VAD in the kernel?
> 
> I would think the VAD would be better since it would be harder for a malware to modify.
> 
> As it stands right now you can already retrieve this value from the VAD even though it's rather cumbersome.

i think you should fetch it from the kernel, since malware can unlink it's modules from PEB.
the kernel is the more reliable way.

**Comment by ufrisk** [comment]
I have added this in my internal development copy now; which I hope to release this or next month. Apologies for this taking such a long time, but soon it will be there.

**Comment by ufrisk** [comment]
Thank you for the enhancement suggestion. This is now added in the new release. Please see the below location in the header file for details:

https://github.com/ufrisk/MemProcFS/blob/c81302e1ff60d4c4fd4a722181965175840765df/vmm/vmmdll.h#L544

Thank You 👍
