### ISSUE TITLE
Why is memory reading not supported for Linux operating systems now?

### ISSUE THREAD

**Issue by sansure** [ufrisk/MemProcFS#170]
Previous versions did support memory reading for Linux operating systems. Can the current version still support Linux operating systems?

**Comment by ufrisk** [comment]
MemProcFS should work just fine running on Linux analyzing memory from a Windows target.

MemProcFS have never been able to analyze Linux memory dumps in a good way.

Please let me know if this answers your question, or if you have issues running MemProcFS on Linux.
