### ISSUE TITLE
In the VMMDLL_MAP_VADENTRY object, the fTeb, fStack, fHeap fields are incorrectly populated from the VMMDLL_Map_GetVadW call.

### ISSUE THREAD

**Issue by bruhov** [ufrisk/MemProcFS#171]
Hi,

In the VMMDLL_MAP_VADENTRY object, the fTeb, fStack, fHeap fields are incorrectly populated from the VMMDLL_Map_GetVadW (C/C++ API) call.

At the same time, everything is correct in vad.txt from the virtual file system.

I use MemProcFS 5.4.5, FPGA 4.11, Windows 10 22h2 (host), Windows 11 22H2 (target).

![screenshot](https://i.imgur.com/GLjS97u.png)

**Comment by ufrisk** [comment]
It seems like these values were changed in Windows 11 22H2 and I have to revisit them and make sure things work. It will take a bit of time to do this (and test it and also verify the other Windows versions as well if there are similar issues somewhere) so I'll make sure to include it in the next release (5.5). Unfortunately no quick fix.

The type "Stack" in the MemProcFS listing isn't derived from those flags though. It's derived from the process threads so it should still hold true despite this bug. I think the wszText should start with STACK so meanwhile you should be able to rely on that value.

Thanks for the bug report. I'll let you know once this is fixed.

**Comment by ufrisk** [comment]
Actually it seems like fTeb, fStack, fHeap will be properly set if you set fIdentifyModules to TRUE.

But I have other bugs in there as well on the most recent Windows version (commit is wrong) and I should rename the fIdentifyModules  as well to make things clearer so I'll leave this issue as open for now.

**Comment by ufrisk** [comment]
I looked into it a bit further and it seems like everything should be ok. I'll change the name of the fIdentifyModules in next version though.
