### ISSUE TITLE
Vmmsharp constants

### ISSUE THREAD

**Issue by imerzan** [ufrisk/MemProcFS#172]
Looks like a lot of the constants defined in `vmmsharp.cs` are marked as static, which means they are checked at runtime, and also mutable -- which i would consider undesired

lines like
```csharp
public static ulong OPT_CORE_PRINTF_ENABLE =            0x4000000100000000;
```
should be changed to
```csharp
public const ulong OPT_CORE_PRINTF_ENABLE =            0x4000000100000000;
```

So they are truly constant

Not a huge deal, but something I've been changing on my own. Just a suggestion -- feel free to close this out 😄

**Comment by ufrisk** [comment]
Thanks, it's an easy enough thing to do, I'll take care of it in the next release :)

**Comment by ufrisk** [comment]
I've updated this in the new release - v5.5.

Please let me know if this is better, if so feel free to close this issue.

**Comment by imerzan** [comment]
> I've updated this in the new release - v5.5.
> 
> Please let me know if this is better, if so feel free to close this issue.

Looks really good! Just saw one thing missed:
https://github.com/ufrisk/MemProcFS/blob/0d535cc28dc132ecda475d328216319c6fae4029/vmmsharp/vmmsharp.cs#L2385-L2386

After changing these to const, I had to change this line:
https://github.com/ufrisk/MemProcFS/blob/0d535cc28dc132ecda475d328216319c6fae4029/vmmsharp/vmmsharp.cs#L718

to

```csharp
Marshal.WriteInt64(new IntPtr(pb + 0), unchecked((long)vmmi.VMMDLL_PROCESS_INFORMATION_MAGIC));
```

**Comment by ufrisk** [comment]
Awesome, I fixed this last minor issue as well now. Thanks for the suggestion :)
