### ISSUE TITLE
mount live win10 raw memory dump file

### ISSUE THREAD

**Issue by adeliktas** [ufrisk/MemProcFS#176]
Hello ufrisk and Community.

I currently have to remount MemProcFS on every change of the live memory on the system (guest win10 vm).
    >sudo ./memprocfs -vv -disable-python -mount /mnt/memprocfs/ -device /cloudflow/connector/win10/mem
    >sudo umount -l /mnt/memprocfs
memflow/cloudflow is being used and provides a live mem dump file of my qemu win10 vm with kvm connector
    at /cloudflow/connector/win10/mem with /dev/fuse on /cloudflow type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)

I can live fine with analyzing a snapshot of the memory and remount the mem, but doing so live instead with the already existing live file would be a great feature.
My question is how feasible is it to implement the support of live mem files?

Greetz
adeliktas

**Comment by ufrisk** [comment]
I haven't looked at memflow, but that memory device you're using seems to be nice.

MemProcFS (or rather the file read implementation in LeechCore) treats files as read-only and static non-changing. This allows MemProcFS to employ various optimizations and disable automatic refreshes.

I've updated the LeechCore file implementation (packaged in the latest binary releases) and it should now support volatile file memory as well as writable file memory. But you'd need to upgrade to latest download with todays date.

example: `sudo ./memprocfs -vv -disable-python -mount /mnt/memprocfs/ -device file://file=/cloudflow/connector/win10/mem,volatile=1,write=1`

(no need for MemProcFS to be run as root though, it would depend on your target mount point and the rights on the mem file).

For more info, check out: https://github.com/ufrisk/LeechCore/wiki/Device_File


Also, if you're into the rust programming language check out the MemProcFS API at: https://crates.io/crates/memprocfs The versions (major.minor) should follow the MemProcFS releases.

Anyway, please let me know how it goes, and also if writes work for you (if it's supported by the virtual memory file you're using?). It would be pretty nice for others to have KVM support on PCILeech and MemProcFS.

**Comment by adeliktas** [comment]
i did fetch LeechCore and MemProcFS upstream and rebuilt both.

`file://file=/cloudflow/connector/win10/mem` will cause a DEVICE: ERROR: Failed opening file

following works to specify the device file path:
```
/cloudflow/connector/win10/mem
file:///cloudflow/connector/win10/mem
"file:///cloudflow/connector/win10/mem"
```

It was not possible to pass the arg/value for volatile and write after the file path (also not with setting it in env var)
`./memprocfs -vv -disable-python -mount /mnt/memprocfs/ -device /cloudflow/connector/win10/mem,volatile=1,write=0`
`DEVICE: ERROR: Failed opening file: '/cloudflow/connector/win10/mem,volatile=1,write=0'`

and cloudflow fuse does not support write yet

**Comment by ufrisk** [comment]
It looks like the changes aren't included in your custom build.

I think you have to do a git clone of the LeechCore repository rather than downloading the zip source archive (which isn't yet up to date).

Make sure you have these lines in the device_file.c    https://github.com/ufrisk/LeechCore/blob/f4a28eb8a7e5a34a9a1f5933eaf7c29616a7ef8a/leechcore/device_file.c#L784

Also, the leechcore.so would need to have to be next to the memprocfs binary.

Oh well, if writes aren't supported it's no biggie, the file support from MemProcFS should be there once it's updated.

Can you retry making sure you have the updated LeechCore source files, (or download the binary release).

**Comment by adeliktas** [comment]
ok just to be 100% sure i cloned the repos and rebuilt it again and now it works. I guess it didn't rebuilt properly with the changes and needed a make clean.
I will run some more tests, but so far it looks great!

**Comment by adeliktas** [comment]
-misc/procinfo/dtb.txt does not get refreshed

**Comment by ufrisk** [comment]
I'm guessing it is, every 5 minutes by default. It's a quite heavy operation to generate that file so it's put on the slowest refresh rate.

There isn't an option to force a refresh manually from the file system at the moment. If it would be helpful I could add it as a feature in some updates I have planned for next week.

If you're using the API you should be able to force an update manually though via an API call.

**Comment by adeliktas** [comment]
refresh force all works great. Thanks for the fast update ♥
