### ISSUE TITLE
sometimes read pool address fail

### ISSUE THREAD

**Issue by pipiw33** [ufrisk/MemProcFS#178]
Hi ufrisk,
I use memprocfs' VMMDLL_Map_GetPool and loop to get a specific address,
Everyone can get the BIG POOL address with a size of 0x200000
but some people cannot read the value of this address using VMMDLL_MemReadEx(hVMM, 4, pPoolEntry->va, &value, 8, &numofbytetoread, VMMDLL_FLAG_NOCACHE);
numofbytetoread = 0, value = 0
------------------------------------------------------------
# Initialize from FPGA:
PRESS ANY KEY TO CONTINUE ...
CALL:    VMMDLL_Initialize
SUCCESS: VMMDLL_Initialize
PRESS ANY KEY TO CONTINUE ...
CALL:    VMMDLL_ConfigGet
SUCCESS: VMMDLL_ConfigGet
         ID = 4
         VERSION = 4.10
SUCCESS: LcCommand: STATUS REGISTER AUTO-CLEAR
------------------------------------------------------------
# Retrieve Pool Tag Map
PRESS ANY KEY TO CONTINUE ...
CALL:    VMMDLL_Map_GetPool
Pool Entry va = ffff99f905200000  value = 0 numof = 0 size = 200000
SUCCESS: VMMDLL_Map_GetPool
------------------------------------------------------------
I don't know if it is because Pool Entry va is a wrong address, or there is some protection on this address that makes it impossible to read

**Comment by ufrisk** [comment]
Hi and thank you for your sponsorship 💖 

Unfortunately this is a really hard question to answer, it may depend on multiple things. I would need a memory dump file that have this issue to look at to be able to tell.

**Comment by pipiw33** [comment]
How can i get memory dump file ?
Actually I really appreciate your contribution

**Comment by ufrisk** [comment]
you can do `pcileech.exe dump`  zip the memory dump and then email the download link to me at pcileech@frizk.net Also take note about what memory address is failing on this specific dump.

**Comment by pipiw33** [comment]
i already send to your email.I use the latest memprocfs(5.5) and leechcore(2.14)

**Comment by ufrisk** [comment]
I have updated MemProcFS to v5.5.3. In this version I have relaxed some over-stringent quality checks on the page tables (which have also caused issues in the past). I hope this version will work better.

Also, I have added a custom option that should allow you to set the quality threshold by default: `-debug-pte-quality-threshold`

Default value is 32. Lower value = more checks, Higher value (max 512) = less checks.

Example to disable checks: `-debug-pte-quality-threshold 512`

Let me know if this should still cause any issues for you.

**Comment by pipiw33** [comment]
Hi ufrisk,
I received your message three hours ago and downloaded the latest version 5.5.3
I tried three computers that I had problems with before,
When using this parameter as before, the problem still exists ,I can't read the value
` hVMM = VMMDLL_Initialize(4, (LPSTR[]) { "", "-device", "fpga", "-norefresh" });`
but when I use the additional custom option `-debug-pte-quality-threshold` I can get the data correctly
use ` hVMM = VMMDLL_Initialize(6, (LPSTR[]) { "", "-device", "fpga", "-norefresh", "-debug-pte-quality-threshold","64" });` issue has been resolved
And I tested on three computers using
` hVMM = VMMDLL_Initialize(6, (LPSTR[]) { "", "-device", "fpga", "-norefresh", "-debug-pte-quality-threshold","128" });`
all working fine

**Comment by ufrisk** [comment]
Hi and thanks for confirming it now works with that extra debug option. Good thing I added it. Issue is resolved then 😄
