### ISSUE TITLE
Timeline csv files created with extra non-valid column data

### ISSUE THREAD

**Issue by swepeba** [ufrisk/MemProcFS#180]
Hi,
This is true for version 5.5 and 5.6.

In forensic mode, a bunch of csv files are created in M:\forensic\csv

![timeline_extra_1](https://user-images.githubusercontent.com/49794422/236133461-56b88e0c-2485-4a13-ac5f-72692ceeaad6.png)

All csv files named timeline_*, include extra non-valid column data for each row except the header row (that are valid). The extra column data includes several empty spaces between the last comma and the line feed. 
Please see screenshot below (click image for details).

![timeline_extra](https://user-images.githubusercontent.com/49794422/236133470-b1e101ed-a7c6-40b9-b652-482b45dc2ff2.png)

The last comma and spaces should be removed to result in a valid csv file.
The other csv files seem to be valid.

Thanks for a great product!
Kind regards,
Peter

**Comment by ufrisk** [comment]
If I remember correctly it's some kind of padding to speed up generation of the files.

It's however clearly breaking the CSV format and even tho Timeline Explorer seems to be handling it I'm guessing that there are other tools that are more strict in the parsing.

I'll fix it, hopefully I'll remove it completely, worst case I'll add a Pad column or something.

I'm away over the weekend though so I'll look into it next week.

**Comment by ufrisk** [comment]
This should now be resolved. I added the extra column Pad instead. Reason is that it speeds up the processing of the timeline a lot. If skipping it I'd be looking at a ~20% slowdown.

Anyhow, it should now contain valid CSV. Please let me know if there should be any remaining issues around this.

And thank you for making me aware of this.
