### ISSUE TITLE
Vmmsharp AOT Warning

### ISSUE THREAD

**Issue by imerzan** [ufrisk/MemProcFS#181]
Noticed when doing some testing with .NET7 / AOT that Vmmsharp appears to be throwing some warnings.

`Warning	IL3050	Using member 'System.Runtime.InteropServices.Marshal.SizeOf(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the object might not be available. Use the SizeOf<T> overload instead.	AOTTest	~redacted~\vmmsharp.cs	129	Active`

I noticed there are a heap of `Marshal.SizeOf(typeof(T))` calls in the wrapper. For example
https://github.com/ufrisk/MemProcFS/blob/976f2e32eed532c614e92b1f086110326b4e4ee7/vmmsharp/vmmsharp.cs#L129

could be changed to
```csharp
int cbERROR_INFO = System.Runtime.InteropServices.Marshal.SizeOf<lci.LC_CONFIG_ERRORINFO>();
```

Which will satisfy the compiler

`SizeOf<T>` is also compatible with .NET Framework 4.5.1 and newer, which should be sufficient for the majority of .NET Applications, since Framework is on 4.8 at the moment.

**Comment by ufrisk** [comment]
Interesting, I actually haven't tested it on .NET7, only on .NET 4.x.

I'm away for a few days. I will take a look at it when I'm back home. But it seems to be pretty straightforward to change. Thanks for reporting this :)

**Comment by ufrisk** [comment]
This should now be updated in the last changes. Let me know if this works fine for you.

**Comment by imerzan** [comment]
> This should now be updated in the last changes. Let me know if this works fine for you.

Yup! Looks good 😄 Thanks
