### ISSUE TITLE
input pid for mem_read in vmmrust

### ISSUE THREAD

**Issue by wvaljean4557** [ufrisk/MemProcFS#182]
Hi ufrisk, recently I try to learn Rust and I found that there are some differences between vmm for Rust and vmm for C++,
I can see you use `u32::MAX` instead of requiring a `pid : u32` or something else in the Rust version.
Rust: 
```Rust
    pub fn mem_read_ex(&self, pa : u64, size : usize, flags : u64) -> ResultEx<Vec<u8>> {
        return self.impl_mem_read(u32::MAX, pa, size, flags);
    }
```
C++
```c++
BOOL VMMDLL_MemReadEx(_In_ VMM_HANDLE H, _In_ DWORD dwPID, _In_ ULONG64 qwA, _Out_writes_(cb) PBYTE pb, _In_ DWORD cb, _Out_opt_ PDWORD pcbReadOpt, _In_ ULONG64 flags)
{
    CALL_IMPLEMENTATION_VMM(H,
        STATISTICS_ID_VMMDLL_MemReadEx,
        VMMDLL_MemReadEx_Impl(H, dwPID, qwA, pb, cb, pcbReadOpt, flags))
}
```
when I want to read memory from a specific pid, I need to call `mem_virt2phys` function to get pa( the value that `mem_read_ex` needs)
That way looks a bit repetitive, so I tried to update `mem_read_ex` like this:
```Rust
    pub fn mem_read_ex(&self, pid : u32, pa : u64, size : usize, flags : u64) -> ResultEx<Vec<u8>> {
        return self.impl_mem_read(pid, pa, size, flags);
    }
```
then every parameter looks mixed, I can't compile the program and get error like this:
```Rust
135 |         if let Ok(s) = vmm.mem_read_ex(pid, va, size, flags) {
    |                            ^^^^^^^^^^^      --        ----- argument of type `u64` unexpected
    |                                             |
    |                                             expected `usize`, found `u64`
```
I'm just new to vmmrust and Rust so I don't know how to add a pid parameter correctly and if there is any other easy way to read memory with va or pid.

**Comment by ufrisk** [comment]
Are there any specific reason you wish to read physical memory using mem_read_as using the Vmm struct directly?

In your case it's probably better to read virtual memory directly using mem_read, mem_read_ex or mem_read_as using the VmmProcess struct https://docs.rs/memprocfs/5.6.1/memprocfs/struct.VmmProcess.html#method.mem_read_ex instead.

**Comment by wvaljean4557** [comment]
Yeah, I do check the examples, I make a mistake of  `vmmprocess.mem_read()` and `vmm.mem_read()` in the examples, I appreciate your help and am sorry for wasting your time.

**Comment by ufrisk** [comment]
no worries, it happens even the best :)

please let me know if you run into any more issues or if you wish for any additions to the rust API and I'd do my best to help.

Anyway, closing the issue since it seems to be successfully resolved. And best wishes with your vmmrust project 👍
