### ISSUE TITLE
unable to connect to FPGA device on live system

### ISSUE THREAD

**Issue by bbrty** [ufrisk/MemProcFS#183]
Hello, 

I have bought an FPGA device, flashed it with its correct firmware and it shows up in the device manager on windows. However when running this command "memprocfs.exe -device FPGA -v" i get an error saying ""
DEVICE: FPGA: ERROR: Unable to connect to USB/FT601 device [0,v0.0,0000]
MemProcFS: Failed to connect to memory acquisition device.
""
Please could you let me know if I'm being stupid or if theres an issue I need to fix!

cheers,

**Comment by ufrisk** [comment]
it's a usb connection issue or a bad flash. which fpga are you using?

is the usb cable connected to the correct port?
have you downloaded and put the ftd3xx.dll alongside memprocfs.exe?
have you had your memprocfs pc connected to the internet so that the ftdi usb kernel driver have been downloaded and installed automatically from windows update?

**Comment by bbrty** [comment]
When i flashed it all outputs looked identical to screenshots of a demonstration, should i just retry with a different cable? 
I am using a LambdaConcept Squirrel and both computers were connected to the internet.

**Comment by ufrisk** [comment]
and you moved the cable to the data port after the flash?
and you downloaded the ftd3xx.dll and put it alongside memprocfs.exe?

also, after the flash you may have to power off/on the device for the flash to be loaded onto the fpga.

**Comment by bbrty** [comment]
yes, yes and yes. All three have been done exactly the way documentation explains and i still get the error.

**Comment by ufrisk** [comment]
is the led on the fpga board blinking a couple of times when you first power it up?

Do you see the FTDI FT01 USB 3.0 Bridge Device in Device Manager?

![image](https://github.com/ufrisk/MemProcFS/assets/18221464/eda950fe-66fa-4c65-b7ec-af3a3d52a361)

**Comment by bbrty** [comment]
When first powered on, it blinks several times then i see two leds constantly on. I see the device in the device manager.

**Comment by imerzan** [comment]
> When first powered on, it blinks several times then i see two leds constantly on. I see the device in the device manager however it is identified as FTDI SuperSpeed-FIFO Bridge(in the other device section) and also a USB composite device(in the Universal Serial Bus Controllers). I am attempting to attack my own PC since i don't have a second one on hand so this may be why there are two devices recognised. ![image](https://user-images.githubusercontent.com/88633188/239284521-5ed03e93-a6c0-48f0-a2e1-12b8fab5d3d6.png)
> 
> When clicking on the properties of the FTDI SuperSpeed-FIFO Bridge, it tells me there are no drivers installed. When i click update driver it tell me none can be found. Is this the cause of the issue?
> 
> ![image](https://user-images.githubusercontent.com/88633188/239287168-69a6c951-e373-4139-af84-6a749382dc1b.png)
> 
> ![image](https://user-images.githubusercontent.com/88633188/239287511-430f3b76-80e2-4f92-a74e-96582cc1c0f2.png)

You need to install the windows driver manually. You can download the package here https://ftdichip.com/drivers/d3xx-drivers/

Select Update Driver and navigate to the folder you downloaded.
