### ISSUE TITLE
How to get the sys module address through python?

### ISSUE THREAD

**Issue by Monday-Leo** [ufrisk/MemProcFS#185]
I successfully get the win32kbase.sys module address using C++ like this:
`VMMDLL_Map_GetModuleFromNameU(hVMM,HIDVars.dwWinlogonPid | VMMDLL_PID_PROCESS_WITH_KERNELMEMORY, (LPSTR)"win32kbase.sys", &pMapModuleEntry, NULL)`
But when I use python api, it doesn't work:
```
vmm = memprocfs.Vmm(['-device', 'fpga'])
process = vmm.process('winlogon.exe')
module = process.module('win32kbase.sys')
```
The error is:
`RuntimeError: Process.module(): Failed.`
Does python api only achieve dll module? How to get the sys module address through python?

**Comment by ufrisk** [comment]
hm, I haven't added that flag to the python function.

I think you should be able to do:
```Python
vmm = memprocfs.Vmm(['-device', 'fpga'])
pid_winlogon = vmm.process('winlogon.exe').pid
process = vmm.process(pid_winlogon | memprocfs.PID_PROCESS_CLONE_WITH_KERNELMEMORY)
```
and then use that object. please let me know if this works for you.

**Comment by Monday-Leo** [comment]
It perfectly works. Thank you so much！

**Comment by ufrisk** [comment]
Nice to see it now works. Let me know if you should run into any future issues or if you wish for me to add new features that you feel is missing.

Best wishes with your DMA attacking.
