### ISSUE TITLE
Minidump not being generated

### ISSUE THREAD

**Issue by bbrty** [ufrisk/MemProcFS#186]
Hello,

Sorry for opening another issue but I've been trying to dump an (non-kernel)application to reverse engineer, however, memprocfs won't generate the dump file, I know memprocfs is all working as it should as I can read and write to the process successfully using the python API, however, really need the minidump file!

How can I go about troubleshooting this?

Many thanks,

**Comment by ufrisk** [comment]
I'm guessing it has to do something with symbols. Make sure you have the most updated version of the python package. I cache required symbols in the info.db database file which is co-packaged with the package.

If using python on Windows make sure to answer yes to the popup about the microsoft symbol server.

If using python on Linux I haven't co-packaged online symbol support yet (the cached symbols should still work though). It's on my todo-list to co-package symbol support for x64 Linux. It's not likely on other platforms such as ARM unfortunately.

To better pinpoint the issue (if the you could add additional start-up options: `"-printf", "-v", "-loglevel" "symbol:7,infodb:7"`

Please let me know how it goes.

**Comment by ufrisk** [comment]
Also, minidump support on Linux is also currently slightly broken, but it should work fine on Windows. It's on my todo-list to fix.

**Comment by bbrty** [comment]
The computer i am running MemProcFS from is running windows, and i've accepted the Symbol Server popup. I used the start-up options and see there are missing type offsets and symbol offsets. Ill paste the output i get below: 

Does this mean the symbols aren't being downloaded correctly?


 
==============================  MemProcFS  ==============================
 - Author:           Ulf Frisk - pcileech@frizk.net
 - Info:             https://github.com/ufrisk/MemProcFS
 - License:          GNU Affero General Public License v3.0
   ---------------------------------------------------------------------
   MemProcFS is free open source software. If you find it useful please
   become a sponsor at: https://github.com/sponsors/ufrisk Thank You :)
   ---------------------------------------------------------------------
 - Version:          5.6.2 (Windows)
 - Mount Point:      M:\
 - Tag:              19041_d27c26e2
 - Operating System: Windows 10.0.19041 (X64)
==========================================================================

[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_LFH_SUBSEGMENT.BlockOffsets
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_LFH_SUBSEGMENT.BlockBitmap
[INFODB]   Missing TypeSize(Dynamic): wntdll!_SEGMENT_HEAP
[INFODB]   Missing TypeSize(Dynamic): wntdll!_HEAP_SEG_CONTEXT
[INFODB]   Missing TypeSize(Dynamic): wntdll!_HEAP_PAGE_SEGMENT
[INFODB]   Missing TypeSize(Dynamic): wntdll!_HEAP_PAGE_RANGE_DESCRIPTOR
[INFODB]   Missing TypeSize(Dynamic): wntdll!_HEAP_VS_CHUNK_HEADER
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP.Encoding
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP.VirtualAllocdBlocks
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP.FrontEndHeap
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP.FrontEndHeapType
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_SEGMENT.FirstEntry
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_SEGMENT.LastValidEntry
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_USERDATA_HEADER.Signature
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_USERDATA_HEADER.EncodedOffsets
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_USERDATA_HEADER.BusyBitmap
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_USERDATA_HEADER.BitmapData
[INFODB]   Missing TypeChildOffset(Dynamic): _SEGMENT_HEAP.LargeAllocMetadata
[INFODB]   Missing TypeChildOffset(Dynamic): _SEGMENT_HEAP.LargeReservedPages
[INFODB]   Missing TypeChildOffset(Dynamic): _SEGMENT_HEAP.SegContexts
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_SEG_CONTEXT.SegmentListHead
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_SEG_CONTEXT.UnitShift
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_SEG_CONTEXT.FirstDescriptorIndex
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_PAGE_RANGE_DESCRIPTOR.TreeSignature
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_PAGE_RANGE_DESCRIPTOR.RangeFlags
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_PAGE_RANGE_DESCRIPTOR.UnitSize
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_LFH_SUBSEGMENT.BlockOffsets
[INFODB]   Missing TypeChildOffset(Dynamic): _HEAP_LFH_SUBSEGMENT.BlockBitmap
[INFODB]   Missing TypeSize(Dynamic): ntdll!_SEGMENT_HEAP
[INFODB]   Missing TypeSize(Dynamic): ntdll!_HEAP_SEG_CONTEXT
[INFODB]   Missing TypeSize(Dynamic): ntdll!_HEAP_PAGE_SEGMENT
[INFODB]   Missing TypeSize(Dynamic): ntdll!_HEAP_PAGE_RANGE_DESCRIPTOR
[INFODB]   Missing TypeSize(Dynamic): ntdll!_HEAP_VS_CHUNK_HEADER
[INFODB]   Missing SymbolOffset: RtlpLFHKey
[INFODB]   Missing SymbolOffset: RtlpLFHKey
[INFODB]   Missing SymbolOffset: RtlpLFHKey
[INFODB]   Missing SymbolOffset: RtlpLFHKey

**Comment by bbrty** [comment]
I am aware you're against cheat development but the dump isn't being generated for Fortnite.

**Comment by ufrisk** [comment]
I'm not really against it, just that I don't wish to get involved so I'll stay out of any potential legal troubles. Also I'm not very interested.

My tools were created for infosec/forensic purposes and it's how I try to pitch them.

Thanks for understanding.

**Comment by ufrisk** [comment]
If you find the issue and it's a general issue, such as some over stringent checks on executable size or whatever I'll be happy to fix it. But I won't be able to look into what is causing this issue for you so it's more if you're able to debug it yourself.

If it's something very fortnite specific that the anti-cheat put in there I'd rather stay away from it.

Once again, thanks for understanding.
