### ISSUE TITLE
Yara - the accept Elastic license switch in PowerShell

### ISSUE THREAD

**Issue by Bloggzy** [ufrisk/MemProcFS#188]
Issue: 
I've found a small issue with accepting the Elastic license switch when using PowerShell.

Background:
When trying to start MemProcFS using PowerShell and using the switch `-license-accept-elastic-license-2.0` it would error and show me the help information. By contrast, running it the same command from command prompt it would start correctly.

It appears to be linked to the "2.0" in the switch, as PowerShell highlights the ".0":
![image](https://github.com/ufrisk/MemProcFS/assets/46377651/9d73c6c1-0f39-4c39-b220-e0b1ead0c782)

The quick fix seems to be wrapping it in quotes (in PowerShell):
`.\MemProcFS.exe -device C:\Demo\Dumps\citadeldc01.mem -forensic 1 "-license-accept-elastic-license-2.0"`

But this is not ideal, and it took me a minute to work out why it wasn't working correctly, so I'm sure others may encounter the same thing?

Maybe removing the "2.0" from the switch would help, or shorten it to "-license-accept-elastic-license-2" or just "-license-accept-elastic-license"?

**Comment by Bloggzy** [comment]
Not wanting to detract from the excellent work, the new Yara searching feature is awesome btw.

**Comment by Bloggzy** [comment]
Looking at the Elastic licence documentation: https://www.elastic.co/licensing/elastic-license
It appears that they refer to the licence as: "Elastic License 2.0 (ELv2)"
Maybe the switch could be shortened to: -accept-elv2 ? Just a thought.

**Comment by ufrisk** [comment]
This is an open source project, I don't get that many contributions financially and I'm afraid I'm not going pay for legal counsel to verify whether it's okay to shorten it like to the one you suggest. For now I prefer to stay on the safe side of things.

I'll see to that the documentation is updated accordingly when doing the next release I've got planned for July though.

**Comment by Bloggzy** [comment]
No worries, that's fair enough, it's an awesome project none the less, thank you for all your efforts, it's a fantastic tool, please keep up the amazing work.

**Comment by ufrisk** [comment]
This should now be resolved. You may now use `-license-accept-elastic-license-2-0`. Documentation have been updated as well.

(old way of doing it will still work as well).

Thanks for reporting :)
