### ISSUE TITLE
yara yr_initialize() failed with error code 368

### ISSUE THREAD

**Issue by tuttimann** [ufrisk/MemProcFS#190]
Hi, I merged the yara rules from Florian Roth (https://github.com/Neo23x0/signature-base/tree/master/yara) in one file and want to use this file with option "-forensic-yara-rules" but unfortunately it gives me the following error:

_[yara]     yr_initialize() failed with error code 368_

Do you know what to do?

**Comment by ufrisk** [comment]
try to run "yarac" against your combined rules. It may give the error.

**Comment by tuttimann** [comment]
This helped, thanks.
