### ISSUE TITLE
Windows 10. FPGA. Disk is not mounted.

### ISSUE THREAD

**Issue by eXskill** [ufrisk/MemProcFS#195]
Hello, thanks for your project!
Environment:
Windows 10 22H2
AMD Ryzen 5900x
FPGA: ScreamerM2 PCIe

Problem:
The disk is not mounted after running the command:
 memprocfs.exe -device fpga -memmap auto
![image](https://github.com/ufrisk/MemProcFS/assets/42116821/04da57cf-bbb4-46f3-8a78-958db31ae67d)

There are no errors.
Dokany, FTD3XXDriver, FTD3XXLibrary installed.
There are no problems with the connection:
![image](https://github.com/ufrisk/MemProcFS/assets/42116821/a6695e5b-1b3b-4a44-afc0-779440908f06)

If roll back the version of LeechCore to v2.11.1, then an error:
[CORE]     Initialization Failed. Unable to locate valid DTB. #2
VmmProc: Unable to auto-identify operating system for PROC file system mount.
		Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.
MOUNT: INFO: PROC file system not mounted.

**Comment by ufrisk** [comment]
It should hopefully work now if you download the latest binaries from the releases section. There was a bug in the FPGA implementation in leechcore.dll. Huge thanks for reporting 👍  Please let me know how it goes.

![test](https://github.com/ufrisk/MemProcFS/assets/18221464/b42e7957-d1a5-48a2-9267-c41079d506fe)

**Comment by eXskill** [comment]
Now it works great! You are the best.

**Comment by ufrisk** [comment]
Awesome, and thanks for confirming. Best wishes with your DMA project. If you find my tools useful think about sponsoring with a small amount 💖
