### ISSUE TITLE
Manually call `VMMDLL_Close` from Rust

### ISSUE THREAD

**Issue by KernelKrusha** [ufrisk/MemProcFS#197]
I am using Bevy and it's `Resource` system to keep a memory context wrapper struct that contains the `Vmm` since I want to easily access it from different places in my application. It works but the `Drop` impl is never called when my application exits.

```rust
#[derive(Debug)]
pub struct MemCtx<'a> {
  pub(crate) vmm: Arc<Vmm<'a>>,
}

pub struct MyBevyPlugin;

impl Plugin for MyBevyPlugin {
  fn build(&self, app: &mut App) {
    app.add_systems(Startup, setup_vmm);
  }
}

fn setup_vmm(world: &mut World) {
  let vmm = Arc::new(Vmm::new(&vmm_dll_path, &vmm_args);
  world.insert_non_send_resource(MemCtx { vmm });
}
```

If I implement `Drop` on my `MemCtx` struct and print I can see that it does get called, however `Drop` for `Vmm` is never called.

This is obviously not a bug in MemProcFS, but since there is no public cleanup function available, I really don't know how to solve it. Would it be possible to add a public `close` function on `Vmm` perhaps?

**Comment by KernelKrusha** [comment]
It turns out that I was not shutting down my Bevy app correctly. When doing a proper clean shutdown as per Bevy's docs, the resource gets dropped as expected.

**Comment by ufrisk** [comment]
I'm glad the issue resolved itself :)

Let me know if you should run into anything else in the Rust API or if you wish for new features / find anything strange.

It's a fairly new API so there is still good chance to change things around should it be needed. I tried to design it to be fairly rustish, but I'm quite new to Rust so I'm sure I missed out on quite a few things...

Anyway, best wishes with your project 👍

**Comment by KernelKrusha** [comment]
Thank you! :)

The only real pain point for me right now is that `VmmProcess` borrows from `Vmm` which makes perfect sense, but the borrow checker will prevent you from having a wrapper struct with both the `vmm` and a process inside.

From my example above:

```rust
#[derive(Debug)]
pub struct MemCtx<'a> {
  pub(crate) vmm: Arc<Vmm<'a>>,
  pub(crate) some_process: Arc<VmmProcess<'a>>,
}
```

The way I do it right now is to simply `mem_ctx.vmm.process_from_name()` everywhere I need it but that feels wrong.

**Comment by ufrisk** [comment]
Yeah, I can see how that is an issue, but it kinds needs to be like that, that process borrows from vmm :\ I don't know a good way around it.

The best solution is probably something like what you're doing. If  you call it really often process_from_pid will be a bit more efficient.

Or mess around with Box and raw pointers to destroy the borrow somehow, but just going with process_from_pid is probably much easier and performance shouldn't really be a problem for that one.

**Comment by KernelKrusha** [comment]
Maybe https://doc.rust-lang.org/std/sync/struct.Arc.html would solve this? As you said, it's not critical for me since I wont be creating new processes often, just a couple times for the entire lifetime of the program.

**Comment by KernelKrusha** [comment]
I was able to use https://github.com/Voultapher/self_cell for a self-referential struct 😄

**Comment by ufrisk** [comment]
Awesome and thanks for the update :)

I should add this to the documentation/examples in next version. it will be quite useful for others as well.

**Comment by alexanderzinolidis** [comment]
Absolutely! :-)

In most cases it's probably not required since you can just structure the code in different ways to make the borrow checker happy.
