### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [ufrisk/MemProcFS#2]
[An extra null pointer check is not needed in functions](https://docs.microsoft.com/en-gb/windows/desktop/api/winbase/nf-winbase-localfree "Do I need to check for null before LocalFree(hMem)?") like the following.
- [LdrModule_CloseHandleModule](https://github.com/ufrisk/MemProcFS/blob/c0318d6f31fbfcd56984683faf63db535aa7b2a3/vmm/m_ldrmodules.c#L31 "https://github.com/ufrisk/MemProcFS/blob/c0318d6f31fbfcd56984683faf63db535aa7b2a3/vmm/m_ldrmodules.c#L31 function")
- [VfsClose](https://github.com/ufrisk/MemProcFS/blob/c0318d6f31fbfcd56984683faf63db535aa7b2a3/MemProcFS/vfs.c#L392 "VfsClose function")

**Comment by ufrisk** [comment]
I'm closing this issue since this has been resolved in Version 1.1 published a week ago.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/ufrisk/MemProcFS/commit/4350b74492515e0f5e90013f96fd1d435ecec09c#diff-2afc41f980bf2a8ef3e603ce6eacd173L38 "Version 1.1").
