### ISSUE TITLE
Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known

### ISSUE THREAD

**Issue by hakija** [ufrisk/MemProcFS#20]
Hello,

Not really an issue more of a question....
How does one find this info: Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.
Can you share a bit more info on what it is? I watched your talk on BlueHat where I think you were referencing this.

I guess issue arises when you are dealing with a RAW memory dump or just CP of a vmem file?
Crash dumps are fine if I understand correctly....

Fantastic work by the way!!!

**Comment by ufrisk** [comment]
Hi, and thanks :)

it's possible to specify it on the command line; example: `MemProcFS.exe -device dumpfile.raw -cr3 0x1ab000`

In reality it's nowdays almost obsolete when analyzing Windows memory dumps since the auto-detect algorithm have been improved a lot since my BlueHat last year.

**Comment by hakija** [comment]
Thanks for quick reply!

I'm memory forensics and have tried so far about 10 different images and half of them throw me this error. Just tried specifying that specific offset you mentioned on one and it worked, but have no clue why :)  Was hoping that was some reasonable explanation or what to look for in memory dumps...Why THAT specific offset?

**Comment by ufrisk** [comment]
There still are some problems, but it's mostly related to locating the Windows kernel on low-memory systems with some paging from what I've noticed so far.

In your case it would greatly help to take a look at the memory dump to improve things; but I also understand if you're unable to share if they contain sensitive information. Also I'm not really interested looking into WinXP and such, but Win7+ I'd be interested in taking a look at if you do have problems.

If you're able to share the problematic memory dump please drop me a note at pcileech@frizk.net

**Comment by hakija** [comment]
Not a problem...they are not case related, some are for training, CTF stuff and similar
Will close this and continue over email

Thank you!
