### ISSUE TITLE
[Question] Function to retrieve physical section map

### ISSUE THREAD

**Issue by 0xGabriella** [ufrisk/MemProcFS#204]
Just wondering, if theres any function that i can use to dump/retrieve physical section map like MmGetPhysicalMemoryRanges in Windows KMDF?. Thank you so much.

**Comment by ufrisk** [comment]
Hi,

This would be: [VMMDLL_Map_GetPhysMem](https://github.com/ufrisk/MemProcFS/blob/2361020029562b872298198ef57f578db93f79d5/vmm/vmmdll.h#L1766C24-L1766C45)

Please let me know if this is the function you're looking at.

**Comment by 0xGabriella** [comment]
Thank you, that is the function im looking for. Also sorry for late reply. Also 1 more, if there's any function to dump all process CR3/DTB. Thank you so much <3

**Comment by 0xGabriella** [comment]
nvm looks like i found it in the vmm example. Thank you so much
https://github.com/ufrisk/MemProcFS/blob/master/vmm_example/vmmdll_example.c#L1422

**Comment by ufrisk** [comment]
Super nice that you found what you were looking for. I hope this will work well enough 👍
