### ISSUE TITLE
cant read memory

### ISSUE THREAD

**Issue by pipiw33** [ufrisk/MemProcFS#208]
Hi .ufrisk
I have a new problem, I can't read memory on certain addresses of a specific process .

`result = VMMDLL_MemReadEx(hVMM, dwPID, 0x140000000, pbPage2, 0x1000, &cRead, 0);`
return result = true cRead = 0 

`VMMDLL_Map_GetModuleFromNameU`  Failed
`VMMDLL_Map_GetPteU` Failed to get the 0x140000000 memory region
`VMMDLL_Map_GetVadU` Success to get the 0x140000000 memory region

environment:
vmm.dll 5.7.0.118  leechcore.dll 2.15.3.50
const char* argv[6] = { "", "-device", "fpga", "-norefresh", "-debug-pte-quality-threshold","512"  };
hVMM = VMMDLL_Initialize(6, (LPSTR*)argv);

I have dumped the memory and can send it to you

**Comment by pipiw33** [comment]
No, this process is not protected by EAC

**Comment by ufrisk** [comment]
please send me the link to the zipped memory dump at pcileech@frizk.net and I'll take a quick look.

**Comment by pipiw33** [comment]
Already sent

**Comment by ufrisk** [comment]
Thank you for this memory dump. It was quite interesting to see. Unfortunately I won't be able to help with this though.

Best wishes with your projects.
