### ISSUE TITLE
Can the same process open two devices at the same time and use them together

### ISSUE THREAD

**Issue by DIXIN20** [ufrisk/MemProcFS#212]
Can the same process open two devices at the same time and use them together

**Comment by ufrisk** [comment]
Hi and many thanks for the sponsorship 💖 

The answer to this question is No and Yes...

It's not supported to use two devices at the same time and automatically load balance between them which is what you're asking for.

It is however supported to use two devices at the same time if they are used in two separate instances, i.e. two VMMDLL_Initialize calls with two different handles returned. You may select device with fpga://devindex= as described [here](https://github.com/ufrisk/LeechCore/wiki/Device_FPGA).

If I were to support it in a single instance it would not do anything to latency though, and it wouldn't do anything for looking up pointer chains and such though. It would better top speed though. Also, it would be quite a lot of job to do a good job around this so I don't have this feature planned.

As a workaround you could manually load-balance though using two MemProcFS instances (even in the same process).

**Comment by DIXIN20** [comment]
OK, thanks

**Comment by ufrisk** [comment]
I know it's not the ideal answer, but I hope that you should at least be able to use the two instances of MemProcFS solution to manually load balance your requests. In theory you should be able to get double performance as in MB/s, but unfortunately no improvements around the lowest latency.

Best wishes with this project and please let me know should you run into some road blocks 👍
