### ISSUE TITLE
Hello! Has DMA applied for memory

### ISSUE THREAD

**Issue by JIUYUE521** [ufrisk/MemProcFS#213]
Which command is requesting memory?

**Comment by ufrisk** [comment]
it would depend, are you using it via the mounted file system, via the pcileech.exe utility command line or are you using the API? If using the API, which programming language are you targeting?

**Comment by JIUYUE521** [comment]
API C++

**Comment by ufrisk** [comment]
[VMMDLL_MemReadEx](https://github.com/ufrisk/MemProcFS/blob/515f027017f63a4d4ef856b749994b8bc7356ecf/vmm/vmmdll.h#L842) if doing single calls.

if doing many calls in the same go the more complex [ScatterRead](https://github.com/ufrisk/MemProcFS/blob/515f027017f63a4d4ef856b749994b8bc7356ecf/vmm/vmmdll.h#L917) functionality may be used.

The example file is a good place to start: https://github.com/ufrisk/MemProcFS/blob/master/vmm_example/vmmdll_example.c

best wishes with your DMA project.
