### ISSUE TITLE
Read Key Press Status

### ISSUE THREAD

**Issue by TiAmo7** [ufrisk/MemProcFS#221]
I want to read the key press status of the user through DMA. What should I do? is there an example?

**Comment by ufrisk** [comment]
A lot of people are reading key presses from win32k gafAsyncKeyState. The implementation differs between Win11 22H2+ as compared to earlier versions of Windows. So there is basically two ways of doing it.

I don't have an example though. But google a bit and check out/ask on the unknowncheats forum and you'll probably get a better answer than I'm able to give.

Best wishes with your DMA attacks :)
