### ISSUE TITLE
memprocfs and struct

### ISSUE THREAD

**Issue by matheusbranhan** [ufrisk/MemProcFS#223]
```
def read_float_memory(process, address):
    return struct.unpack("<f", process.memory.read(address, 4))[0]
```

```
def read_vec3(process, address):
    try:
        x = read_float_memory(process, address)
        y = read_float_memory(process, address + 4)
        return {'x': x, 'y': y}
    except:
        return
```
        
Hi, is there any API already in memprocfs that can do this for me without using the struct? It's taking a lot of time from my code.

**Comment by ufrisk** [comment]
There is currently no API for this, and I've answered in the other thread. Please don't create multiple issues.

I have a job as well, I can't sit around here monitoring Github 24/7 so it may be a while before I answer sometimes.
