### ISSUE TITLE
const LPSTR should be LPCSTR

### ISSUE THREAD

**Issue by slack69** [ufrisk/MemProcFS#23]
https://github.com/ufrisk/MemProcFS/blob/f2d15cf4fe4f19cfeea3dad52971fae2e491064b/vmm/vmm.h#L83

I was trying to create a project which included `vmm.h`, however received the error:

`a value of type "const char *" cannot be used to initialize an entity of type "const LPSTR"`

It seems to me from [this](https://stackoverflow.com/questions/38220957/c-why-const-lpstr-is-different-than-const-char) Stackoverflow question that you cannot create a `const LPSTR` as using a typedef seals it from further modification and should use `LPCSTR`.

Making this change let me compile, however I'm unsure if I'm missing something here.

**Comment by ufrisk** [comment]
Thanks. It's a small enough change and I'll fix it in the next update.

**Comment by slack69** [comment]
Yeah, didn't think it big enough for a pull request but stopped me from compiling. So seemed important enough for an issue.

**Comment by ufrisk** [comment]
This should now be fixed. Closing issue. Thank you for the suggestion.

https://github.com/ufrisk/MemProcFS/blob/c81302e1ff60d4c4fd4a722181965175840765df/vmm/vmmdll.h#L135
