### ISSUE TITLE
mmap.txt

### ISSUE THREAD

**Issue by matheusbranhan** [ufrisk/MemProcFS#230]
hi ufrisk, for someone reason, i have use all the time the mmap.txt in innicialization, you have any ideia about this? it's my memory, my cpu or my motherboard? or config?

**Comment by ufrisk** [comment]
There is some info about it here: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt

it seems to be an issue primarily with AMD CPUs and Thunderbolt.
