### ISSUE TITLE
VMMDLL_OPT_PROCESS_DTB

### ISSUE THREAD

**Issue by pipiw33** [ufrisk/MemProcFS#231]
`switch(fOption) {
        case VMMDLL_OPT_PROCESS_DTB:
            pProcess->pObPersistent->paDTB_Override = qwValue;
            VmmProcRefresh_Slow(H);
            return TRUE;
        default:
            return FALSE;
    }`
    
Hi .ufrisk
I noticed that after setting the DTB, it calls VmmProcRefresh_Slow to refresh all process, which takes half a second.
I think after I set DTB for a certain process, can I refresh only this process to greatly shorten the time?

**Comment by ufrisk** [comment]
It quite doesn't work that way. The memory cache is located on the physical memory layer so it will have to be completely cleared anyway. In essence MemProcFS does not know which memory belongs to which process and which memory are shared between multiple processes.

Also some kernel-level structures have to be updated. Slow may be a bit overkill though in some scenarios so it may be possible to speed it up a tiny bit.

But is the half a second really an issue if you're changing DTBs?

**Comment by ufrisk** [comment]
I've looked into this some more.

It should be possible to greatly speed up this process if doing it on normal processes, (not the system pid 4 process).

**Comment by pipiw33** [comment]
that would be really cool.I just set the DTB on the user process

**Comment by ufrisk** [comment]
I'll look into this tomorrow if I can do something about it, it's getting quite late over here now...

I'll let you know once the issue is resolved.

**Comment by ufrisk** [comment]
I did an update in 5.8.15 just published in the C/C++ API.

I added a new option `VMMDLL_OPT_PROCESS_DTB_FAST_LOWINTEGRITY` that should do the same thing but pretty much instantly.

Note that it will also clear internal data which will have to be re-generated at first access. Examples of this is the list of modules and VADs. This may still take some time.

But the actual call to set the DTB should now at least be much faster.

Please let me know how it goes, or if you're using some other API than the C/C++ one.

**Comment by pipiw33** [comment]
I'll check it quickly

**Comment by pipiw33** [comment]
I tested it. Works very well for me.
This is much better than my solution.
I just modified `MmX64_Virt2Phys` and `MmX64_Virt2PhysEx`
pObPTEs = VmmTlbGetPageTable(H, paPT & 0x0000fffffffff000, FALSE);
to
pObPTEs = dtb value;

**Comment by ufrisk** [comment]
Awesome to see the issue was resolved and that it now works well :)

This one was a bit hard for me to test so many thanks for confirming it works fine.
