### ISSUE TITLE
MemProcFS: Failed to connect to memory acquisition device.

### ISSUE THREAD

**Issue by JRBusiness** [ufrisk/MemProcFS#233]
Hi, MemProcFS was working before, but today when I try to run 
`memprocfs.exe -device FPGA`
I got 
`MemProcFS: Failed to connect to memory acquisition device.`

Doesn't matter how I try it I still got the same error. However it was working just fine with other  speed test tools.

**Comment by ufrisk** [comment]
Hi, can you try to run the following command:

`memprocfs.exe -device FPGA -v -vv`

It may provide some more debug logs helping with locating what the error may be.

**Comment by JRBusiness** [comment]
Yes, I got this after running above command:
`DEVICE: FPGA: ERROR: Unable to load FTD3XX.dll [0,v0.0,0000]`

**Comment by JRBusiness** [comment]
After downloaded the FTD3XX.dll from https://ftdichip.com/drivers/d3xx-drivers/ and put it in
`c:/windows/system32/`
everything worked fine now.

**Comment by ufrisk** [comment]
Rhanka for the update. Its good to see the issue was resolved!
