### ISSUE TITLE
LeechAgent

### ISSUE THREAD

**Issue by zijingsh** [ufrisk/MemProcFS#235]
Hellol,Ufrisk
Why is this link and tutorial unavailable
https://github.com/ufrisk/LeechCore-dev/wiki/LeechAgent

**Comment by ufrisk** [comment]
Where did you find this link so that I may fix it.

The correct one should be: https://github.com/ufrisk/LeechCore/wiki/LeechAgent

**Comment by zijingsh** [comment]
Thanks for your reply to the link I saw in the wiki

**Comment by ufrisk** [comment]
Thank you for making me aware if this issue.

It should now be fixed.

Please let me know if you should run into additional issues in the future. And thank you once again.
