### ISSUE TITLE
VMMDLL_Map_GetPool fails after Windows update

### ISSUE THREAD

**Issue by trickymagus** [ufrisk/MemProcFS#236]
Windows version: Windows 10 Pro 22H2
Used info.db and other dll files from v5.8.15

It was working right before KB5032189 windows update so I think it is the problem.

**Comment by trickymagus** [comment]
Removing KB5032189 updated solved problem. So it is the problem.

**Comment by ufrisk** [comment]
This will most likely work if you download the most recent binary update which includes the info.db database now with Microsoft November patches. Please let me know if this should not work.
