### ISSUE TITLE
Initialization Failed. Unable to locate valid DTB. #2

### ISSUE THREAD

**Issue by wudehua2016** [ufrisk/MemProcFS#238]
I used the LeetDMA to acquest the memory data, with the command line of " .\MemProcFS.exe -device FPGA", targetting at the ubuntu 22.04, and no vt was turn on. A issues was occur：
[CORE]     Initialization Failed. Unable to locate valid DTB. #2
VmmProc: Unable to auto-identify operating system.
         Specify PageDirectoryBase (DTB/CR3) in -dtb option if value if known.
         If arm64 dump, specify architecture: -arch arm64
[CORE]     Failed to initialize.

BTW, i used to acquest the memory data of the win10, and SUCCEEDED, while fails at ubuntu 22.04.

**Comment by ufrisk** [comment]
MemProcFS does not support analyzing Linux memory. It's a tool for analyzing Windows memory.

If you wish to dump the memory or gain code execution PCILeech will support Linux, but the support is more basic than for the Windows version.

**Comment by wudehua2016** [comment]
Thanks a lot
