### ISSUE TITLE
PDB  QUESTION

### ISSUE THREAD

**Issue by zijingsh** [ufrisk/MemProcFS#240]
Hello to bother you again ：
In China, Microsoft's symbolic parsing server always has some people who cannot link to the server, or cannot download ntkrnlmp.pdb, whose file size is 3KB and incomplete, I want to set a proxy server URL to cache and help customers download. However, I do not know where the change can be made to use the new address to download the operation when the download is incomplete. Second question, if there is info.db in the same directory, can I not download pdb from the symbol server in most cases
Please forgive my poor English expression, I hope you can understand my meaning

**Comment by ufrisk** [comment]
I don't think the Microsoft symbol server libraries I use support a proxy server. They are quite old and I use those due to more restrictive licensing terms on newer versions (I don't know if the newer versions support proxy server either).

For most use cases I think the info.db should be sufficient though. I usually update it 2-3 days after patch Tuesday every month.

**Comment by zijingsh** [comment]
i test my pdb proxy is work，Now I want to know how to change the download address, or if he fails to download the pdb, how do I call him to re-download it with a different download address resolution
thx u help ufrisk

**Comment by ufrisk** [comment]
On Windows, which I assume you're running on, I use the `symsrv.dll` from Microsoft.

I don't think it's capable of proxy servers, but you could look into the documentation, maybe it is possible somehow, or contact Microsoft about it.

If there is something I'd have to do to change MemProcFS to make it work please let me know. But I unfortunately don't think it's supported.

**Comment by jeanga** [comment]
Hope this can be useful to you: https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/firewalls-and-proxy-servers#choosing-a-proxy-server
or may be https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/symproxy will if I misunderstood your actual context.

**Comment by zijingsh** [comment]
@jeanga Thanks for your help
