### ISSUE TITLE
[BUG] vmmsharp Vmm.MemReadArray

### ISSUE THREAD

**Issue by imerzan** [ufrisk/MemProcFS#246]
https://github.com/ufrisk/MemProcFS/blob/646dd6e1b208f1106a5e2c696a61efde1085f55b/vmmsharp/vmmsharp.cs#L985C1-L985C1

The VMMDLL_MemReadEx parameters should be utilizing `cb` instead of `count`. This is only going to cause an issue with types that are greater than 1 byte in size, so probably why it wasn't noticed originally :D oops.

https://github.com/ufrisk/MemProcFS/blob/646dd6e1b208f1106a5e2c696a61efde1085f55b/vmmsharp/vmmsharp.cs#L990C29-L990C29

should also be `cbRead != cb`

**Comment by ufrisk** [comment]
Thanks. I'll fix this 👍

**Comment by ufrisk** [comment]
This should now be resolved. Huge thanks for making me aware of this :)
