### ISSUE TITLE
VMMDLL_Map_GetThread  return failed

### ISSUE THREAD

**Issue by smoke0506** [ufrisk/MemProcFS#247]
I referred to the case in MemProcFS to call, but it failed. The following is the code and return information。

**Comment by ufrisk** [comment]
Thread support requires the files your "out info" says are missing.

Download the latest MemProcFS release in which those files exists from here: https://github.com/ufrisk/MemProcFS/releases/latest

**Comment by ufrisk** [comment]
I'm closing the issue since I hope it will start to work once you added the required dependencies.

Let me know if you still have issues and best wishes with your DMA attacking 👍
