### ISSUE TITLE
vmmWinInit_TryInitialize: Initialization Failed. Unable to locate valid DTB. #2 VmmProc: Unable to auto-identify operating system for PROC file system mount.          Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known. MOUNT: INFO: PROC file system not mounted.

### ISSUE THREAD

**Issue by RaringReaper2** [ufrisk/MemProcFS#250]
mmWinInit_TryInitialize: Initialization Failed. Unable to locate valid DTB. #2
VmmProc: Unable to auto-identify operating system for PROC file system mount.
         Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.
MOUNT: INFO: PROC file system not mounted.

Trying to setup a after getting it flashed and updated im now having this issue

**Comment by ufrisk** [comment]
if your target computer have an AMD CPU or if you use thunderbolt you have to use a  [memory map](https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt)

Also try to power off / power on the target and then run: `pcileech -device fpga -v -vv display -min 0x1000` to see if DMA is working at all.

If having custom firmware try the default one I provide in the [pcileech-fpga](https://github.com/ufrisk/pcileech-fpga) project.

**Comment by ufrisk** [comment]
Since I haven't heard anything about this issue I assume it's resolved. I'm closing it. If its not let me know.
