### ISSUE TITLE
[question]Can I call an exported function and get the return?

### ISSUE THREAD

**Issue by ChunkyZhang** [ufrisk/MemProcFS#254]
If could ，how to do ，I'm  noob in coding...
Very Thanks :-)

**Comment by ufrisk** [comment]
You mean like in general? Then it may be best to read up on a programming tutorial of your selected language.

If you mean PCILeech exported function there is documentation and also an example project here: https://github.com/ufrisk/MemProcFS/tree/master/vmm_example There are also other examples for other languages in the documentation.

If you mean call an OS function on the attacked machine directly over DMA that is not possible. You'd have to create some kind of hook to gain code execution first and then call the OS function of your choice on the target system.

I have set up a Discord also if you wish to ask some more general questions: https://discord.gg/BCmfBhDPXX
