### ISSUE TITLE
symbols fail on Windows when there are non-ascii characters in the MemProcFS path.

### ISSUE THREAD

**Issue by dongdun** [ufrisk/MemProcFS#255]
![1](https://github.com/ufrisk/MemProcFS/assets/154966122/11fc5165-035f-486b-9b5c-a3340094702d)

Not only this problem, I feel that many of my files have not been read. Compared with others, other people's txt files have content, while many of mine are empty files.

my system is win11

**Comment by ufrisk** [comment]
Have you copied the latest binaries from https://github.com/ufrisk/MemProcFS/releases/tag/v5.8 and unzipped all files in the folder you wish to use.

netstat is sometimes reliant on symbols which are updated each path tuesday by me or downloaded from Microsoft (but you'd need all the DLL files in that download for it to work).

Please let me know if this resolved your issue.

**Comment by dongdun** [comment]
> Have you copied the latest binaries from https://github.com/ufrisk/MemProcFS/releases/tag/v5.8 and unzipped all files in the folder you wish to use.
> 
> netstat is sometimes reliant on symbols which are updated each path tuesday by me or downloaded from Microsoft (but you'd need all the DLL files in that download for it to work).
> 
> Please let me know if this resolved your issue.


1. I copied all the MemProcFS folders installed in Win11 to another Win10 computer, which means that the files are the same. After the Win10 computer executes, the content of netstat can be seen.

2. And my Win11 error is indeed a symbol related issue, but as mentioned earlier, the MemProcFS files are all the same, so I am not sure if it is a problem with the Win11 basic environment or if some files of Win11 were called that I do not have.



Initialized 64-bit Windows 10.0.22621
[SYMBOL]   Functionality may be limited. Extended debug information disabled.
[SYMBOL]   Offline symbols unavailable - file 'info.db' not found.
[SYMBOL]   Reason: Unable to download kernel symbols to cache from Symbol Server.


==============================  MemProcFS  ==============================
 - Author:           Ulf Frisk - pcileech@frizk.net
 - Info:             https://github.com/ufrisk/MemProcFS
 - Discord:          https://discord.gg/BCmfBhDPXX
 - License:          GNU Affero General Public License v3.0
   ---------------------------------------------------------------------
   MemProcFS is free open source software. If you find it useful please
   become a sponsor at: https://github.com/sponsors/ufrisk Thank You :)
   ---------------------------------------------------------------------
 - Version:          5.8.20 (Windows)
 - Mount Point:      M:\
 - Tag:              22621_8442b8ee
 - Operating System: Windows 10.0.22621 (X64)
==========================================================================

**Comment by dongdun** [comment]
> Have you copied the latest binaries from https://github.com/ufrisk/MemProcFS/releases/tag/v5.8 and unzipped all files in the folder you wish to use.
> 
> netstat is sometimes reliant on symbols which are updated each path tuesday by me or downloaded from Microsoft (but you'd need all the DLL files in that download for it to work).
> 
> Please let me know if this resolved your issue.


Sorry, I found the problem. The installation path of my MemprocFS contains Chinese characters, which causes the program to not execute normally.
For now, just cancel the Chinese characters path.

**Comment by ufrisk** [comment]
I'm reopening the issue, I'll look into to see if I can fix this. If there are issues with the libraries used I might not be able to, but it would be nice to have it working with non-ascii characters.

Thanks for reporting and finding out about this issue 👍

**Comment by ufrisk** [comment]
This bug should now be resolved. Symbols should now work in directories with non-ascii characters. Can you please verify.

**Comment by dongdun** [comment]
I downloaded the latest version for verification and it has been resolved。

> 这个错误现在应该已经解决了。符号现在应该可以在包含非 ASCII 字符的目录中使用。能否请您核实一下。
