### ISSUE TITLE
a doubt about a reading with memprocfs and scatter memory

### ISSUE THREAD

**Issue by ConnorMAD** [ufrisk/MemProcFS#256]
From your Ulf experiences, how can you make reading as fast as possible using Python?
If you have some reading functions with scattermemory or a quick read that can open my mind, I would be grateful.

Happy new year ulf

**Comment by ufrisk** [comment]
Hi, there is a [Scatter API](https://github.com/ufrisk/MemProcFS/wiki/API_Python_ScatterMemory) for Python as well that you may use.

Happy New Year!
