### ISSUE TITLE
Cant start correctly x86 build

### ISSUE THREAD

**Issue by dolodi** [ufrisk/MemProcFS#257]
64 bit build works correctly but when i try to build on x86 it gives this error: The program '[2604] ' has exited with code 3221225595 (0xc000007b).

Are there any 32bit dll ? i think that its using the 64bit dlls, and as such it cant start properly. Its using VMM.dll , leechcore.dll, FTD3XX.dll,
Also im using the leechcore.lib 32bit and vmm.lib 32bit for it.

For 64 bit version im using the 64bit Libs.

Does someone knows if it's possible to make a 32bit build for 32bit programs?

**Comment by ufrisk** [comment]
is the build not working or does it build and then crash when you try to run it?

**Comment by dolodi** [comment]
It build and crash, but i fixed it, just had to compile the dlls by myself for the x86 version.
Also now i facing a problem when using VMMDLL_ProcessGetInformationAll i get this error:

The procedure entry point VMMDLL_ProcessGetInformationAll could not be located in the dynamic link library -path/program.exe
