### ISSUE TITLE
MemProcFS: Error file system plugins in vmm.dll!

### ISSUE THREAD

**Issue by dolodi** [ufrisk/MemProcFS#259]
I used a memmap and i resolved a problem, but now i get this error, i didnt see no issues opened on this subject so can somebody help me ?

pcileech.exe dump -memmap physmemmap.txt

Memory Dump: Initializing ... Done.
 Current Action: Dumping Memory
 Current Action: Dumping Memory
 Access Mode:    Normal
 Progress:       2304 / 15344 (15%)
 Speed:          209 MB/s
 Address:        0x0000000190000000
 Pages read:     589824 / 3928064 (15%)
 Pages failed:   0 (0%)

pcileech>memprocfs.exe -device fpga -memmap physmemmap.txt
Initialized 64-bit Windows 10.0.19041
MemProcFS: Error file system plugins in vmm.dll!

**Comment by ufrisk** [comment]
Apologies for the slow answer, I see it was quite a while ago.

Did you get this to work, and if so, what was the error? Are you using the latest download from the releases section at: https://github.com/ufrisk/MemProcFS/releases/latest

**Comment by ufrisk** [comment]
Since I haven't heard back on this one I'll assume it's resolved. Closing the issue.
