### ISSUE TITLE
MemProcFS: Failed to load initial memory map from: '...'

### ISSUE THREAD

**Issue by justno-steep** [ufrisk/MemProcFS#264]
Hello,
I am kinda stuck on trying to read memory.
I always get the error:
MemProcFS: Failed to load initial memory map from: '...', where '...' is something like '¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦ç'.

I use -devicec fpga -v -printf -vv -memmap and a path to a txt. I tried dump it via a different lib and made it per Hand like I saw in another issue via RamMap, both ends up with the same error. I guess the issue lies in there but not sure how to fix it.
Please let me know if you have any idea, or need more information.

**Comment by ufrisk** [comment]
Both of them should work. I'm unable to replicate the issue.

Do you have the start of the screenshot above. Also could you attach one of the memmap.txt files that isn't working here in case there is something strange with the file as such.

**Comment by ufrisk** [comment]
This works completely fine for me.

I however noticed you're running a very ancient version of my tools, `LeechCore v2.13.0`. Please try again with the most recent version of both MemProcFS and LeechCore, bundled together from the releases section here: https://github.com/ufrisk/MemProcFS/releases/latest

**Comment by ufrisk** [comment]
what is your command line, can you show it in a screenshot (not copy/paste)?

**Comment by ufrisk** [comment]
I asked for the command line, the command line you start the MemProcFS with, the one where I see the input arguments. Not the end of the output listing which you showed me before.

**Comment by ufrisk** [comment]
yeah, I'd start by setting a brake point at VMMDLL_Initialize and check out what's up. Something is clearly wrong, and in this case I'm guessing it's something with your code.

If you should run into this issue when running the latest MemProcFS command line please let me know.

Until then I'd unfortunately have to assume there is an error somewhere in your code since I'm unable to replicate the issue command-line.
