### ISSUE TITLE
The error return value of the API VMMDLL_Map_GetPteU.

### ISSUE THREAD

**Issue by alukaduo09** [ufrisk/MemProcFS#266]
The cPages returned from the process page table obtained by me is not correct. 
Shifting cPages << 12 does not yield the correct size.
I also observed the API VMMDLL_Map_GetVadU, and many of the memory pages' end addresses inside it are incorrect.

**Comment by alukaduo09** [comment]
![1](https://github.com/ufrisk/MemProcFS/assets/62860793/7f2b9c78-408f-49ff-b32c-a1536a5a025f)

**Comment by alukaduo09** [comment]
> 你有没有在 discord 频道上问过这个问题？或者也许还有其他人？
> 
> 不幸的是，VAD 与 VirtualQueryEx 不是 1：1 的匹配。

I haven't used Discord because I can't access your channel. It prompts me with "Unable to accept invite".

How can I get the correct size of the memory block?

**Comment by alukaduo09** [comment]
> Did you ask on the discord channel about this? Or maybe there was someone else?
> 
> The VADs is not an 1:1 match unfortunately to VirtualQueryEx.

I haven't used Discord because I can't access your channel. It prompts me with "Unable to accept invite".

How can I get the correct size of the memory block?

**Comment by ufrisk** [comment]
The discord should work I think, try this one:

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>

And as mentioned, unfortunately there isn't quite an 1:1 mapping between `VMMDLL_Map_GetVadU` and `VirtualQueryEx`. In general DMA and memory forensics won't give you perfect results, but results should be fairly close to the true values at least.
