### ISSUE TITLE
Can't specify -memmap file

### ISSUE THREAD

**Issue by BubonicPestilence** [ufrisk/MemProcFS#270]
Hello. Thank you for both of your projects.
While using PCILeech, i was able to specify -memmap mmap.txt and it read it.

While trying to do same in Python, permanently getting errors:

```
    vmm = memprocfs.Vmm(["-device", "fpga", "-memmap", "C:/Upload/mmap.txt"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Vmm.init(): Initialization of vmm failed.

    vmm = memprocfs.Vmm(["-device", "fpga", "-memmap", "C:\\Upload\\mmap.txt"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Vmm.init(): Initialization of vmm failed.

    vmm = memprocfs.Vmm(["-device", "fpga", "-memmap", "mmap.txt"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Vmm.init(): Initialization of vmm failed.
```

Maybe there is some different way of loading this map?

And yes, if i remove memmap option, everything works good.

**Comment by ufrisk** [comment]
Can you try:

`vmm = memprocfs.Vmm(["-device", "fpga", "-memmap", "C:\\Upload\\mmap.txt", "-v", "-vv", "-printf"])`

and see if you get additional debug output. I find this really curious and I should look into it, but having some debut output would be good to rule out some of the more easier to find culprits first.

**Comment by BubonicPestilence** [comment]
Thank yo uvery much, this one worked, and pointed me to possible error.
I've regenerated mmap.txt and it works, so error was in not "fully exported mmap.txt"
