### ISSUE TITLE
MemProcFS C# API: problem with reading file

### ISSUE THREAD

**Issue by awe0312** [ufrisk/MemProcFS#272]
Hello everyone, I new in forensics and I have trouble, when i try to use this code: 
        nt = vmm.VfsRead("\\pid\\" + dwExplorerPID  + passForFile", 0x200, 0x1000, out pbMemoryRead);

I can't read this file, and i can't copy this file to phisical device. 
I see you video in youtube when u have sucsefful example with extracting minidump file in python API, but i want to do same in C# API.

I suppouse, my problem related with this parameters: 0x200, 0x1000 (maybe it's offset and count bytes for read) but how I can configure it, or know it?

Thank you, I hope u can help me!

**Comment by ufrisk** [comment]
First numeric parameter is the bytes to read, the 2nd one is the starting offset inside the file. To read up to 1MB you may use the following:

```C#
byte[] pbMemoryRead;
nt = vmm.VfsRead("\pid\" + dwExplorerPID + "\minidump\minidump.dmp", 0x100000, 0, out pbMemoryRead);
```

If reading a larger file with unknown size it might be a good idea to query the file size first with the [VfsList function](https://github.com/ufrisk/MemProcFS/blob/ca3acb8558b8a0da69104c1b22f95ddd2d10a3fa/vmmsharp/vmm_example.cs#L78).

As for minidumps goes, it should be possible to read them from all processes with the exceptions of the kernel processes (System, Registry, MemoryCompression) and LSASS which is not possible to read minidumps from.

Please let me know of this helps. Also some times it may be faster to ask a query in the Discord programming channel.

<a href="https://discord.gg/BCmfBhDPXX"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>

**Comment by awe0312** [comment]
Thank you for responding!

Unfortunately, the code you provided doesn't work for my case. I can read the file, but not its full size. In this case, I'm only able to read 1,024 KB from this minidump file.

When I try to use the [VFSlist function](https://github.com/ufrisk/MemProcFS/blob/ca3acb8558b8a0da69104c1b22f95ddd2d10a3fa/vmmsharp/vmm_example.cs#L78)

` result = vmm.VfsList("\\pid\\" + dwExplorerPID + "\\minidump", 2, ExampleVfsCallBack_AddFile, ExampleVfsCallBack_AddDirectory);
`

I noticed, that this function write to result only boolean value (true or false) and i can't read this size, what i mention before when  say aboutt your example with python API, you make this with only one command. 

Maybe need ask for programmer in Discord.

**Comment by ufrisk** [comment]
Hi,

The example was for reading max 1MB. If you wish to read between 1-2MB you can do the following:
```C#
byte[] pbMemoryRead;
nt = vmm.VfsRead("\\pid\\" + dwExplorerPID + "\\minidump\\minidump.dmp", 0x100000, 0x100000, out pbMemoryRead);
```

If you wish to read 16MB from offset 0 you can do the following:
```C#
byte[] pbMemoryRead;
nt = vmm.VfsRead("\\pid\\" + dwExplorerPID + "\\minidump\\minidump.dmp", 0x01000000, 0, out pbMemoryRead);
```

**Comment by ufrisk** [comment]
I'm closing this issue since I believe it was resolved. If not, just let me know here.
