### ISSUE TITLE
Please add -V or -version option

### ISSUE THREAD

**Issue by kaarposoft** [ufrisk/MemProcFS#274]
It would be useful, if MemProcFs had an option to show the installed version.
This could be -V or -version.
Many Linux programs have such an option.

**Comment by kaarposoft** [comment]
Maybe a -V option to just show MemProcFs version and a -VV option which show MemProcFs version plus the other points you mention?

**Comment by ufrisk** [comment]
I added the option `-version` to the new version.

It will print the version of vmm.dll/so which is the main analysis library. If this option is given no guide will be printed if not enough other options are given for a proper start-up.

Can you verify this is indeed working as intended?

**Comment by kaarposoft** [comment]
Thank you very much - the stdout now looks exactly as expected.
However, the return code from the process is 1, where I would have expected 0.
