### ISSUE TITLE
An issue with mounting image files

### ISSUE THREAD

**Issue by gongyu0217** [ufrisk/MemProcFS#284]
MemProcFS>MemProcFS.exe -device ./memdump.dmp

**### The following error occurred while executing the above code**

[CORE]     Initialization Failed. Unable to locate valid DTB. #2
VmmProc: Unable to auto-identify operating system.
         Specify PageDirectoryBase (DTB/CR3) in -dtb option if value if known.
         If arm64 dump, specify architecture: -arch arm64
[CORE]     Failed to initialize.

**Comment by ufrisk** [comment]
MemProcFS is not able to analyze the dump for some reason. Is the dump valid? Are you able to open it with Volatility or WinDBG or may it be corrupt?

If it's indeed working in Volatility or WinDBG please let me know if you're able to share this dump. If it's a working memory dump I'm very keen on making it work on MemProcFS as well.
