### ISSUE TITLE
C++ Scatter abnormal

### ISSUE THREAD

**Issue by lishaoju** [ufrisk/MemProcFS#290]
When reading a large amount of data, sometimes the return result is empty
VMMDLL_MemReadEx The returned data is correct

**Comment by ufrisk** [comment]
Is it working now. There was previously a max limit on how many scatters you could prepare. If the return value from the prepare call was not correctly set it would have had this behavior.

But it's resolved in the latest release. Can you check if the latest release of MemProcFS resolves your issue?

**Comment by ufrisk** [comment]
Since I haven't heard anything back about this issue I'm assuming it was resolved. I'm closing this issue.
