### ISSUE TITLE
C++ freezing the Read Requests

### ISSUE THREAD

**Issue by math-muller** [ufrisk/MemProcFS#295]
Basically I have a while(true) loop, which does several readings and every 10 seconds it freezes and then quickly starts working again

Is there any configuration that needs to be done to fix this? It looks like it's something in the lib

**Comment by ufrisk** [comment]
For general questions about the project the Discord server is better than Github issues which are more for bugs and enhancement requests.

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>

As for your timing question there is a background refresh. It's detailed in the guide here: https://github.com/ufrisk/MemProcFS/wiki/FAQ_Timing
