### ISSUE TITLE
The PID can be found, but its base address cannot be found.

### ISSUE THREAD

**Issue by subeoy1** [ufrisk/MemProcFS#297]
#define VMMDLL_ProcessGetModuleBase VMMDLL_ProcessGetModuleBaseW
uintptr_t c_process::get_module_base(const std::wstring& module_name) {
return VMMDLL_ProcessGetModuleBase(m_vmh, (DWORD)m_pid, (LPWSTR)module_name.c_str());
m_base = get_module_base(utils->string_to_wstring(process_name));
if (!m_base)
{
std::cout << "Failed getting base address for process.\n";
return false;
}
if fails the m_base is 0

**Comment by S1ckZer** [comment]
The 5E Protect the Game

no support for cheats :D

**Comment by subeoy1** [comment]
> The 5E Protect the Game
> 
> no support for cheats :D

Why can other people's software support it? Is there any other way?

**Comment by ufrisk** [comment]
No discussions about Anti-Cheat bypasses on this Github. There are far better forums for that. Thank You.

**Comment by S1ckZer** [comment]
@DefaultO 
I know how to do it, of course, but I just want to respect ufrist's rules. 
He doesn't want to support cheaters in his repo or discord.
