### ISSUE TITLE
FAIL:    VMMDLL_PidGetFromName

### ISSUE THREAD

**Issue by hrt** [ufrisk/MemProcFS#3]
I found solutions to most of my problems and now reading and writing are work fine.

I have now decided to look into a process which is protected by an anti-cheat.
The process and PID can be seen when I look from within the target PC but VMMDLL_PidGetFromName fails to find the process from the attacker PC.

~~Would you like for me to upload a memory dump for analysis?~~

So the actual process name is _FortniteClient-Win64-Shipping.exe_ but when I dump and mount memory it appears as _FortniteClient_

**Comment by hrt** [comment]
target pc:
![image](https://user-images.githubusercontent.com/21159953/50006307-3f362580-ffa5-11e8-8bc1-33b9a2e7e940.png)


dump:
![image](https://user-images.githubusercontent.com/21159953/50006339-5ffe7b00-ffa5-11e8-8601-af4e28628ce8.png)

**Comment by ufrisk** [comment]
Yes, it's a limitation at the moment. It's on the todo-list, but will probably take some time to fix.

Currently only the 15 first characters of the process name is used (it's only 15 characters directly in the `EPROCESS` structure which I gather the information from).

Problem with `VMMDLL_PidGetFromName` is that it may return the wrong PID if there are multiple processes which have the same name (in the first 15 characters).

The workaround would be to walk the PID list calling `VMMDLL_ProcessGetInformation` for each PID, check for the name and some other telltale signs of the right process.

**Comment by hrt** [comment]
thanks - that works

**Comment by ufrisk** [comment]
Closing this issue since support for "Long Name" (full name) was added some time ago.
