### ISSUE TITLE
Problem with initialization of vmm

### ISSUE THREAD

**Issue by egorchecpc** [ufrisk/MemProcFS#302]
I'm using the library in Python code. When I run the program I get the following error and I don't understand how to get rid of it ((

File "C:\cs2_radar\app.py", line 230, in <module>
    vmm = memprocfs.Vmm(['-device', 'fpga', '-disable-python', '-disable-symbols', '-disable-symbolserver', '-disable-yara', '-disable-yara-builtin', '-debug-pte-quality-threshold', '64'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Vmm.init(): Initialization of vmm failed.

Windows 10 x64, AMD Ryzen 7 5800h

**Comment by ufrisk** [comment]
Hi,

I'm not going to help you cheat in CS2. Thanks for understanding.
