### ISSUE TITLE
VmmWinInit_FindNtosScan() Fails on some devices with 0xffff

### ISSUE THREAD

**Issue by njbrown09** [ufrisk/MemProcFS#31]
It seems that VmmWinInit_FindNtosScan fails when your deviceid if 0xffff. It has something to do with VmmWinInit_FindNtosScanHint64

This can be fixed by literally just removing the highlighted code shown here:
https://gyazo.com/c87a434b28be5f69fc9d96b632dd8838

**Comment by ufrisk** [comment]
The new release should now be auto-detecting whenever the tiny read algorithm is required. Also it should have a bunch of other improvements which believe me to think this error should have disappeared.

If it's still around please let me know and re-open the issue and I'll have a look again. But I'm fairly sure it should be gone.
