### ISSUE TITLE
What should I do to clear 

### ISSUE THREAD

**Issue by subeoy1** [ufrisk/MemProcFS#310]
VMMDLL_VfsReadW(this->vmm_handle, const_cast<LPWSTR>(L"\\misc\\procinfo\\dtb.txt"), bytes.get(),  buffer_size - 1, &j, 0);
What should I do to clear the cache of this file before he goes to read it? I found your VMM The H function library cannot be found

**Comment by dolodi** [comment]
does this work without re-initializing all the plugins and just refresh the dtb.txt?
