### ISSUE TITLE
Is dokan necessary for VMMDLL_VfsReadW?

### ISSUE THREAD

**Issue by maoxian123** [ufrisk/MemProcFS#311]
```
auto nt = VMMDLL_VfsReadW(HANDLE, (LPWSTR)L"\\misc\\procinfo\\progress_percent.txt", bytes, 3, &i, 0);
if (nt == VMMDLL_STATUS_SUCCESS && atoi((LPSTR)bytes) == 100)
	break;
```
If i dont install dokan,sometimes bytes is always =0
why?

**Comment by ufrisk** [comment]
Reading files in the VFS API is independent of Dokan. Dokan is not required and would in no way affect this.

When you haven't read anything in that folder it's normal to read 0 on the first read. If you wait a while it should read 100 eventually.

**Comment by maoxian123** [comment]
I found some problems,if symbols/ntkrnlmp.pdb download.error ,\\misc\\procinfo\\progress_percent.txt will always 0,how to solve?
VMMDLL_VfsReadW must use pdb?

**Comment by ufrisk** [comment]
are you using the latest release of MemProcFS including all supporting files, including dbghelp.dll, symsrv.dll, info.db, vmm.dll, leechcore.dll from the downloads at?: https://github.com/ufrisk/MemProcFS/releases/latest

**Comment by ufrisk** [comment]
Closing issue since question was answered.
