### ISSUE TITLE
VMMDLL_ProcessGetInformationAll is unavailable

### ISSUE THREAD

**Issue by Space-CN-G** [ufrisk/MemProcFS#312]
BOOL VMMDLL_ProcessGetInformationAll_Impl(_Out_ PVMMDLL_PROCESS_INFORMATION *ppProcInfoAll, _Out_ PDWORD pcProcInfo)
{
    DWORD i, cProcInfo = 0;
    SIZE_T cbAlloc, cbProcInfo, cPIDs = 0;
    PDWORD pdwPIDs = NULL;
    PVMMDLL_PROCESS_INFORMATION pe, pProcInfoAll = NULL;
    // 1: get pid-list
    VmmProcessListPIDs(H, NULL, &cPIDs, VMM_FLAG_PROCESS_SHOW_TERMINATED);
    if(!cPIDs) { goto fail; }
    if(!(pdwPIDs = LocalAlloc(LMEM_ZEROINIT, cPIDs * sizeof(DWORD)))) { goto fail; }
    VmmProcessListPIDs(H, pdwPIDs, &cPIDs, VMM_FLAG_PROCESS_SHOW_TERMINATED);
    if(!cPIDs) { goto fail; }
    cbAlloc = cPIDs * sizeof(VMMDLL_PROCESS_INFORMATION);//<--------- cbAlloc is too large, exceeding 0x40000000 
    // 2: create and fill result array:
    if(!(pProcInfoAll = VmmDllCore_MemAllocExternal(H, OB_TAG_API_PROCESS_INFORMATION, cbAlloc, cbAlloc))) { goto fail; }
    for(i = 0; i < cPIDs; i++) {
        pe = pProcInfoAll + cProcInfo;
        pe->magic = VMMDLL_PROCESS_INFORMATION_MAGIC;
        pe->wVersion = VMMDLL_PROCESS_INFORMATION_VERSION;
        cbProcInfo = sizeof(VMMDLL_PROCESS_INFORMATION);
        if(VMMDLL_ProcessGetInformation_Impl(H, pdwPIDs[i], pe, &cbProcInfo)) {
            cProcInfo++;
        }
    }
    *pcProcInfo = cProcInfo;
    *ppProcInfoAll = pProcInfoAll;
    LocalFree(pdwPIDs);
    return TRUE;
fail:
    *pcProcInfo = 0;
    *ppProcInfoAll = NULL;
    VmmDllCore_MemFreeExternal(pProcInfoAll);
    LocalFree(pdwPIDs);
    return FALSE;
}

**Comment by ufrisk** [comment]
What do you mean its unavailable? it's in the header file here: https://github.com/ufrisk/MemProcFS/blob/5a50667933c87f542e9bd34f7d438b8603e29bc0/vmm/vmmdll.h#L2280

It's also exported.

Why did you post the internal implementation (which is not exported)?

**Comment by Space-CN-G** [comment]
cbAlloc = cPIDs * sizeof(VMMDLL_PROCESS_INFORMATION); //<--------- cbAlloc 太大，超过 0x40000000
