### ISSUE TITLE
How do I get process pdpt

### ISSUE THREAD

**Issue by zijingsh** [ufrisk/MemProcFS#313]
How do I get process pdpt

**Comment by ufrisk** [comment]
You can have a look here: <https://github.com/ufrisk/MemProcFS/wiki/FS_Process_Virt2Phys> about how to do it with the file system.

If you wish to do it programatically, just read the PML4 and parse the PML4e to find the PDPT I guess.

Also, this github issues section is more for raising issues such as bugs and/or enhancement suggestions.

For general questions joining the discord is a better option.
