### ISSUE TITLE
VMM.dll, System Compatibility Issue?

### ISSUE THREAD

**Issue by derekeiri** [ufrisk/MemProcFS#314]
I've only been able to replicate this on an enterprise Win11 (22631.4037) and Win10 (19045.4780) machines, so I suspect it's environment specific. I can run this on a personal machine with no issues. However, guidance on how to further troubleshoot this on my end is appreciated.

Since v5.11.4, I receive the following error. 

 ---------------------------
MemProcFS.exe - Bad Image
---------------------------
C:\Tools\MemProcFS_files_and_binaries_v5.11.4-win_x64-20240817\VMM.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000007b. 
---------------------------

I can execute v5.11.3.20240730 with no error.

If I take the v5.11.3.20240730 VMM.dll file and replace the v5.11.4 VMM.dll with it to run v5.11.4, the error goes away.

**Comment by ufrisk** [comment]
I don't understand this issue at all. I haven't changed anything at all in the build process or introduced new code that may cause these issues.

Only thing I can come to think about is that Microsoft always updates Visual Studio and I build with the latest version.

I've updated it once again and built a new version. Please let me know if you still have compatibility issues with this one and I'd have to try to look into it closer.
[vmm.zip](https://github.com/user-attachments/files/16950137/vmm.zip)

**Comment by ufrisk** [comment]
I'd say don't waste your time on it.

If you had some issues and no longer have them it must have been related to the Visual Studio versions somehow. I haven't changed anything at all, except building it with a slightly more recent version (updated today).
