### ISSUE TITLE
Cr3 help

### ISSUE THREAD

**Issue by lishaoju** [ufrisk/MemProcFS#315]
> if (Map.Config.State.ErrorSize[0] > 0) {
				LOG("Update environment");
				Dma.Function.UpdateCache(VMMDLL_OPT_REFRESH_FREQ_TLB);
}
Dma.Process.FixCR3();

After fixing CR3, I occasionally encounter problems where some data fails to return results. I need to use VMMDLL_OPT_REFRESH_FREQ_TLB to restore functionality, but using this option causes CR3 to be modified, which requires me to re-fix CR3. This results in an infinite loop where every few seconds there are intervals during which data cannot be retrieved. Is there a way to resolve this issue?

**Comment by dolodi** [comment]
do you mean the freq of which the dtb get refreshed ?

**Comment by lishaoju** [comment]
> do you mean the freq of which the dtb get refreshed ?

It's not working. I'm currently updating every 0.5 seconds, but it's still not having any effect

**Comment by dolodi** [comment]
even if you do every 500ms it will still take 1500 to load progress_percent.txt to 100, so fixcr3 will not finish before 2 seconds~~.
Either you find a way to refresh the dtb.txt without initializing the plugins each time or idk, thats the only slow part in the code dependant on the dma

**Comment by ufrisk** [comment]
I'm closing this issue. I'd prefer if you were to discuss your game hax needs in other places than on my Github. Thanks for understanding.
