### ISSUE TITLE
FTD3XX

### ISSUE THREAD

**Issue by lishaoju** [ufrisk/MemProcFS#317]
Can you tell me where the source code of FTD3XX is open sourced? I need to change the current FTD3XX.dll to lib

**Comment by ufrisk** [comment]
`FTD3XX.dll` is from ftdichip.com

This project merely use their DLL for accessing the FT601 chip.

Please have a look around ftdichip.com to see if you can find your lib file and/or if it's open sourced somehow (last I checked it was not).
