### ISSUE TITLE
Caching pages to stop using Process DTB

### ISSUE THREAD

**Issue by ikeaDev** [ufrisk/MemProcFS#318]
The process im using VMMDLL on is messing with dtb which makes it unaccessable for vmm. I found I can cache pml4 and pdps and use the rest like normal. Since the code of VMMDLL is very large and mostly undocumented, where would I include my custom page cache (I already have the cache done just need to make vmm use it) for translating virutal to physical addresses? I looked through some functions like MmX64_Virt2PhysEx but couldnt figure out how they work.

**Comment by ufrisk** [comment]
This is not supported in the current version.

It's not undocumented. The external API is quite well documented.

But if I were to add something I guess you could add something after the call to LeechCore for reading the physical memory here: https://github.com/ufrisk/MemProcFS/blob/e47352beba608ccb85bac1962239de92e90accd1/vmm/vmm.c#L1420

**Comment by ufrisk** [comment]
I'm closing this issue. Since I haven't heard anything back, I'll assume things are fine.
