### ISSUE TITLE
`VmmProcess` should implement `Copy`

### ISSUE THREAD

**Issue by zacryol** [ufrisk/MemProcFS#319]
https://github.com/ufrisk/MemProcFS/blob/98dd0d4933e1e149ba49ddc58af4202687d7a5fe/vmmrust/memprocfs/src/lib_memprocfs.rs#L1611-L1615

All of this struct's fields are `pub` and implement `Copy`, so there's no real reason to not make it `Copy + Clone` (or at the very least `Clone`).

The lack of these traits doesn't even prevent the user from "copying" it manually, since all fields are `pub`.

**Comment by ufrisk** [comment]
Thanks for the suggestion.

I've added Clone (and Copy to some degree) to a bunch of different structs in 5.11.7.

Let me know if this will do and if the changes are fine.

**Comment by ufrisk** [comment]
I'm closing this issue. Since I haven't heard anything about it, I'll assume things are fine.
