### ISSUE TITLE
The Vmmpyc.pyd file is not working

### ISSUE THREAD

**Issue by teatreee** [ufrisk/MemProcFS#32]
Why is my memprocfs always unable to use the PY API functionality?Put vmmpyc.pyd and vmmpy.py in the same folder.But when you run the command from VMmpy import *.
Display: from VMMPyc Import *
ImportError: DLL Load failed: The specified module cannot be found.

**Comment by ufrisk** [comment]
1. make sure your Python is 64-bit Python and not 32-bit Python (I think the 32-bit one may be the default and that this may be your issue).
2. start python from the MemProcFS folder with all the binaries (dlls and pyd)
3. no capitalization on the imports.

![image](https://user-images.githubusercontent.com/18221464/89097718-a6eeed80-d3e1-11ea-980e-3891cd3813c3.png)

**Comment by ufrisk** [comment]
I looked into this again; it should work on Windows 8.1 or later. It seems like I introduced some symbols in the current release that is not supported on Windows 7 or earlier.

**Comment by ufrisk** [comment]
did you resolve this issue? - i.e. is it okay for me to close this issue?
