### ISSUE TITLE
5.11.7 Vmm Init Error

### ISSUE THREAD

**Issue by imerzan** [ufrisk/MemProcFS#320]
After upgrading from an earlier 5.11.x build (I think 5.11.4) I am getting this error on startup:

```csharp
LeechDMA: Initialized. (v4)
DEVICE: FPGA: DRIVER_SUPPLIED PCIe gen1 x4 [0,0,0] [v4.17,0500] [ASYNC,NORM,FWCUST]
FPGA: TINY PCIe TLP algrithm auto-selected!
[CORE]     Initialization Failed. Unable to locate valid DTB. #2
[CORE]     Unable to auto-identify operating system.
           Specify PageDirectoryBase (DTB/CR3) in -dtb option if value if known.
           If arm64 dump, specify architecture: -arch arm64

[CORE]     Failed to initialize.

[CORE]     SHUTDOWN COMPLETED (00000233802F5040).
[CORE]       TIME: 2024-10-02 14:04:39 UTC.
[CORE]       RUNTIME: 0s.
```

using VmmSharp (latest nuget pkg)

If i switch back to the old vmm/leechcore, it goes away entirely.

**Comment by ufrisk** [comment]
Can you try to update the leechcore_driver.dll as well. For the 2.19 LeechCore version this file was updated as well (I now see I forgot to change the version number on it though, will do), but the leechcore_driver.dll in the package should work.

**Comment by imerzan** [comment]
Yes, that fixed it.
BTW this updated binary doesnt seem to be in the latest MemProcFS binaries, I had to find it in Leechcore repo.

**Comment by ufrisk** [comment]
Oh, I forgot to update the binary packages of MemProcFS with the new files. It's done now. Thanks :)

Nice to see the issue resolved, but I would have expected a good error message if there was a version mis-match between leechcore and the driver, but it seems like that part is somewhat broken.
