### ISSUE TITLE
Initialization of VMM failed 

### ISSUE THREAD

**Issue by teatreee** [ufrisk/MemProcFS#33]
I'm sorry to have taken up so much of your time.However, I still have problems in following your instructions, as shown in Figure 1 and Figure 2.There is also a problem with MemprocFS 'FPGA, which never connects to the FPGA device, as shown in Figure 3.
![question_1](https://user-images.githubusercontent.com/69066433/89119979-e3574200-d4e4-11ea-9a40-93b8970f1456.jpg)
![question_2](https://user-images.githubusercontent.com/69066433/89119983-ebaf7d00-d4e4-11ea-9e6a-5b24d163677c.jpg)
![question_3](https://user-images.githubusercontent.com/69066433/89119985-efdb9a80-d4e4-11ea-9a05-9e2a1aa81175.jpg)

**Comment by ufrisk** [comment]
can you please try, in your python (the -device command argument was missing)

```Python
from vmmpy import *
VmmPy_Initialize(['-device', 'C:\\Test\\Windows7x64.vmem'])
```

Also for the MemProcFS are you able, on a fresh boot, connect to the FPGA device in verbose mode you may see extra info:
`MemProcFS.exe -device fpga -v -vv -mount k`

Please note that you do need to have the FTD3XX.dll file placed alongside MemProcFS for the FPGA to work. But if running in verbose mode it will tell you (hopefully) what the error is.

If it's not working, please try the version I'll release early next week.

**Comment by teatreee** [comment]
Thank you very much. Both problems have been solved.For MemProcFS, the main problem is the FTD3XX. DLL version. The version I used is 12.0.4 and the program needs 13.0.2 or above.I am very interested in your project. I am a beginner and I am not in this research direction, so I do not have the time to study, but the tools you provide are very friendly and convenient for a beginner like me, so I want to use my spare time to learn.For example, perform some memory analysis operations using the Python interface.I watched a video you posted on YouTube. You said the full memory dump is too slow, so how can you dump the memory of a particular process according to the process number?In addition, can you recommend some papers or books on memory analysis or Python API development?I do appreciate it.Thanks so much for your great support!
