### ISSUE TITLE
Other way to list all dtbs?

### ISSUE THREAD

**Issue by maoxian123** [ufrisk/MemProcFS#331]
Is there any other way to list dtbs,include pid=0 or name is null.
`VMMDLL_VfsReadW(hVmm, (LPWSTR)L"\\misc\\procinfo\\dtb.txt",.....) `
This method is a bit troublesome and slow speed.

**Comment by FocuzJS** [comment]
ulf pls fix my eac p2c 🙏🏻 

> Is there any other way to list dtbs,include pid=0 or name is null. `VMMDLL_VfsReadW(hVmm, (LPWSTR)L"\\misc\\procinfo\\dtb.txt",.....) ` This method is a bit troublesome and slow speed.

**Comment by ufrisk** [comment]
yah, I'm not helping that,

besides the approach used in `dtb.txt` for what is meant to render is about as fast as it can theoretically get since it's limited by read performance of the hardware itself...
