### ISSUE TITLE
GetPfnSystem help

### ISSUE THREAD

**Issue by lishaoju** [ufrisk/MemProcFS#332]
When using MmPfn_Map_GetPfnSystem, the execution is extremely slow, and it returns an incorrect list where the PIDs don’t match the process names. For some devices, however, it retrieves the data correctly

**Comment by ufrisk** [comment]
This is very sparse info, it's not enough for me to track down the issue.

On the devices it doesn't retrieve the data correctly, may they perhaps be running some kind of games anti-cheat system?

Anti-Cheats have been known to mess around with this functionality. If this is the case I won't be able to help with this and feel free to close this issue.

If your system does not run an anti-cheat I could take a look. It would be great in that case if you could dump the entire memory of the problematic system (with PCILeech or some other utility, such as DumpIt or WinPmem) and then verify against the memory dump that the error indeed still manifests. If so, I'd be happy to take a look at it. (but as already mentioned, only if this system of yours aren't running an anti-cheat).

**Comment by Cyk-Fad** [comment]
> This is very sparse info, it's not enough for me to track down the issue.
> 
> On the devices it doesn't retrieve the data correctly, may they perhaps be running some kind of games anti-cheat system?
> 
> Anti-Cheats have been known to mess around with this functionality. If this is the case I won't be able to help with this and feel free to close this issue.
> 
> If your system does not run an anti-cheat I could take a look. It would be great in that case if you could dump the entire memory of the problematic system (with PCILeech or some other utility, such as DumpIt or WinPmem) and then verify against the memory dump that the error indeed still manifests. If so, I'd be happy to take a look at it. (but as already mentioned, only if this system of yours aren't running an anti-cheat).

I tested on no anticheat running.Using plugin m_misc_procinfo.c to get procinfo. MmPfn_Map_GetPfnSystem would take about 2 - 3 seconds to get all process info.I want to get process that this.

he line 0046 may indicate a stray DTB at physical address 0x1d91b0000. It is possible to manually try this value against potentially defunct processes by writing to the file dtb.txt in the process root folder (not recommended).

0000      4           1aa000 ffffe5070ee66040 System
0001    172           48c000 ffffe5070eef0080 Registry
0002    796          508a000 ffffe5071d029240 fontdrvhost.ex
0003   6992        10078c000 ffffe5071e9a4080 sihost.exe
0004   6224        102198000 ffffe5071ea0f080 taskhostw.exe
0005   7136        103e31000 ffffe5071e9db080 svchost.exe
0006   5756        105203000 ffffe5071e58b080 rundll32.exe
...
0043  12992        1c51a0000 ffffe50720454080 svchost.exe
0044  10044        1ca823000 ffffe50724fc0080 dllhost.exe
0045   3868        1d316c000 ffffe507217482c0 dllhost.exe
0046      0        1d91b0000                0 ---
0047   9200        1e3d38000 ffffe5071f5240c0 explorer.exe
0048   7044        202cfa000 ffffe50721481340 svchost.exe

I need to fix some process through using line46's DTB.Would u like to help me?

**Comment by Cyk-Fad** [comment]
> > This is very sparse info, it's not enough for me to track down the issue.
> > On the devices it doesn't retrieve the data correctly, may they perhaps be running some kind of games anti-cheat system?
> > Anti-Cheats have been known to mess around with this functionality. If this is the case I won't be able to help with this and feel free to close this issue.
> > If your system does not run an anti-cheat I could take a look. It would be great in that case if you could dump the entire memory of the problematic system (with PCILeech or some other utility, such as DumpIt or WinPmem) and then verify against the memory dump that the error indeed still manifests. If so, I'd be happy to take a look at it. (but as already mentioned, only if this system of yours aren't running an anti-cheat).
> 
> I tested on no anticheat running.Using plugin m_misc_procinfo.c to get procinfo. MmPfn_Map_GetPfnSystem would take about 2 - 3 seconds to get all process info.I want to get process that this.
> 
> he line 0046 may indicate a stray DTB at physical address 0x1d91b0000. It is possible to manually try this value against potentially defunct processes by writing to the file dtb.txt in the process root folder (not recommended).
> 
> 0000 4 1aa000 ffffe5070ee66040 System 0001 172 48c000 ffffe5070eef0080 Registry 0002 796 508a000 ffffe5071d029240 fontdrvhost.ex 0003 6992 10078c000 ffffe5071e9a4080 sihost.exe 0004 6224 102198000 ffffe5071ea0f080 taskhostw.exe 0005 7136 103e31000 ffffe5071e9db080 svchost.exe 0006 5756 105203000 ffffe5071e58b080 rundll32.exe ... 0043 12992 1c51a0000 ffffe50720454080 svchost.exe 0044 10044 1ca823000 ffffe50724fc0080 dllhost.exe 0045 3868 1d316c000 ffffe507217482c0 dllhost.exe 0046 0 1d91b0000 0 --- 0047 9200 1e3d38000 ffffe5071f5240c0 explorer.exe 0048 7044 202cfa000 ffffe50721481340 svchost.exe
> 
> I need to fix some process through using line46's DTB.Would u like to help me?

In most situations,2 - 3 seconds is ok.But I'm developing a function that needs lower time to do this. ONLY FOR DTB like line46.
Could u plz make a function to getting these DTBs?

**Comment by ufrisk** [comment]
This relies on dumping the entire PFN database and analyzing it.

The PFN database is of size = Total RAM / 85. For a 16GB system this will give approx: 16,000,000,000 / 85 = 200,000,000 = 200MB. Double the memory and double the PFN database. 

There is no really way around this fact with the current algorithm in use. It's not possible to optimize it further. If it's problematically slow only current option is to get a ZDMA board.

**Comment by ufrisk** [comment]
I'm closing this issue since it's been thoroughly answered. Maybe you'll find some other alternative solution. Best wishes with your projects.

**Comment by ufrisk** [comment]
I'm closing this issue since there is not really anything I can do to improve upon the current algorithm as it works now.
