### ISSUE TITLE
Force update DTB.txt?

### ISSUE THREAD

**Issue by Lynnette177** [ufrisk/MemProcFS#337]
I'm caching pml4 right now. But when I'm using cached table, although the target process has moved its PML4, dtb.txt seems not to be updated, "progress_percent.txt" seems always to be 100%. 
When I clear my cache, it will update again. 
Is there anyway to force the file to update?
Thanks for your reply in advance.

**Comment by ufrisk** [comment]
If you use the API use `SLOW` refresh to trigger an update. More info here: https://github.com/ufrisk/MemProcFS/wiki/FAQ_Timing

The issues section of this project isn't the best place to ask general questions though, it's better to do that on the project Discord server.
