### ISSUE TITLE
VmmWinInit_TryInitialize_SystemUniqueTag possible bug?

### ISSUE THREAD

**Issue by Frostchi** [ufrisk/MemProcFS#341]
https://github.com/ufrisk/MemProcFS/blob/fddcad73f76c10eeb660d3095edaf47a13b995bf/vmm/vmmwininit.c#L1169

Is this meant to be a PDWORD? It's an array of 32 bytes with the address of it being casted to a DWORD?

**Comment by ufrisk** [comment]
First 4 bytes of the SHA256 hash is assigned to the DWORD. It's only mean to be some quick check of an unique id to the system, it's mostly useful when using eleasticsearch to import multiple memory dumps. It's correct as-is.
