### ISSUE TITLE
memprocfs says failed to connect to memory acquisition device

### ISSUE THREAD

**Issue by Keynesian111** [ufrisk/MemProcFS#348]
recently i changed to a new second pc with usb 3.2 gen1/gen2, and i am unable to connect to memprocfs regardless of what i did.

i could run dmatest application fine and it would show speed but whenever i ran the command MemProcFS.exe -device fpga -memmap auto it says failed to connect.
MemProcFS.exe -device fpga -memmap auto

my main computer is AMD, new second pc is also AMD if that helps.

**Comment by Keynesian111** [comment]
fixed, installed dokan.

**Comment by ufrisk** [comment]
It's super nice to see the issue is resolved. Good luck with your DMA memory analysis!
