### ISSUE TITLE
Unable to locate ntoskrnl.exe

### ISSUE THREAD

**Issue by KenionX** [ufrisk/MemProcFS#35]
I just updated everything to LeechCore v2.0.2

however on the new version it wont find ntoskrnl.exe (it worked fine on the old release)
DEVICE: FPGA: ScreamerM2 PCIe gen2 x1 [300,0,500] [v4.6,0500]
X570 asus chipset
Winver: 1909 Build 18363.959

FPGA: TINY PCIe TLP algrithm auto-selected!
LcMemMap_AddRange: 0000000000000000-000000000009ffff -> 0000000000000000
LcMemMap_AddRange: 0000000000100000-000000081f37ffff -> 0000000000100000
LeechCore v2.0.2: Open Device: fpga
VmmWinInit_TryInitialize: INFO: DTB  located at: 00000000001ad000. MemoryModel: X64
VmmWinInit_TryInitialize: Initialization Failed. Unable to locate ntoskrnl.exe. #3

**Comment by ufrisk** [comment]
Thank you for reporting this.

I have noted a similar issue when using the tiny algorithm. I'll be looking into this but it may take some time before I'll be able to unfortunately.

**Comment by sheeets** [comment]
@KenionX Did you ever get this resolved? I’m getting the same error and pretty confident now it’s a hardware error.

**Comment by Boreo** [comment]
Seems to be a problem with some mobos, I also have x570 asus chipset which is getting the same error.

**Comment by KenionX** [comment]
@sheeets Iam 100% sure its not an hardware error, I have 2 pcs, with the exactly same issue. It might be related to 32gb memory? maybe its not proper reading bars on that.

However it works 100% all the time on the older memprocFs / leechcore for me.

**Comment by sheeets** [comment]
What version of MemProcFS does it work for you? I tried mine in a buddies computer that was working fine and I got the error, which is why I’m convinced it’s hardware related.

**Comment by ufrisk** [comment]
I just pushed a fix that affected the tiny algorithm that caused data corruption in rare occurrences. Can you please check if the latest binaries resolves your issue and report back how it goes?

**Comment by KenionX** [comment]
@ufrisk thx you so much!!! It works flawless now :)

**Comment by ufrisk** [comment]
Thank You for confirming it's fixed. This was a bad issue and also hard to find. I'm also very happy it's fixed.

---

Also, if you should find PCILeech / MemProcFS useful please consider sponsoring the project here on Github. I see people purchasing hardware for hundreds of dollars (of which I receive absolutely zero dollars of) just to be able to run my free open source software. Sponsorships go for as little as $2 and Github is matching it - a $2 sponsorship for you is a $4 sponsorship for me. Thank You 💖
