### ISSUE TITLE
How do I use MemProcFS to write custom rules to retrieve memory based on a particular string or sequence of bytes?

### ISSUE THREAD

**Issue by teatreee** [ufrisk/MemProcFS#37]
Thank you very much for your reply and guidance!The error in version 3.3 is due to the use of windows 7 system, which can be used normally now.I have placed an order on Amazon for the books you recommended, and I will step up my study later.For dumping memory based on a specific process number, I intended to write custom rules to retrieve memory based on a specific string or sequence of bytes, but because of the entire memory dump, the file size was too large.I have carefully checked the vmmpy_example.py file and found no module to implement this function. Do you have any good Suggestions?Or can I try to write a program based on the Python API you provide?

**Comment by ufrisk** [comment]
If you're thinking about the virtual memory file / virtual memory space; yes it's going to be too large. It's huge.

There is no way to retrieve memory based on a specific signature. You'll have to read memory and scan the contents of it using your own code.

One way to approach this may be to retrieve the active memory segments in virtual memory - the VADs. This can be retrieved with the call to `VmmPy_ProcessGetVadMap`.

When you know what the addresses and sizes and a little about what the memory is related to you may read that using `VmmPy_MemRead` or `VmmPy_MemReadScatter`

**Comment by ufrisk** [comment]
Way way long over due. I have some time ago added a search capability to MemProcFS to the file system and its C/C++ API.

If there is any interest I could port it over to Python as well.

I'm closing this issue since it's now finally implemented.

**Comment by FlameSky-S** [comment]
Hi, ufrisk.  Have you ported the `VMMDLL_MemSearch` and `VMMDLL_YaraSearch` functions to Python?

**Comment by ufrisk** [comment]
@FlameSky-S It's not added currently. I'll look into adding it next week when I'm back home.

**Comment by ufrisk** [comment]
@FlameSky-S This was added in the most recent MemProcFS update (v5.7). Please let me know how it works for you.

There are some examples in the [example file](https://github.com/ufrisk/MemProcFS/blob/4b5c7754a109f9b8ab22fda7d8257c9944e5846d/files/memprocfs_example.py#L343) and also documentation in the [wiki](https://github.com/ufrisk/MemProcFS/wiki/API_Python_Search)
