### ISSUE TITLE
syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	

### ISSUE THREAD

**Issue by johnjohnsp1** [ufrisk/MemProcFS#39]
Hello,
i'm trying to compile the new release of memproc but getting few errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.c	335	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.c	335	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.c	335	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.c	335	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.c	335	
Error	C2449	found '{' at file scope (missing function header?)	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.c	336	
Error	C2059	syntax error: '}'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.c	413	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm	C:\temp\MemProcFS-3.4\vmm\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	m_vmemd	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	m_vmemd	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	m_vmemd	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2059	syntax error: ';'	m_vmemd	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2059	syntax error: ')'	m_vmemd	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmmpyc	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmmpyc	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmmpyc	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmmpyc	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmmpyc	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	MemProcFS	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	MemProcFS	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	MemProcFS	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2059	syntax error: ';'	MemProcFS	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2059	syntax error: ')'	MemProcFS	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	MemProcFS	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	MemProcFS	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	MemProcFS	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2059	syntax error: ';'	MemProcFS	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2059	syntax error: ')'	MemProcFS	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmmpycplugin	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmmpycplugin	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmmpycplugin	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmmpycplugin	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmmpycplugin	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2146	syntax error: missing ')' before identifier 'ppLcErrorInfo'	vmm_example	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2081	'PPLC_CONFIG_ERRORINFO': name in formal parameter list illegal	vmm_example	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2061	syntax error: identifier 'ppLcErrorInfo'	vmm_example	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2059	syntax error: ';'	vmm_example	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	
Error	C2059	syntax error: ')'	vmm_example	C:\temp\MemProcFS-3.4\includes\vmmdll.h	77	

using latest release of Vstudio2019 with a windows 10 version 2004 (OSBuild 19041.450)
Microsoft Visual Studio Enterprise 2019
Version 16.7.2
VisualStudio.16.Release/16.7.2+30413.136
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00433-90000-00004-AA023
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

C# Tools   3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.7.20181.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Dotfuscator Community Edition   5.42.0.9514-e0e25f754
PreEmptive Protection - Dotfuscator CE

GitHub.VisualStudio   2.11.104.25275
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.7.20181.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.7.20181.2
Conda support for Python projects.

Python - Django support   16.7.20181.2
Provides templates and integration for the Django web framework.

Python - IronPython support   16.7.20181.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.7.20181.2
Profiling support for Python projects.

SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

anything i miss or do wrong ?
had no problem with the version 3.3

thanks

**Comment by ufrisk** [comment]
hrm, I tried to compile on a separate computer with visual studio; both the 3.4 zip and main/latest works with me without error.

I did a `git clone https://github.com/ufrisk/MemProcFS`
and then open the solution in Visual Studio and compiled it. can you please try this approach to see if it works?

**Comment by johnjohnsp1** [comment]
thanks for teh fast reply, i did try your same method, did a git clone https://github.com/ufrisk/MemProcFS, opened the folder MemProcFS, right click on memprocfs.sln then Vstudio opened and builded:

![image](https://user-images.githubusercontent.com/1888855/91743891-d9def980-ebb8-11ea-80af-217b2ba80d2f.png)

but sadly i keep getting the same error.
no idea why

**Comment by johnjohnsp1** [comment]
i did try a test the previous version 3.3 and everything went fine:

![image](https://user-images.githubusercontent.com/1888855/91749316-950b9080-ebc1-11ea-9d79-53d61dbaf0c3.png)

no idea really but i did the same step

**Comment by ufrisk** [comment]
I have on a fresh install fully updated windows 10 2004 release:
 - Downloaded and installed visual studio community edition with Python, .NET Desktop and C++ Desktop features installed.
 - Rebooted after install.
 - Downloaded MemProcFS 3.4 binaries from release (I would suggest getting main/latest clone though due to some small unrelated bug fixes.
 - opened MemProcFS.sln
 - compiled both release x64 and debug x64 without any error at all.

I develop on enterprise version, which I see you're also using; but for this test I installed community since it's free and probably easier to download. I don't think this should matter though.

**Comment by johnjohnsp1** [comment]
thanks again for the fast answer, actually tried once more to git clone the repo at https://github.com/ufrisk/MemProcFs , opened with VStudio and compiled both (debug & release) without any errors:

![image](https://user-images.githubusercontent.com/1888855/91755775-f6386180-ebcb-11ea-8829-7fc260e30875.png)

all went fine .. no error so far, i really don't know what's changed from the previuos attempt.
Thanks for the patience so far and apologize if i did anything wrong

**Comment by ufrisk** [comment]
Awesome. I hope you do find your use for my project. Please let me know if you should bump into some bugs or if you have any enhancement suggestions about missing features you would like to see implemented.

---

Also, if you should find PCILeech / MemProcFS useful please consider sponsoring the project here on Github. I see people purchasing hardware for hundreds of dollars (of which I receive absolutely zero dollars of) just to be able to run my free open source software. Sponsorships go for as little as $2 and Github is matching it - a $2 sponsorship for you is a $4 sponsorship for me. Thank You 💖
