### ISSUE TITLE
Saving/Loading memory maps

### ISSUE THREAD

**Issue by njbrown09** [ufrisk/MemProcFS#42]
How do we save/load memory maps via vmm.dll? Trying to prevent master aborts.

**Comment by ufrisk** [comment]
in initialize call add two entries to argv, i.e. `-memmap` and `<filename_of_memmap>`

**Comment by njbrown09** [comment]
Yes but how do we save? It just gives a file error.

**Comment by ufrisk** [comment]
what do you mean with save? just save it as any kind of text file to any drive on your computer?

example: save this below to a text file `memmap.txt`
```
     1000 -        9cfff
   100000 -       101fff
   103000 -     ad137fff
100000000 -    43e5fffff
```

**Comment by ufrisk** [comment]
I had a but in the memory map parsing causing some memory maps to fail loading. I made a small change so if you download the latest version it should work hopefully; please let me know otherwise. I'm closing this issue since it should now be resolved.

**Comment by njbrown09** [comment]
Yes but how do we have it save a memory map. I need to be able to have the library save the memmap and load it. Manually making a text file will not work in my case.

**Comment by njbrown09** [comment]
Essentially if the file doesnt exist, generate a memory map and save it.

**Comment by ufrisk** [comment]
two options:

1) Retrieve and iterate over `VMMDLL_MAP_PHYSMEM` by calling `VMMDLL_Map_GetPhysMem()` to generate it yourself.

2) Read it from the file system programatically by calling:
  2.1. `VMMDLL_InitializePlugins()` - to initialize plugin sub-system (required by VfsRead) unless already done.
  2.2. `VMMDLL_VfsRead()` on file `/sysinfo/memory/physmemmap.txt`

**Comment by ufrisk** [comment]
also, to load the memory map, you may specify it as a parameter to a file at startup;

or, after startup (if possible in your use case) to load it into the LeechCore by calling `LcCommand()` with `LC_CMD_MEMMAP_SET` and a buffer with your memory map contents.
