### ISSUE TITLE
This line may cause the array to be out of bounds？

### ISSUE THREAD

**Issue by N1neSun** [ufrisk/MemProcFS#44]
https://github.com/ufrisk/MemProcFS/blob/065a25d2a43237b6671abf8897b675d62e890f8b/vmm/mm_win.c#L525

**Comment by ufrisk** [comment]
Thanks. It's a out of bound read. I'll fix it. I wonder why the visual studio code analysis didn't catch it.

It's a stack based read buffer overrun; and the erroneous result will be bad "candidate pointers" of data. I don't see how this should have any stability- or security implications. But nevertheless it's bad code and I'll fix it in next release.

Thank you for reporting :)

**Comment by ufrisk** [comment]
This should now be fixed. Thank you for reporting. Please let me know if you should happen to run into any more issues.
