### ISSUE TITLE
Make paths compatible with common procfs conventions

### ISSUE THREAD

**Issue by BenBE** [ufrisk/MemProcFS#46]
It would be nice if MemProcFS could be mounted in a way that looks and behaves like a procfs normally found on unixoid systems.

Represented features might include:
- `/proc/<pid>` for process directories
- `/proc/<pid>/maps` for the memory map
- `/proc/<pid>/fd/` for the list of handles
- `/proc/<pid>/cmdline` for the command line
- `/proc/<pid>/exe` for the executable being run
…

More information can be found [in the Linux Kernel documentation](https://www.kernel.org/doc/html/latest/filesystems/proc.html).

**Comment by ufrisk** [comment]
Thanks for the suggestion :) 

I've thought about this myself in the past, but I kind of forgot about it. It would be quite easy for me to rename the "pid" directory to "proc"; on the other hand it's quite easy to use as-is now as well.

I guess it would be quite easy for me to rename some files I already have in the process directories to "exe", "mem", "cwd" and such. Memory maps and things like file descriptors would be harder or even infeasible to fully align.

It's a good suggestion and I'll put it up as an enhancement. I'll look into it and I'll likely change some things around to partially align with the /proc-fs

**Comment by ufrisk** [comment]
Hi,

I'm closing this issue since my project have due to requirements from other people taken a slightly different direction. Basically there has been a demand to dumb things down a bit and make files more easily clickable (hence the added .txt file endings recently) and more similar things around this - which to some degree goes against this.

**Comment by BenBE** [comment]
Understandable. Although having the "dump" vs."posix" names an option shouldn't introduce too much additional work.
