### ISSUE TITLE
This version not support windows 10.0.18363?

### ISSUE THREAD

**Issue by N1neSun** [ufrisk/MemProcFS#47]
This version not support windows 10.0.18363?

**Comment by ufrisk** [comment]
It should support 1909/18363. Are you having problems?

**Comment by N1neSun** [comment]
I create a version 18363 in my vmware ，but it can't use.

**Comment by ufrisk** [comment]
how do you access the memory?

do you create a memory dump with dumpit, copy the .vmem+vmss/vmsn memory save files when the vm is saved or are you accessing live memory with MemProcFS inside the VM with dumpit or winpmem?

**Comment by N1neSun** [comment]
I copied the .vmem memory

**Comment by ufrisk** [comment]
next to the .vmem memory file you may have a file with the same name ending with .vmss or .vmsn which may contain metadata needed. can you try copy the .vmss or .vmsn file and place it alongside the .vmem file and try again?

**Comment by N1neSun** [comment]
it works, thanks a lot.
