### ISSUE TITLE
Can't read with VmmPy_VfsRead

### ISSUE THREAD

**Issue by ittaidayagi** [ufrisk/MemProcFS#49]
Hi,

I try to use the Python API and for some reason I can't read with the VmmPy_VfsRead.
I try to use exactly the same command line as the example: VmmPy_UtilFillHexAscii(VmmPy_VfsRead('/memory.pmem', 0x100, 0x1000)), and it gives me the error "RuntimeError: VMMPYC_VfsRead: Failed".

**Comment by ufrisk** [comment]
Have you successfully run `VmmPy_Initialize` and `VmmPy_Initialize_Plugins` prior to `VmmPy_VfsRead`?

**Comment by ittaidayagi** [comment]
I didn't run VmmPy_Initialize_Plugins, and now it's working! 
Thank you very much

**Comment by ufrisk** [comment]
awesome :) I see that I need to clarify my examples a bit.

Good Luck with your MemProcFS memory forensics and analysis. Please let me know if you feel something is missing or if you have any more questions.
