### ISSUE TITLE
VMMDLL_MemReadScatter question

### ISSUE THREAD

**Issue by fisherwise** [ufrisk/MemProcFS#55]
Hi,

I've been using this function and come across the comment ```Reads must start at even DWORDs (4-bytes).```. 
What does this mean?

**Comment by ufrisk** [comment]
apologies for the rather slow answer. It means that a memory read must start at even 4-byte addresses; ie. addresses of:
0x1000, 0x1004, 0x1008 are ok whilst 0x1001, 0x1006, 0x1007 and so on aren't.

btw, did you get it to work?
