### ISSUE TITLE
VMMDLL_MemReadScatter fails on address ending 0x800

### ISSUE THREAD

**Issue by fisherwise** [ufrisk/MemProcFS#56]
Hi,

I'm trying to read an array of addresses of 2 types, one ending with 0x000 (ex. 0x1000) and another one ending 0x800(ex. 0x1800). All the 0x000 ones succeeds and all the 0x800 ones failed. I'm reading 0x500 from the addresses, so it should align with all the requirements in the function comments.

**Comment by ufrisk** [comment]
Thanks for reporting this; it's supposed to work so I'll look into this. I've been a bit busy elsewhere though but I hope to look into this next weekend :) Meanwhile the workaround is to read 0xD00 or 0x1000 bytes from offset 0x000.

**Comment by fisherwise** [comment]
Just did some test and figured it does not related to endings of an address. a normal address (e.g. ```23ff9dcd00```) can still fail. I tried to follow to Device_FPGA and apparantly it simply fails.
A new theory maybe any address not ending with ```000`` would fail. I'll check that and report back

**Comment by ufrisk** [comment]
0x1000 sized reads aligned to 0x1000 boundaries should not fail. I'll look into the others a bit more this weekend. Please let me know if you should find out anything more :)

**Comment by fisherwise** [comment]
I tried to follow it in debugger and got to [DeviceFPGA_ReadScatter L#1871](https://github.com/ufrisk/LeechCore/blob/e31a5084e264b4ab3c21238a95f703e994ec3384/leechcore/device_fpga.c#L1872) where some of the vStack returned are 0 resulting pMEM-f to be false

**Comment by ufrisk** [comment]
that means there was nothing read; probably due to the error. I'll look into this. Meanwhile please read whole pages only.

**Comment by fisherwise** [comment]
thanks. was reading at the start of page but not with 0x1000 size. looks like there's less failure if I'm reading from the start of page and read the whole page.

**Comment by ufrisk** [comment]
Awesome that you got it to work :) The full page reads should work better. That code path is really well tested - it's what's used internally. I'll try to look into the other cases soon though. But for your use cases I think this, while a bit overly complicated, should be fine. There is very little performance overhead in reading full pages compared to tiny parts of it.

**Comment by ufrisk** [comment]
I'm closing the issue since it should be fixed? If not, please let me know.
