### ISSUE TITLE
incomplete array type LPSTR

### ISSUE THREAD

**Issue by aDioS786** [ufrisk/MemProcFS#59]
Hi,
Am trying to use vmm_Example and surely something silly I am doing. Project is cpp and when I'm trying to use 
result = VMMDLL_Initialize(3, (LPSTR[]) { "", "-device", "fpga" });

//LPSTR[] keep moaning about not allowed 

Not sure what simple thing am missing here.

**Comment by ufrisk** [comment]
not sure; are you using visual studio 2019?

`VMMDLL_Initialize(3, (LPSTR[]) { "", "-device", "fpga" });` should be working; if it's not try (LPSTR*) or something like that instead and maybe the warnings will go away?

**Comment by aDioS786** [comment]
yes using VS 2019

**Comment by ufrisk** [comment]
can't you just define it before then?
LPSTR psz[3] = { "", "-device", "fpga" };
VMMDLL_Initialize(3, psz);

**Comment by aDioS786** [comment]
tried that already, gets value of type "const char*" cannot be used to initialize entity of type LPSTR.

**Comment by ufrisk** [comment]
the use
LPCSTR psz[3] = { "", "-device", "fpga" };

**Comment by aDioS786** [comment]
This worked
LPCSTR psz[5] = { "", "-device", "fpga" };
result = VMMDLL_Initialize(3, (LPSTR*)psz);

Now i am getting true back for  FPGA, but at end of code execution after main block finish, I am getting this error from exe_common.inl

if (!has_cctor) _cexit  error "Exception thrown at 0x00007FFEE95E5E65 (ntdll.dll) in FPGATest.exe: 0xC0000005: Access violation reading location 0x0000000000000010."

**Comment by ufrisk** [comment]
I'm glad this resolved itself.

I don't know why your compiler is so over-zealous though. Also I have no clue about the access violation. Should you find a place in my code that causes it please let me know. But I'm not really able to debug your code for you and/or help with coding issues unfortunately this just being a hobby project of mine with very few backers.

I wish you the best of luck with this though; and please let me know if you should run into a bug that you're able to reproduce/pinpoint.

**Comment by aDioS786** [comment]
I agree, many thanks for your help, I'll update once I found why it might be causing it.
