### ISSUE TITLE
VmmPy_ProcessGetSections Gives Incorrect Names

### ISSUE THREAD

**Issue by charlie-paradigm** [ufrisk/MemProcFS#60]
The method is supposed to return the named sections, but only returns the name of the module it is called with.

The examples shows calling:
`VmmPy_ProcessGetSections(332, "cmd.exe") --> [{ [...] 'Name': '.text', [...]}]`

https://github.com/ufrisk/MemProcFS/blob/6476149d991f2c2111407c431ade6f23f931b70e/files/vmmpy.py#L558-L569

However, when I call this function with `cmd.exe` or any other module, the module argument is returned for the section name:
`VmmPy_ProcessGetSections(XXX, "YYY.exe") --> [{ [...] 'Name': 'YYY.exe', [...]}]`

It seems like this could stem from the vmmpyc method initializing `szName` from `pe->Name` but never using it  -- instead, `pyUnicodeModule` is inserted, which seems to just be the module name argument?
https://github.com/ufrisk/MemProcFS/blob/6476149d991f2c2111407c431ade6f23f931b70e/vmmpyc/vmmpyc.c#L1163-L1164

**Comment by ufrisk** [comment]
Thanks, good catch :)

Are you able to change this yourself until I fix it, or do you wish me to push a fix later this eavning?

I'm in the midst of a big python re-write to make it more pythonic and also to better allow me to put it up on python pip later this month. It's still in the early stages so it's going to be 2-3 weeks from now. Most info-structures like this one will stay the same though - so it will be familiar; but I'll introduce the notation of custom types with process objects and such.

**Comment by ufrisk** [comment]
I made a total remake of the Python API to make it less c-like and more python-ish. Also put it up on Python pip.

This means a lot of things have changed. I have also fixed this bug though. Many thanks for reporting. And please check out the new API.
