### ISSUE TITLE
VMMDLL_Map_GetVad always return 0x1000 vads and missing entries

### ISSUE THREAD

**Issue by fisherwise** [ufrisk/MemProcFS#61]
I tried to use VMMDLL_Map_GetVad with pcileech(fpga) and I figured it always returns exactly 0x1000 entries and is missing some entries (comparing to process hacker results on target machine). Wondering what's causing it.

**Comment by ufrisk** [comment]
That is a very large amount of VADs.

I had a sanity check in my code that maxed it at 0x1000 VADs. Just don't want to allocate memory for millions of VADs if I should happen to read the wrong value from _EPROCESS.

I have upped this value to 0x10000 in next release which will be released next week. Will this be sufficient for you?

**Comment by ufrisk** [comment]
This should now be fixed in the v3.9 release. I uppled the limit to 0x10000 (65k) VADs. Please let me know if you still run into errors.
