### ISSUE TITLE
Finding pointers and offsets using DMA

### ISSUE THREAD

**Issue by AcTiViSioN911** [ufrisk/MemProcFS#63]
Hello. I have some questions, and I don't even know who else to ask besides you. I am writing a program like Cheat Engine for personal use, using MemProcFS with Dokany. A person wrote about the [same thing here](https://github.com/ufrisk/MemProcFS/issues/22). However I am interested in finding pointers and offsets. As I understand it, no one has yet implemented this functionality? I do not have enough knowledge on how to do this. I took the Terraria game and using the Cheat Engine I was able to find pointers, however, there was not a single static one, and everything starts with THREADSTACK0 ([in short here](https://forum.cheatengine.org/viewtopic.php?p=5487976#5487976)) but I did not understand how to work with this only using DMA. Therefore, I would like to ask you for some hint how it is possible to find pointers with offsets? Perhaps I missed something and everything is easier than it seems to me. Perhaps I will be able to find the patterns with which the addresses I need begin with, but for now it looks too complicated and I want to make sure that there is no other way.

**Comment by ufrisk** [comment]
I'm not going to help you to cheat. I created this software with other purposes in mind. Even tho it's totally fine with me if it's used for cheats as well I have a policy of staying away from it.

With that being said you have various kinds of info about the threads as the TEB and the stack locations for each individual thread both in the file system and the API though. I don't have stack analysis (other than displaying where they are located in memory and displaying them as files in the virtual file system).

If you should find a bug in my software or if you are missing some easy to add features please let me know and I'll do my best to fix it. Best wishes with your project :)

**Comment by AcTiViSioN911** [comment]
Thanks for the answer! Cheating sounds too strong for my needs :)
I have a couple of questions. I don't quite understand the difference between virtual and physical memory, why do I find more addresses when scanning virtual memory? I am not doing any filtering.

vad
Read memory: 0m 10s 422ms
Scan memory: 0m 6s 613ms
Found: 3296

pte
Read memory: 0m 15s 572ms
Scan memory: 0m 6s 273ms
Found: 3169

I am using your vmmsharp. As for the filtering, it seemed to me unfinished, I manually compiled the following table:
// vad.Protection: 1 = *-r---, 4 = *-rw--, 6 = *-rwx-, 7 = *--wxc, 24 = *-----, 28 = *mrw--
Perhaps I did not understand something, but I wish it were out of the box :)
Regarding vad / pte, after receiving the data array, I go through each, but then I ran into the following: everything is quite simple for vad, I have vaStart and vaEnd, by simple subtraction I get the size. But pte lacks End and I have to calculate it using the formula "(uint) pte.cPages * 4096 - 1" and it looks unfinished too. It would be convenient to have a Size for both.
In any case, thanks for your work, without it I would not even try to do this.

**Comment by ufrisk** [comment]
About virtual memory vs physical memory it's a big topic way too big to explain in a github issue. There are pretty good resources around this if you google it tho.

Thanks for the suggestion; I have added the requested fields to the vmmsharp to the main/latest https://github.com/ufrisk/MemProcFS/blob/master/vmmsharp/vmmsharp.cs. If you find anything else that you feel could be improved upon in the C# API please let me know. I'm not using it myself so I kinda miss out on these things that could be improved upon.

If you find the project useful please consider [sponsoring my project](https://github.com/sponsors/ufrisk) here on Github for as little as $2. Github is doubling all sponsorships so it's a good deal. Thank you 💖

**Comment by AcTiViSioN911** [comment]
Hello. I don't know how to contact you, I just wanted to tell you a fun fact about Windows. My project worked fine on an old computer. Yesterday I put together a new computer and installed Windows. I speak Russian, so the main language of Windows was Russian. And imagine what my surprise was that my project no longer works. I realized that the reason for this is the language, when I tried to find a number that is exactly present in memory, and HxD gave me the phrase "111.222" is not a floating point number. I've encountered a similar problem in the past, and even websites crashed when trying to process a dotted number. Perhaps it is worth mentioning this somewhere?

**Comment by ufrisk** [comment]
Hi, you can drop me a note at pcileech@frizk.net if you wish as well; or reach out to me on Discord. Huge thanks for the sponsorship btw :)

To be honest I haven't tested MemProcFS much on other systems than English; I should really be trying to test it on Russian and Chinese as well. It should use unicode chars internally though; either as wide-char or utf-8 so there is no technical reason why it should not work. It may very well be that I missed something somewhere though.

This error if yours, have you been able to determine that it's MemProcFS or its API that is failing; or is it your project you are building on-top of it that is having issues?

**Comment by AcTiViSioN911** [comment]
I don’t understand what’s wrong. I did several reboots and everything works, now even in Russian HxD shows the correct float and does not give errors. It means that there was a defect in my windows before installing the English language pack. It was a clean build from the official website without any changes, just installed VS and dependencies...

**Comment by ufrisk** [comment]
I'll add checking out MemProcFS with Russian/Chinese languages to my todo-list. I don't have the MSDN images for those right now though and my access expired a while ago so it may take a while before doing this. If you're able to do a memory dump that triggers the error and that you're able to share I'll be able to look into it as well. But regardless thanks for the the report. This is somemthing I should have tested a long time ago myself...
