### ISSUE TITLE
files/handles only available in pre-compiled binaries but not when compiled in source code

### ISSUE THREAD

**Issue by ALim95** [ufrisk/MemProcFS#71]
hi there,

while running memprocfs using the pre-compiled version 4.1, I am able to view files/handles of the various processes such as winword.exe and see file reconstruction of my word file.

however, when i compile it myself using the source code and visual studio 2019, the files/handles is empty.  I believe it is initialised properly as i traced the code and M_FileHandlesVads_Initialize function in m_files_handles_vads.c is being called.

Would anybody happen to know whats the issue? Many thanks.

**Comment by ufrisk** [comment]
Hi,

My best guess is that you're missing debug symbols. On Windows it will try to download symbols from the Microsoft symbol server if you place the Microsoft `symsrv.dll` and `dbghelp.dll` alongside MemProcFS.

As a fallback (on Windows) and as primary on Linux it will try to lookup bundled cached symbols. For this to happen you'll need to place info.db alongside the MemProcFS binary.

Please let me know if this resolves your issue.

**Comment by ALim95** [comment]
hi there,

thanks so much for the speedy reply.

you are absolutely right! it is finally working after i place all three files alongside MemProcFS.exe.

**Comment by ALim95** [comment]
i will close the issue since it has been resolve, thanks once again

**Comment by ufrisk** [comment]
Awesome and best wishes with MemProcFS :) Please let me know if you should run into something else or wish for new/improved features.
