### ISSUE TITLE
Scatter Read is great only for single thread!

### ISSUE THREAD

**Issue by unknownpk** [ufrisk/MemProcFS#73]
iv been using scatter read etc made my own function to handle the alignment and writing etc BUT iv got 2 threads if 1 thread is using scatter read then my second thread has to wait until thread 1 is finished using scatter read which is very slow could you maybe explain why? or a fix? i really do need 2 threads using scatter read because it really is faster but right now its not :(

**Comment by ufrisk** [comment]
Accesses towards the hardware device are as you noticed serialized behind a lock. Running two threads with continuous reads will only be very marginally faster than running just one thread.

It would be a major job changing this behavior. For smaller reads (10 pages/thread read call) I guess it should be possible in theory. For larger reads 20+ pages/thread there would still have to be as-is. But it's just a very big job so it's unfortunately not very likely that I'll change it in the near future.

**Comment by unknownpk** [comment]
thanks so much for replying i know your busy :) but is the lock on the device? or the MemProcFS? because i see when grabbing the process data you enter and exit a lock? if this is the lock then would it not be possible to store the process data into a global variable and use it that way? and not grab it over and over again per call? thanks

**Comment by ufrisk** [comment]
There are several locks in the code path; all but one should be very short lived though and hopefully won't cause issues.

The main lock I was talking about is on the device itself though. (LeechCore.h!LC_CONTEXT.Lock).

It's strange that the other functions are working so well while the scatter is not though. Are you by any chance making use of the cache in the normal read functions while not in the Scatter functions (you'd need to be reading whole 4096-byte pages to activate the cache with the scatter).

Anyway; if you should fine the culprit why your scatter reads are slower than your normal reads please let me know. That should absolutely not be the case. The normal read functions is using the scatter read in the background. But access to the device itself is serialized behind a lock unfortunately.

**Comment by unknownpk** [comment]
ok let me explain so you understand alittle bit better i have addresses to read around 1000 maybe more or less so i dont read ALL at once with scatter i read around 50 - 100 at once and loop till iv done all 1000 but AS im reading the 1000 addresses i save them into an array then use another thread to use scatter read on the valid or addresses i want and when reading the BIG address list it taking around 100 ms to 500ms depending on size etc BUT when its doing the reading part my other thread TRYS to read but takes EXTACTLY the same ammount of time as the 500ms but when using memreadex it is not it takes 50ms to 100ms AT MOST and im using flags VMMDLL_FLAG_NOCACHE | VMMDLL_FLAG_NOPAGING | VMMDLL_FLAG_NOCACHEPUT | VMMDLL_FLAG_ZEROPAD_ON_FAIL and im setting the right addresses etc making sure there in 0x1000 alignment like 0x1000,0x2000,0x3000 etc etc

**Comment by ufrisk** [comment]
this is a bit strange since the normal read functions use the scatter read in the background. the device lock I won't be able to much about; but if there are other slowdowns it should be fixed.

Would you be able to share a small test program (small source code sample) that triggers this bug on a common process (explorer.exe for example) so that I may look into it a bit easier?

**Comment by unknownpk** [comment]
i will try make a temp app for you but right now my real life kinda got busy :( but i want to ask whats MAX scatter i can read?
AKA cpMEMs? because im doing like 100 to 500 depends on the memory so maybe this is the issue? 

DWORD VMMDLL_MemReadScatter(_In_ DWORD dwPID, _Inout_ PPMEM_SCATTER ppMEMs, _In_ DWORD cpMEMs, _In_ DWORD flags);

**Comment by ufrisk** [comment]
Thanks for looking into this and for understanding that these issues aren't easy for me to find without a reliable way of replicating the issue, hence me asking for the test program.

For the ScreamerM2 the maximum number of pages towards the FPGA device at one single time is 28. But the number of pages you may read via the scatter function should be unlimited (I would still recommend less than 16MB / 0x1000 pages at a time). The read request will go for the lock and then do repeated reads for 28 pages each time behind the lock if required.

**Comment by unknownpk** [comment]
yeah i know i understand so bad idea to do more then 28 hmm ill limit it tbh and btw can i ask why you never allow the user to call the function "VmmProcessGet" so a person COULD just enter the lock once and exit it once? that way its more faster etc? because i see ANY call to Read/Write it will call this function everytime? but wouldnt it be faster to call VmmProcessGet save it and then use it over and over?

**Comment by ufrisk** [comment]
The lock for fetching the process object is a separate lock. That lock doesn't trigger any IO and is very short lived. Unless contended (which should be very rare since it's held for such a short time) it should be super quick.

Main reason is that I wanted to keep the API as simple as possible; also I don't want to expose the internal objects since that would open up a big can of worms such as enabling user-after-free and memory leaks unless handled absolutely correctly by the user. And seeing it's not causing performance issues it should be fine as-is.

**Comment by ufrisk** [comment]
I just released a new easier-to-use memory read scatter API. While not exactly resolving the locking issue I hope things should improve in other areas.

Since there is no good way to completely resolve this I'm closing this issue.
