### ISSUE TITLE
config_refresh_enable cannot be enabled

### ISSUE THREAD

**Issue by lincoln123lin** [ufrisk/MemProcFS#74]
Hi, am having issues enabling the refresh by changing the value in config_refresh_enable from 0 to 1. The value does not get saved
![image](https://user-images.githubusercontent.com/16117585/130565545-917e74e0-ecd5-437a-9506-269dd49d3a0b.png)

I took a look in the command options MemProcFS has, but saw there is only the option to turn off refreshing (-norefresh). Since the refresh is not enabled by default, how do I enable it?

**Comment by ufrisk** [comment]
which memory source do you use? the fpga, driver, vm (i.e. live memory) or a memory dump file (i.e. static memory)?

It should be possible to enable refresh by writing `1` to the  `config_refresh_enable.txt` if refresh is supported by the underlying memory. If you're opening a dump file there is no need for refresh and it won't enable.

If you're unable to enable it when using live memory something strange would be going on which I'd have to look more into. It should be enabled by default then.

**Comment by lincoln123lin** [comment]
I am using the LiveCloudKd driver from gerhart to look at the live memory of a VM.

Launched MemProcFS with the following command: 

MemProcFS.exe -device hvmm -v

**Comment by ufrisk** [comment]
Hi,

If you try out the most recent version of LiveCloudKd this should be resolved by default. I haven't tried it yet; but it should now work without the extra options.

**Comment by lincoln123lin** [comment]
I have just tried it today. It works by default. I believe the flags are now reversed as the `hvmm://volatile` option is now `hvmm://nvolatile`

![image](https://user-images.githubusercontent.com/16117585/131428151-147f7ac7-e448-43c2-9087-3de82c84580f.png)

Shall leave the thread open as per your request
