### ISSUE TITLE
Using library inside a dll?

### ISSUE THREAD

**Issue by X3P0** [ufrisk/MemProcFS#84]
Is this idea possible?

I'm trying to use vmm.dll within another dll that is loaded into a process but it fails, this works when executing the following code outside of the dll in a basic console app but fails when loaded via LoadLibrary.

```
#include <vmmdll.h>
#pragma comment(lib, "vmm")

char* args[] = { (char*)"", (char*)"-device", (char*)"hvmm://id=0" };
BOOL result = VMMDLL_Initialize(3, args);

if (result) {
  g_Logger->Info("SUCCESS: VMMDLL_Initialize\n");
} else {
  g_Logger->Fail("FAIL: VMMDLL_Initialize\n");
}
```

**Comment by ufrisk** [comment]
I don't see why it shouldn't be possible. But vmm.dll and leechcore.dll probably have to be loaded properly into the process first by LoadLibrary or similar. They may have issues being injected. I haven't tested this use case.

**Comment by X3P0** [comment]
I see thanks, is there a way to see the error response from `VMMDLL_Initialize` to understand why it is failing, when I load via a DLL I don't see any console window and even if I AllocConsole to create one there is no output

**Comment by ufrisk** [comment]
you'd need to specify the printf option to enable printouts. it's disabled by defailt. Also verbose mode may be good to have.

`VMMDLL_Initialize(6, (LPSTR[]){"", "-printf ", "-v", "-vv", "-device", "hvmm://id=0"})`

**Comment by X3P0** [comment]
No joy :(

```
void MyAmazingThread(HMODULE hModule)
{
    AllocConsole();
    freopen_s((FILE**)stdout, "CONOUT$", "w", stdout);
    std::cout << "This works" << std::endl;
    printf("This works too\n");

    BOOL result;

    char* args[] = { (char*)"", (char*)"-printf", (char*)"-v", (char*)"-vv", (char*)"-device", (char*)"hvmm://id=0"};
    result = VMMDLL_Initialize(6, args);

    if (result)
        printf("SUCCESS: VMMDLL_Initialize\n");
    else
        printf("FAIL: VMMDLL_Initialize\n");
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved)
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
        CreateThread(0, 0, (LPTHREAD_START_ROUTINE)MyAmazingThread, hModule, 0, 0);
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
```

![alt text](https://i.imgur.com/6TkGQRn.png)

**Comment by ufrisk** [comment]
Unfortunately I don't have a clear answer why the printouts aren't working. This is how the MemprocFS itself is loading things. Maybe this will require some debugging :\ Also, since you're using hvmm I'm assuming you're running as elevated admin.

**Comment by X3P0** [comment]
Yeah was elevated, I'll close and try figure it out and will report back if I find out anything

**Comment by X3P0** [comment]
Interestingly this works with:

`-device M:\memory.pmem`

but the performance of that is real bad and would prefer to use hvmm

**Comment by ufrisk** [comment]
yeah, looping access through the dokany must be lousy performance. but it's interesting that it works. that means it's probably related to the hvmm.

There is a VMMDLL_InitializeEx function as well that may allow you to get out some info from the hvmm (if thats where the error is). Also you have to have the hvmm files alongside the vmm.dll/leechcore.dll for this to work.

Also this reminds me I have to code a new more flexible logging system around this...

**Comment by X3P0** [comment]
Thanks I've got hvmm.sys, leechcore_device_hvmm.dll and hvlib.dll in the same folder.

I think there is a issue starting the driver when loaded inside dll, do you know if it's possible to connect to an already started instance of hvmm?
