### ISSUE TITLE
Unable to get Memory Map

### ISSUE THREAD

**Issue by imerzan** [ufrisk/MemProcFS#87]
Hello! Thank you so much for your work. I encountered several issues while utilizing your vmmsharp library, and trying to generate a physical memory map programmatically.

I have tried several methods (from info I found in #42  & the wiki)

1. I tried calling ```vmm.Map_GetPhysMem()``` which returns a 0 length array.
2. I tried reading ```sys/memory/physmemmap.txt``` which returns a blank table:
```
   #         Base            Top
--------------------------------
```

Here is the code I am using:
```
                vmm.Initialize("-printf", "-v", "-device", "FPGA");
                vmm.InitializePlugins();
                vmm.VfsRead("sys/memory/physmemmap.txt", 4096, 0x0, out var map);
                File.WriteAllBytes("memmap.raw", map);
```

The target computer is running Windows 11. 
device firmware version 4.7
memprocfs 4.6

MemProcFs inits OK and can otherwise read memory.

**Comment by imerzan** [comment]
Hi! Just wondering if you have any ideas on this. I've tried both an older and most recent version of MemProcFs.

**Comment by ufrisk** [comment]
oh, I thought you closed the issue so that it went away, obviously not.

it's an issue with the memory map generation. It's working for me on Win11 with the latest patches though.

some ideas:
- device may read out of bounds on the win11 system and stop working somehow. Similar to this: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt
- you're missing additional supporting files `symsrv.dll` and/or `dbghelp.dll` which should be located next to `vmm.dll` or you answered no to the symbol server download question that pops up in a separate window. I'll update the "offline" symbols for this patch tuesday in next update.
- memory reads may fail for some other reason. after it failed is it working start memprocfs again? or will all reads fail?
- some other error. in this case I'd need you to do a memory dump (using pcileech dumpit or winpmem). after the dump is completed I'd need you to verify the issue still persists in it. and if possible after that I'll take a look at it if possible.

**Comment by imerzan** [comment]
Hi, thanks for the response!!

I will check some of this. It doesn't appear to be reading out of bounds (I've had this happen in the past and my target PC will lock up sometimes)

Also after attempting to get the physical memory map, I can still read virtual addresses via vmmdll and the device functions otherwise normally.

I will try the symbols.

**Comment by imerzan** [comment]
Used the Symbol Server and no change in behavior. Unable to get Phys Mem Map from attacking machine.

I am able to do a full dump using PciLeech without a map.

**Comment by ufrisk** [comment]
are you able to see the memory map if you analyze the dump?

if not, and the memory map issue persists in the dump as well, will you be able to share the dump so that I may locate the issue?

**Comment by imerzan** [comment]
I mounted the raw dump file via MemProcFs 4.6 and I am still unable to get a Memory Map via either method in the vmmsharp library :(

I am not sure of a good way to send this dump, it's ~33GB in size.

**Comment by ufrisk** [comment]
I would need it to try to see whats up. It usually compresses quite well. If you're able to upload it somewhere please send an email to me at pcileech@frizk.net with the link and I'll take a look.

**Comment by imerzan** [comment]
Hi, I appreciate it, but I decided to go another way for generating my memory maps, so this will no longer pose a problem for me. Thank you for all your assistance and your hard work on these libraries!

**Comment by imerzan** [comment]
@ufrisk I was eventually able to get this working. Posting my vmmsharp code here in case it helps anyone (Not sure why Map_GetPhysMem() is suddenly working, but hey I'll take it)

```csharp
        private static void GetMemMap()
        {
            try
            {
                var map = vmm.Map_GetPhysMem();
                if (map.Length == 0) throw new Exception("Map_GetPhysMem() returned no entries!");
                string mapOut = "";
                for (int i = 0; i < map.Length; i++)
                {
                    mapOut += $"{i.ToString("D4")}  {map[i].pa.ToString("x")}  -  {(map[i].pa + map[i].cb - 1).ToString("x")}  ->  {map[i].pa.ToString("x")}\n";
                }
                File.WriteAllText("mmap.txt", mapOut);
            }
            catch (Exception ex)
            {
                // log error
            }
        }
```

**Comment by ufrisk** [comment]
It's nice to see you got it to work. Many thanks for the update and best wishes with your DMA attacking 👍

**Comment by bbhxwl** [comment]
> @ufrisk I was eventually able to get this working. Posting my vmmsharp code here in case it helps anyone (Not sure why `Map_GetPhysMem()` is suddenly working, but hey I'll take it)
> 
> ```cs
>         private static void GetMemMap()
>         {
>             try
>             {
>                 var map = vmm.Map_GetPhysMem();
>                 if (map.Length == 0) throw new Exception("Map_GetPhysMem() returned no entries!");
>                 string mapOut = "";
>                 for (int i = 0; i < map.Length; i++)
>                 {
>                     mapOut += $"{i.ToString("D4")}  {map[i].pa.ToString("x")}  -  {(map[i].pa + map[i].cb - 1).ToString("x")}  ->  {map[i].pa.ToString("x")}\n";
>                 }
>                 File.WriteAllText("mmap.txt", mapOut);
>             }
>             catch (Exception ex)
>             {
>                 // handle error
>             }
>         }
> ```

Map_GetPhysMem
What does this code do? I'm reading DMA very slowly now. I don't know why. The log always outputs a list of all processes.

**Comment by ufrisk** [comment]
use `vmm.Initialize("-device", "FPGA");` instead of `vmm.Initialize("-printf", "-v", "-device", "FPGA");` to disable the extra debug outputs.

**Comment by bbhxwl** [comment]
> ```cs
> Map_GetPhysMem
> ```

I heard that I must use map_ Getphysmem, but I don't understand what this can do.

**Comment by ufrisk** [comment]
This function tries to retrieve the physical memory map of the target system - i.e. which physical memory regions are available for use to the operating system.

Sometimes the physical memory map is a good way of increasing DMA stability. You'd need to specify it at start-up though in those cases and you're usually retrieving it with other tools than MemProcFS in those cases. More info at: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt

**Comment by bbhxwl** [comment]
> This function tries to retrieve the physical memory map of the target system - i.e. which physical memory regions are available for use to the operating system.
> 
> Sometimes the physical memory map is a good way of increasing DMA stability. You'd need to specify it at start-up though in those cases and you're usually retrieving it with other tools than MemProcFS in those cases. More info at: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt

Can this project also use DMA to read the local J memory?

**Comment by ufrisk** [comment]
J memory?

**Comment by bbhxwl** [comment]
> J memory?

I mean, get the memory of your own computer, not the memory of another computer through DMA.

**Comment by ufrisk** [comment]
Yes, it supports drivers such as DumpIt or Winpmem. It also supports Hyper-V and VMWare virtual machines.

**Comment by bbhxwl** [comment]
> Yes, it supports drivers such as DumpIt or Winpmem. It also supports Hyper-V and VMWare virtual machines.

 DumpIt or Winpmem
Is there a tutorial on how to read memory? I want to try to use this library to read the memory of the local machine. C # usually cannot write drivers, so it cannot read protected processes.

**Comment by ufrisk** [comment]
Please understand that this is an open source project and that I'm not getting paid to answer a huge number of questions from you.

This is described in main readme on this project
```
To capture live memory (without PCILeech FPGA hardware) download [DumpIt](https://www.comae.com/) and start MemProcFS via DumpIt /LIVEKD mode. Alternatively, get WinPMEM by downloading the most recent signed [WinPMEM driver](https://github.com/Velocidex/c-aff4/tree/master/tools/pmem/resources/winpmem) and place it alongside MemProcFS - detailed instructions in the [LeechCore Wiki](https://github.com/ufrisk/LeechCore/wiki/Device_WinPMEM).
```

Also have a look here: https://github.com/ufrisk/LeechCore/wiki/Device_WinPMEM

Basically start your program as elevated admin and then pass the option parameters: `-device pmem://c:\temp\winpmem_x64.sys`

I would greatly appreciate if you could at least have a quick look at the readme before asking questions in the future.

Thanks.

**Comment by bbhxwl** [comment]
> Please understand that this is an open source project and that I'm not getting paid to answer a huge number of questions from you.
> 
> This is described in main readme on this project
> 
> **To capture live memory (without PCILeech FPGA hardware) download [DumpIt](https://www.comae.com/) and start MemProcFS via DumpIt /LIVEKD mode. Alternatively, get WinPMEM by downloading the most recent signed [WinPMEM driver](https://github.com/Velocidex/c-aff4/tree/master/tools/pmem/resources/winpmem) and place it alongside MemProcFS - detailed instructions in the [LeechCore Wiki](https://github.com/ufrisk/LeechCore/wiki/Device_WinPMEM).**
> 
> Also have a look here: https://github.com/ufrisk/LeechCore/wiki/Device_WinPMEM
> 
> Basically start your program as elevated admin and then pass the option parameters: `-device pmem://c:\temp\winpmem_x64.sys`
> 
> I would greatly appreciate if you could at least have a quick look at the readme before asking questions in the future.
> 
> Thanks.

Thank you. My English is poor, but I only know C #. It seems that many documents only explain C++. Sorry, if you are busy, you can not reply to me. This project is very good, and I will sponsor it

**Comment by ufrisk** [comment]
Hi, please use `vmm = vmm.Initialize("-device", "[FPGA](pmem://c:\\temp\\winpmem_x64.sys)");` in C#.
