### ISSUE TITLE
Writing to memory broken in Python API

### ISSUE THREAD

**Issue by afrishling** [ufrisk/MemProcFS#89]
Hi Ulf

I saw this behaviour in MemProcFS v4.4 and confirmed it exists in MemProcFS V4.7 before trying to track it down in the MemProcFS code.

When trying to write to the memory space of an application using the Python API (process.memory.write()), I consistently got the error "RuntimeError: VirtualMemory.write(): Failed." and no data appeared to be written. I also attempted to write to this location by converting to a physical address and writing through the vmm API (process.memory.virt2phys() and vmm.memory.write()), which did not throw an exception, but the data was apparently not written to the target.

I confirmed it was not an issue with connection to the target or in LeechCore by using MemProcFS to mount the target memory and writing to the correct virtual address using the process's virtual memory file and a hex editor.

I have had a look through the code, and it looks like there is an error in parsing the arguments to both of the Python functions in the [below line](https://github.com/ufrisk/MemProcFS/blob/35c41a205c1165b62f7f57bb3a36833870cf820a/vmmpyc/vmmpyc.c#L96).
`if(!PyArg_ParseTuple(args, "Ky#", &dwPID, &va, &pb, &cb)) {`
dwPID already has the correct value as it is passed as an argument to this function, so the inclusion of it in the argument parsing incorrectly overwrites its value and results in the other variables to receive the wrong values. The wrong PID only being present explains why there is an error for writing to a process (since the that PID probably doesn't exist), while writing directly to physical memory succeeds (but either writes to the wrong address or writes no data).

I have not yet had a chance to make the change and test it myself, but I have compared it to how the arguments are parsed when reading from memory (which does work correctly for me).

Thanks again for the great project :-)

**Comment by ufrisk** [comment]
Thank you for this excellent bug report. My test cases aren't covering the write path as well as it should.

Anyway, I hope it should be fixed in the version I just published. Please let me know if the issue is resolved.

**Comment by afrishling** [comment]
I've confirmed that both write functions now work as expected in v4.7.1
