### ISSUE TITLE
build x32 vmm fail

### ISSUE THREAD

**Issue by harryismystar** [ufrisk/MemProcFS#92]
Sorry to ask a simple question. I wanna build a x32 vmm.dll, but get this error, is there anything wrong in setting that i miss:

Rebuild started...
1>------ Rebuild All started: Project: vmm, Configuration: Debug Win32 ------
1>        1 file(s) copied.
1>charutil.c
1>fc.c
1>infodb.c
1>mm_pfn.c
1>mm_vad.c
1>mm_win.c
1>mm_x64.c
1>mm_x86.c
1>mm_x86pae.c
1>m_conf.c
1>m_fc_json.c
1>m_fc_module.c
1>m_fc_ntfs.c
1>m_fc_proc.c
1>m_fc_registry.c
1>m_fc_thread.c
1>m_fc_timeline.c
1>m_file_handles_vads.c
1>m_file_modules.c
1>m_findevil.c
1>Generating Code...
1>Compiling...
1>m_handle.c
1>m_memmap.c
1>m_minidump.c
1>m_phys2virt.c
1>m_proc_search.c
1>m_proc_token.c
1>m_sys.c
1>m_sys_cert.c
1>m_sys_driver.c
1>m_sys_mem.c
1>m_sys_net.c
1>m_sys_obj.c
1>m_sys_pool.c
1>m_sys_proc.c
1>m_sys_svc.c
1>m_sys_syscall.c
1>m_sys_task.c
1>m_thread.c
1>m_vfsfc.c
1>m_vfsproc.c
1>Generating Code...
1>Compiling...
1>m_vfsroot.c
1>m_winreg.c
1>ob_cachemap.c
1>ob_compressed.c
1>ob_container.c
1>ob_core.c
1>ob_counter.c
1>ob_map.c
1>ob_memfile.c
1>ob_set.c
1>ob_strmap.c
1>oscompatibility.c
1>pdb.c
1>pe.c
1>sqlite3.c
1>statistics.c
1>sysquery.c
1>util.c
1>vmm.c
1>vmmdll.c
1>Generating Code...
1>Compiling...
1>m_ldrmodules.c
1>vmmdll_scatter.c
1>vmmevil.c
1>vmmlog.c
1>vmmnet.c
1>vmmproc.c
1>vmmwin.c
1>pluginmanager.c
1>m_virt2phys.c
1>vmmwininit.c
1>vmmwinobj.c
1>vmmwinpool.c
1>vmmwinreg.c
1>vmmwinsvc.c
1>Generating Code...
1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(1087,5): error MSB6006: "link.exe" exited with code 1112.
1>C:\Users\xxxx\Desktop\MemProcFS-4.7\files\temp\vmm\x86\charutil.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'
1>Done building project "vmm.vcxproj" -- FAILED.

**Comment by ufrisk** [comment]
Thanks you for reporting this. There was an error in the debug build configuration (release configuration was working fine). But it should now work with the changes I just pushed.

It's not ideal to run MemProcFS as a 32-bit process though (even if it will work) since it's a bit of a memory hog.

Please let me know if this works better for you.

**Comment by harryismystar** [comment]
works fine, thanks!
