### ISSUE TITLE
A possible bug in forensic ntfs module

### ISSUE THREAD

**Issue by herosi** [ufrisk/MemProcFS#94]
Hi, thank you for the amazing project.
I found a possible bug on ntfs module on MemProcFs 4.3.6 or later. 

I tested MemProcFs 4.0.3, 4.1.0, 4.2.3, 4.3.6, 4.4.0, 4.5.1 and 4.7.8.
I tested on a Win11 box and used dokan 2.0.3.2000 and 1.3.1.1000.
And I tested a Win11 memory image.

I used the same memory image and almost the same options below except for the -mount option.

`MemProcFS.exe -device physmem.raw -pagefile0 pagefile.sys -pagefile1 swapfile.sys -mount o
`

The test results are here.

`dir ntfs_results\ | select name,length
`

> Name                 Length
> ----                 ------
> ntfs_files_4.0.3.txt 374662
> ntfs_files_4.1.0.txt 374662
> ntfs_files_4.2.3.txt 374662
> ntfs_files_4.3.6.txt 139920
> ntfs_files_4.4.0.txt 139920
> ntfs_files_4.5.1.txt 139920
> ntfs_files_4.7.8.txt 139920
> 

`Get-FileHash -Algorithm SHA256 ntfs_results\*  | Format-Table -AutoSize -Wrap
`

> Algorithm Hash                                                             Path
> --------- ----                                                             ----
> SHA256    4CF2EE1631813373EA508B15CC14C707AB00A0C15DA8DC6F52C02CA09D47A467 ntfs_results\ntfs_files_4.0.3.txt
> SHA256    4CF2EE1631813373EA508B15CC14C707AB00A0C15DA8DC6F52C02CA09D47A467 ntfs_results\ntfs_files_4.1.0.txt
> SHA256    4CF2EE1631813373EA508B15CC14C707AB00A0C15DA8DC6F52C02CA09D47A467 ntfs_results\ntfs_files_4.2.3.txt
> SHA256    9FAAD97A65698C4523A94F96775C02CC75BCE99F52078E85CE1A7A541D95197D ntfs_results\ntfs_files_4.3.6.txt
> SHA256    9FAAD97A65698C4523A94F96775C02CC75BCE99F52078E85CE1A7A541D95197D ntfs_results\ntfs_files_4.4.0.txt
> SHA256    9FAAD97A65698C4523A94F96775C02CC75BCE99F52078E85CE1A7A541D95197D ntfs_results\ntfs_files_4.5.1.txt
> SHA256    9FAAD97A65698C4523A94F96775C02CC75BCE99F52078E85CE1A7A541D95197D ntfs_results\ntfs_files_4.7.8.txt
> 

It seems after 4.3.x, the module would have had a bug. From that version, the result seems to be decreased by about one-third.
Could you check it?
If you need my memory image, I can share it with you.

**Comment by ufrisk** [comment]
I changed the implementation back between those versions (had to do it because of other things), and I added some extra checks to increase quality and skip over some memory to increase speed. The result hash should differ between these versions. I would have expected a slightly smaller size in the new version, But a 3:1 size difference is extreme. Many thanks for reporting this. I'll look into it.

Maybe I added too many quality checks or something broke, either in my implementation at the time or in Windows 11.

If possible, it would be nice to have your copy so we're looking at the same material.

**Comment by herosi** [comment]
I have sent the link to your twitter account,

**Comment by ufrisk** [comment]
Thanks for this bug report. I fixed a number of issues in the update I just made available (download latest updated release).

It was a hash collision that only materialized if you had the offline symbol pack that I provide. Making the PFN database parsing to fail corrupt, which then affected NTFS parsing. Nevertheless it ought to be fixed now.

Please let me know if you come across some more issues, or if you feel some functionality should be added.

Once again, Thank You for this bug report!

**Comment by herosi** [comment]
I'm the one who need to say thank you!
Thank you for the super rapid response!
