### ISSUE TITLE
Registry data for several special accounts are not listed

### ISSUE THREAD

**Issue by unk0unk0unk0** [ufrisk/MemProcFS#97]
The registry data for the accounts bellow are not displayed under the folder "\registry\HKU". Those are only displayed under the folder "\registry\by-hive".
- S-1-5-18 (STSTEM/LocalSystem) 
- .DEFAULT (an alias of the one above)
- S-1-5-19 (LocalService)
- S-1-5-20 (NetworkService)

I think those should be listed under the folder "\registry\HKU" as Registry Editor displays.

![Picture1](https://user-images.githubusercontent.com/51192060/165697658-a3efb18e-7ae5-43c0-9345-3ad3fc625c96.jpg)

I found this issue by parsing a Win10 memory image with MemProcFS 4.7.10.

**Comment by ufrisk** [comment]
Thank You for this excellent suggestion. It's easy enough to add so I've done it in the v4.7.11 release I just pushed. Thanks!

**Comment by unk0unk0unk0** [comment]
It works well on my environment. Thank you for your quick excellent update.
